import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const source = fileURLToPath(new URL('../wasm/entities.c', import.meta.url));
const target = fileURLToPath(new URL('../src/parser/entities/entityWasmBytes.ts', import.meta.url));
// Reference wire semantics are part of the check: changes require reviewing the C implementation.
const hash = createHash('sha256').update(readFileSync(source));
for (const path of ['fieldPathOps.ts', 'quantizedFloat.ts', '../ubitreader.ts'])
	hash.update(readFileSync(fileURLToPath(new URL(`../src/parser/entities/${path}`, import.meta.url))));
const digest = hash.digest('hex');
if (process.argv.includes('--check')) {
	if (!readFileSync(target, 'utf8').includes(`Source SHA-256: ${digest}`))
		throw new Error('Entity WASM/reference source changed; run npm run build:entities');
} else {
	const dir = mkdtempSync(join(tmpdir(), 'cs2parser-entities-'));
	try {
		const wasm = join(dir, 'entities.wasm');
		execFileSync(
			'clang',
			[
				'--target=wasm32',
				'-O3',
				'-mbulk-memory',
				'-ffp-contract=off',
				'-nostdlib',
				'-fno-builtin',
				'-Wl,--no-entry',
				'-Wl,--export=ptr',
				'-Wl,--export=packet',
				'-Wl,--export-memory',
				'-Wl,--strip-all',
				source,
				'-o',
				wasm
			],
			{ stdio: 'inherit' }
		);
		const bytes = readFileSync(wasm);
		writeFileSync(
			target,
			`// Generated by scripts/build-entities-wasm.ts. Do not edit.\n// Source SHA-256: ${digest}\nexport const entityWasmBase64 =\n\t'${bytes.toString('base64')}';\n`
		);
		console.log(`Embedded ${bytes.length} bytes of entity WASM`);
	} finally {
		rmSync(dir, { recursive: true, force: true });
	}
}
