import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const source = fileURLToPath(new URL('../wasm/snappy.c', import.meta.url));
const target = fileURLToPath(new URL('../src/compression/snappyWasmBytes.ts', import.meta.url));
const hash = createHash('sha256').update(readFileSync(source)).digest('hex');

if (process.argv.includes('--check')) {
	if (!readFileSync(target, 'utf8').includes(`Source SHA-256: ${hash}`)) {
		throw new Error('Snappy WASM source changed; run npm run build:snappy');
	}
} else {
	const dir = mkdtempSync(join(tmpdir(), 'cs2parser-snappy-'));
	try {
		const wasm = join(dir, 'snappy.wasm');
		execFileSync(
			'clang',
			[
				'--target=wasm32',
				'-O3',
				'-mbulk-memory', // Lower literal memcpy to memory.copy without libc imports.
				'-nostdlib',
				'-fno-builtin',
				'-Wl,--no-entry',
				'-Wl,--export=snappy_uncompress',
				'-Wl,--export=__heap_base',
				'-Wl,--export-memory',
				'-Wl,--strip-all',
				source,
				'-o',
				wasm
			],
			{ stdio: 'inherit' }
		);
		const bytes = readFileSync(wasm);
		writeFileSync(
			target,
			`// Generated by scripts/build-snappy-wasm.ts. Do not edit.\n// Source SHA-256: ${hash}\nexport const snappyWasmBase64 =\n\t'${bytes.toString('base64')}';\n`
		);
		console.log(`Embedded ${bytes.length} bytes of Snappy WASM`);
	} finally {
		rmSync(dir, { recursive: true, force: true });
	}
}
