import { readFileSync, writeFileSync } from 'node:fs';

const source = new URL('../src/broadcast/default-event-descriptors.bin', import.meta.url);
const target = new URL('../src/broadcast/defaultEventDescriptorBytes.ts', import.meta.url);
const bytes = readFileSync(source);
const content = `// Generated by scripts/generate-broadcast-descriptors.ts. Do not edit.\n// prettier-ignore\nexport const defaultEventDescriptorBase64 = '${bytes.toString('base64')}';\n`;
if (process.argv.includes('--check')) {
	if (readFileSync(target, 'utf8') !== content) throw new Error('Run npm run generate:broadcast-descriptors');
} else {
	writeFileSync(target, content);
}
