// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: c_peer2peer_netmessages.proto

/* eslint-disable */
import { BinaryReader } from "@bufbuild/protobuf/wire";
import { CMsgVoiceAudio } from "./netmessages.js";
import { CMsgQAngle, CMsgVector } from "./networkbasetypes.js";

export const protobufPackage = "";

export const P2P_Messages = {
  p2p_TextMessage: 256,
  p2p_Voice: 257,
  p2p_Ping: 258,
  p2p_VRAvatarPosition: 259,
  p2p_WatchSynchronization: 260,
  p2p_FightingGame_GameData: 261,
  p2p_FightingGame_Connection: 262,
  UNRECOGNIZED: -1,
} as const;

export type P2P_Messages = typeof P2P_Messages[keyof typeof P2P_Messages];

export namespace P2P_Messages {
  export type p2p_TextMessage = typeof P2P_Messages.p2p_TextMessage;
  export type p2p_Voice = typeof P2P_Messages.p2p_Voice;
  export type p2p_Ping = typeof P2P_Messages.p2p_Ping;
  export type p2p_VRAvatarPosition = typeof P2P_Messages.p2p_VRAvatarPosition;
  export type p2p_WatchSynchronization = typeof P2P_Messages.p2p_WatchSynchronization;
  export type p2p_FightingGame_GameData = typeof P2P_Messages.p2p_FightingGame_GameData;
  export type p2p_FightingGame_Connection = typeof P2P_Messages.p2p_FightingGame_Connection;
  export type UNRECOGNIZED = typeof P2P_Messages.UNRECOGNIZED;
}

export interface CP2P_TextMessage {
  text?: Uint8Array | undefined;
}

export interface CSteam_Voice_Encoding {
  voice_data?: Uint8Array | undefined;
}

export interface CP2P_Voice {
  audio?: CMsgVoiceAudio | undefined;
  broadcast_group?: number | undefined;
}

export const CP2P_Voice_Handler_Flags = { Played_Audio: 1, UNRECOGNIZED: -1 } as const;

export type CP2P_Voice_Handler_Flags = typeof CP2P_Voice_Handler_Flags[keyof typeof CP2P_Voice_Handler_Flags];

export namespace CP2P_Voice_Handler_Flags {
  export type Played_Audio = typeof CP2P_Voice_Handler_Flags.Played_Audio;
  export type UNRECOGNIZED = typeof CP2P_Voice_Handler_Flags.UNRECOGNIZED;
}

export interface CP2P_Ping {
  send_time?: string | undefined;
  is_reply?: boolean | undefined;
}

export interface CP2P_VRAvatarPosition {
  body_parts: CP2P_VRAvatarPosition_COrientation[];
  hat_id?: number | undefined;
  scene_id?: number | undefined;
  world_scale?: number | undefined;
}

export interface CP2P_VRAvatarPosition_COrientation {
  pos?: CMsgVector | undefined;
  ang?: CMsgQAngle | undefined;
}

export interface CP2P_WatchSynchronization {
  demo_tick?: number | undefined;
  paused?: boolean | undefined;
  tv_listen_voice_indices?: string | undefined;
  dota_spectator_mode?: number | undefined;
  dota_spectator_watching_broadcaster?: boolean | undefined;
  dota_spectator_hero_index?: number | undefined;
  dota_spectator_autospeed?: number | undefined;
  dota_replay_speed?: number | undefined;
}

function createBaseCP2P_TextMessage(): CP2P_TextMessage {
  return { text: undefined };
}

export const CP2P_TextMessage: MessageFns<CP2P_TextMessage> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CP2P_TextMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCP2P_TextMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCSteam_Voice_Encoding(): CSteam_Voice_Encoding {
  return { voice_data: undefined };
}

export const CSteam_Voice_Encoding: MessageFns<CSteam_Voice_Encoding> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CSteam_Voice_Encoding {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCSteam_Voice_Encoding();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.voice_data = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCP2P_Voice(): CP2P_Voice {
  return { audio: undefined, broadcast_group: undefined };
}

export const CP2P_Voice: MessageFns<CP2P_Voice> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CP2P_Voice {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCP2P_Voice();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.audio = CMsgVoiceAudio.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.broadcast_group = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCP2P_Ping(): CP2P_Ping {
  return { send_time: undefined, is_reply: undefined };
}

export const CP2P_Ping: MessageFns<CP2P_Ping> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CP2P_Ping {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCP2P_Ping();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.send_time = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.is_reply = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCP2P_VRAvatarPosition(): CP2P_VRAvatarPosition {
  return { body_parts: [], hat_id: undefined, scene_id: undefined, world_scale: undefined };
}

export const CP2P_VRAvatarPosition: MessageFns<CP2P_VRAvatarPosition> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CP2P_VRAvatarPosition {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCP2P_VRAvatarPosition();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.body_parts.push(CP2P_VRAvatarPosition_COrientation.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.hat_id = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.scene_id = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.world_scale = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCP2P_VRAvatarPosition_COrientation(): CP2P_VRAvatarPosition_COrientation {
  return { pos: undefined, ang: undefined };
}

export const CP2P_VRAvatarPosition_COrientation: MessageFns<CP2P_VRAvatarPosition_COrientation> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CP2P_VRAvatarPosition_COrientation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCP2P_VRAvatarPosition_COrientation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pos = CMsgVector.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ang = CMsgQAngle.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCP2P_WatchSynchronization(): CP2P_WatchSynchronization {
  return {
    demo_tick: undefined,
    paused: undefined,
    tv_listen_voice_indices: undefined,
    dota_spectator_mode: undefined,
    dota_spectator_watching_broadcaster: undefined,
    dota_spectator_hero_index: undefined,
    dota_spectator_autospeed: undefined,
    dota_replay_speed: undefined,
  };
}

export const CP2P_WatchSynchronization: MessageFns<CP2P_WatchSynchronization> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CP2P_WatchSynchronization {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCP2P_WatchSynchronization();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.demo_tick = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.paused = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.tv_listen_voice_indices = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.dota_spectator_mode = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.dota_spectator_watching_broadcaster = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.dota_spectator_hero_index = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.dota_spectator_autospeed = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.dota_replay_speed = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface MessageFns<T> {
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
