// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: clientmessages.proto

/* eslint-disable */
import { BinaryReader } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export const EBaseClientMessages = {
  CM_CustomGameEvent: 280,
  CM_CustomGameEventBounce: 281,
  CM_ClientUIEvent: 282,
  CM_DevPaletteVisibilityChanged: 283,
  CM_WorldUIControllerHasPanelChanged: 284,
  CM_RotateAnchor: 285,
  CM_MAX_BASE: 300,
  UNRECOGNIZED: -1,
} as const;

export type EBaseClientMessages = typeof EBaseClientMessages[keyof typeof EBaseClientMessages];

export namespace EBaseClientMessages {
  export type CM_CustomGameEvent = typeof EBaseClientMessages.CM_CustomGameEvent;
  export type CM_CustomGameEventBounce = typeof EBaseClientMessages.CM_CustomGameEventBounce;
  export type CM_ClientUIEvent = typeof EBaseClientMessages.CM_ClientUIEvent;
  export type CM_DevPaletteVisibilityChanged = typeof EBaseClientMessages.CM_DevPaletteVisibilityChanged;
  export type CM_WorldUIControllerHasPanelChanged = typeof EBaseClientMessages.CM_WorldUIControllerHasPanelChanged;
  export type CM_RotateAnchor = typeof EBaseClientMessages.CM_RotateAnchor;
  export type CM_MAX_BASE = typeof EBaseClientMessages.CM_MAX_BASE;
  export type UNRECOGNIZED = typeof EBaseClientMessages.UNRECOGNIZED;
}

export const EClientUIEvent = {
  EClientUIEvent_Invalid: 0,
  EClientUIEvent_DialogFinished: 1,
  EClientUIEvent_FireOutput: 2,
  UNRECOGNIZED: -1,
} as const;

export type EClientUIEvent = typeof EClientUIEvent[keyof typeof EClientUIEvent];

export namespace EClientUIEvent {
  export type EClientUIEvent_Invalid = typeof EClientUIEvent.EClientUIEvent_Invalid;
  export type EClientUIEvent_DialogFinished = typeof EClientUIEvent.EClientUIEvent_DialogFinished;
  export type EClientUIEvent_FireOutput = typeof EClientUIEvent.EClientUIEvent_FireOutput;
  export type UNRECOGNIZED = typeof EClientUIEvent.UNRECOGNIZED;
}

export interface CClientMsg_CustomGameEvent {
  event_name?: string | undefined;
  data?: Uint8Array | undefined;
}

export interface CClientMsg_CustomGameEventBounce {
  event_name?: string | undefined;
  data?: Uint8Array | undefined;
  player_slot?: number | undefined;
}

export interface CClientMsg_ClientUIEvent {
  event?: EClientUIEvent | undefined;
  ent_ehandle?: number | undefined;
  client_ehandle?: number | undefined;
  data1?: string | undefined;
  data2?: string | undefined;
}

export interface CClientMsg_DevPaletteVisibilityChangedEvent {
  visible?: boolean | undefined;
}

export interface CClientMsg_WorldUIControllerHasPanelChangedEvent {
  has_panel?: boolean | undefined;
  client_ehandle?: number | undefined;
  literal_hand_type?: number | undefined;
}

export interface CClientMsg_RotateAnchor {
  angle?: number | undefined;
}

function createBaseCClientMsg_CustomGameEvent(): CClientMsg_CustomGameEvent {
  return { event_name: undefined, data: undefined };
}

export const CClientMsg_CustomGameEvent: MessageFns<CClientMsg_CustomGameEvent> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CClientMsg_CustomGameEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCClientMsg_CustomGameEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.event_name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCClientMsg_CustomGameEventBounce(): CClientMsg_CustomGameEventBounce {
  return { event_name: undefined, data: undefined, player_slot: undefined };
}

export const CClientMsg_CustomGameEventBounce: MessageFns<CClientMsg_CustomGameEventBounce> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CClientMsg_CustomGameEventBounce {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCClientMsg_CustomGameEventBounce();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.event_name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.player_slot = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCClientMsg_ClientUIEvent(): CClientMsg_ClientUIEvent {
  return { event: undefined, ent_ehandle: undefined, client_ehandle: undefined, data1: undefined, data2: undefined };
}

export const CClientMsg_ClientUIEvent: MessageFns<CClientMsg_ClientUIEvent> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CClientMsg_ClientUIEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCClientMsg_ClientUIEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.event = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.ent_ehandle = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.client_ehandle = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data1 = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.data2 = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCClientMsg_DevPaletteVisibilityChangedEvent(): CClientMsg_DevPaletteVisibilityChangedEvent {
  return { visible: undefined };
}

export const CClientMsg_DevPaletteVisibilityChangedEvent: MessageFns<CClientMsg_DevPaletteVisibilityChangedEvent> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CClientMsg_DevPaletteVisibilityChangedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCClientMsg_DevPaletteVisibilityChangedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.visible = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCClientMsg_WorldUIControllerHasPanelChangedEvent(): CClientMsg_WorldUIControllerHasPanelChangedEvent {
  return { has_panel: undefined, client_ehandle: undefined, literal_hand_type: undefined };
}

export const CClientMsg_WorldUIControllerHasPanelChangedEvent: MessageFns<
  CClientMsg_WorldUIControllerHasPanelChangedEvent
> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CClientMsg_WorldUIControllerHasPanelChangedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCClientMsg_WorldUIControllerHasPanelChangedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.has_panel = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.client_ehandle = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.literal_hand_type = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCClientMsg_RotateAnchor(): CClientMsg_RotateAnchor {
  return { angle: undefined };
}

export const CClientMsg_RotateAnchor: MessageFns<CClientMsg_RotateAnchor> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CClientMsg_RotateAnchor {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCClientMsg_RotateAnchor();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.angle = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface MessageFns<T> {
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
