// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: cs_gameevents.proto

/* eslint-disable */
import { BinaryReader } from "@bufbuild/protobuf/wire";
import { CMsgQAngle, CMsgVector } from "./networkbasetypes.js";

export const protobufPackage = "";

export const ECsgoGameEvents = {
  GE_PlayerAnimEventId: 450,
  GE_RadioIconEventId: 451,
  GE_FireBulletsId: 452,
  GE_PlayerBulletHitId: 453,
  UNRECOGNIZED: -1,
} as const;

export type ECsgoGameEvents = typeof ECsgoGameEvents[keyof typeof ECsgoGameEvents];

export namespace ECsgoGameEvents {
  export type GE_PlayerAnimEventId = typeof ECsgoGameEvents.GE_PlayerAnimEventId;
  export type GE_RadioIconEventId = typeof ECsgoGameEvents.GE_RadioIconEventId;
  export type GE_FireBulletsId = typeof ECsgoGameEvents.GE_FireBulletsId;
  export type GE_PlayerBulletHitId = typeof ECsgoGameEvents.GE_PlayerBulletHitId;
  export type UNRECOGNIZED = typeof ECsgoGameEvents.UNRECOGNIZED;
}

export interface CMsgTEPlayerAnimEvent {
  player?: number | undefined;
  event?: number | undefined;
  data?: number | undefined;
}

export interface CMsgTERadioIcon {
  player?: number | undefined;
}

export interface CMsgTEFireBullets {
  origin?: CMsgVector | undefined;
  angles?: CMsgQAngle | undefined;
  weapon_id?: number | undefined;
  mode?: number | undefined;
  seed?: number | undefined;
  player?: number | undefined;
  inaccuracy?: number | undefined;
  recoil_index?: number | undefined;
  spread?: number | undefined;
  sound_type?: number | undefined;
  item_def_index?: number | undefined;
  sound_dsp_effect?: number | undefined;
  ent_origin?: CMsgVector | undefined;
  num_bullets_remaining?: number | undefined;
  attack_type?: number | undefined;
  player_inair?: boolean | undefined;
  player_scoped?: boolean | undefined;
  tick?: number | undefined;
  extra?: CMsgTEFireBullets_Extra | undefined;
}

export interface CMsgTEFireBullets_Extra {
  aim_punch?: CMsgQAngle | undefined;
  attack_tick_count?: number | undefined;
  attack_tick_frac?: number | undefined;
  render_tick_count?: number | undefined;
  render_tick_frac?: number | undefined;
  inaccuracy_move?: number | undefined;
  inaccuracy_air?: number | undefined;
  type?: number | undefined;
}

export interface CMsgPlayerBulletHit {
  attacker_slot?: number | undefined;
  victim_slot?: number | undefined;
  victim_pos?: CMsgVector | undefined;
  hit_group?: number | undefined;
  damage?: number | undefined;
  penetration_count?: number | undefined;
  is_kill?: boolean | undefined;
  through_smoke?: boolean | undefined;
}

function createBaseCMsgTEPlayerAnimEvent(): CMsgTEPlayerAnimEvent {
  return { player: undefined, event: undefined, data: undefined };
}

export const CMsgTEPlayerAnimEvent: MessageFns<CMsgTEPlayerAnimEvent> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgTEPlayerAnimEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgTEPlayerAnimEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.player = reader.fixed32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.event = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.data = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgTERadioIcon(): CMsgTERadioIcon {
  return { player: undefined };
}

export const CMsgTERadioIcon: MessageFns<CMsgTERadioIcon> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgTERadioIcon {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgTERadioIcon();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.player = reader.fixed32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgTEFireBullets(): CMsgTEFireBullets {
  return {
    origin: undefined,
    angles: undefined,
    weapon_id: undefined,
    mode: undefined,
    seed: undefined,
    player: undefined,
    inaccuracy: undefined,
    recoil_index: undefined,
    spread: undefined,
    sound_type: undefined,
    item_def_index: undefined,
    sound_dsp_effect: undefined,
    ent_origin: undefined,
    num_bullets_remaining: undefined,
    attack_type: undefined,
    player_inair: undefined,
    player_scoped: undefined,
    tick: undefined,
    extra: undefined,
  };
}

export const CMsgTEFireBullets: MessageFns<CMsgTEFireBullets> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgTEFireBullets {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgTEFireBullets();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.origin = CMsgVector.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.angles = CMsgQAngle.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.weapon_id = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.mode = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.seed = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 53) {
            break;
          }

          message.player = reader.fixed32();
          continue;
        }
        case 7: {
          if (tag !== 61) {
            break;
          }

          message.inaccuracy = reader.float();
          continue;
        }
        case 8: {
          if (tag !== 69) {
            break;
          }

          message.recoil_index = reader.float();
          continue;
        }
        case 9: {
          if (tag !== 77) {
            break;
          }

          message.spread = reader.float();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.sound_type = reader.int32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.item_def_index = reader.uint32();
          continue;
        }
        case 12: {
          if (tag !== 101) {
            break;
          }

          message.sound_dsp_effect = reader.fixed32();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.ent_origin = CMsgVector.decode(reader, reader.uint32());
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.num_bullets_remaining = reader.uint32();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.attack_type = reader.uint32();
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.player_inair = reader.bool();
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.player_scoped = reader.bool();
          continue;
        }
        case 19: {
          if (tag !== 152) {
            break;
          }

          message.tick = reader.int32();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.extra = CMsgTEFireBullets_Extra.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgTEFireBullets_Extra(): CMsgTEFireBullets_Extra {
  return {
    aim_punch: undefined,
    attack_tick_count: undefined,
    attack_tick_frac: undefined,
    render_tick_count: undefined,
    render_tick_frac: undefined,
    inaccuracy_move: undefined,
    inaccuracy_air: undefined,
    type: undefined,
  };
}

export const CMsgTEFireBullets_Extra: MessageFns<CMsgTEFireBullets_Extra> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgTEFireBullets_Extra {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgTEFireBullets_Extra();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.aim_punch = CMsgQAngle.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.attack_tick_count = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.attack_tick_frac = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.render_tick_count = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.render_tick_frac = reader.float();
          continue;
        }
        case 6: {
          if (tag !== 53) {
            break;
          }

          message.inaccuracy_move = reader.float();
          continue;
        }
        case 7: {
          if (tag !== 61) {
            break;
          }

          message.inaccuracy_air = reader.float();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.type = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgPlayerBulletHit(): CMsgPlayerBulletHit {
  return {
    attacker_slot: undefined,
    victim_slot: undefined,
    victim_pos: undefined,
    hit_group: undefined,
    damage: undefined,
    penetration_count: undefined,
    is_kill: undefined,
    through_smoke: undefined,
  };
}

export const CMsgPlayerBulletHit: MessageFns<CMsgPlayerBulletHit> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgPlayerBulletHit {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgPlayerBulletHit();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.attacker_slot = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.victim_slot = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.victim_pos = CMsgVector.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.hit_group = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.damage = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.penetration_count = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.is_kill = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.through_smoke = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface MessageFns<T> {
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
