// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: cs_usercmd.proto

/* eslint-disable */
import { BinaryReader } from "@bufbuild/protobuf/wire";
import { CMsgQAngle, CMsgVector } from "./networkbasetypes.js";
import { CBaseUserCmdPB } from "./usercmd.js";

export const protobufPackage = "";

export interface CSGOInterpolationInfoPB {
  src_tick?: number | undefined;
  dst_tick?: number | undefined;
  frac?: number | undefined;
}

export interface CSGOInterpolationInfoPB_CL {
  frac?: number | undefined;
}

export interface CSGOInputHistoryEntryPB {
  view_angles?: CMsgQAngle | undefined;
  render_tick_count?: number | undefined;
  render_tick_fraction?: number | undefined;
  player_tick_count?: number | undefined;
  player_tick_fraction?: number | undefined;
  cl_interp?: CSGOInterpolationInfoPB_CL | undefined;
  sv_interp0?: CSGOInterpolationInfoPB | undefined;
  sv_interp1?: CSGOInterpolationInfoPB | undefined;
  player_interp?: CSGOInterpolationInfoPB | undefined;
  frame_number?: number | undefined;
  target_ent_index?: number | undefined;
  shoot_position?: CMsgVector | undefined;
  target_head_pos_check?: CMsgVector | undefined;
  target_abs_pos_check?: CMsgVector | undefined;
  target_abs_ang_check?: CMsgQAngle | undefined;
}

export interface CSGOUserCmdPB {
  base?: CBaseUserCmdPB | undefined;
  input_history: CSGOInputHistoryEntryPB[];
  attack1_start_history_index?: number | undefined;
  attack2_start_history_index?: number | undefined;
  left_hand_desired?: boolean | undefined;
  is_predicting_body_shot_fx?: boolean | undefined;
  is_predicting_head_shot_fx?: boolean | undefined;
  is_predicting_kill_ragdolls?: boolean | undefined;
}

function createBaseCSGOInterpolationInfoPB(): CSGOInterpolationInfoPB {
  return { src_tick: undefined, dst_tick: undefined, frac: undefined };
}

export const CSGOInterpolationInfoPB: MessageFns<CSGOInterpolationInfoPB> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CSGOInterpolationInfoPB {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCSGOInterpolationInfoPB();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.src_tick = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.dst_tick = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.frac = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCSGOInterpolationInfoPB_CL(): CSGOInterpolationInfoPB_CL {
  return { frac: undefined };
}

export const CSGOInterpolationInfoPB_CL: MessageFns<CSGOInterpolationInfoPB_CL> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CSGOInterpolationInfoPB_CL {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCSGOInterpolationInfoPB_CL();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.frac = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCSGOInputHistoryEntryPB(): CSGOInputHistoryEntryPB {
  return {
    view_angles: undefined,
    render_tick_count: undefined,
    render_tick_fraction: undefined,
    player_tick_count: undefined,
    player_tick_fraction: undefined,
    cl_interp: undefined,
    sv_interp0: undefined,
    sv_interp1: undefined,
    player_interp: undefined,
    frame_number: undefined,
    target_ent_index: undefined,
    shoot_position: undefined,
    target_head_pos_check: undefined,
    target_abs_pos_check: undefined,
    target_abs_ang_check: undefined,
  };
}

export const CSGOInputHistoryEntryPB: MessageFns<CSGOInputHistoryEntryPB> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CSGOInputHistoryEntryPB {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCSGOInputHistoryEntryPB();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.view_angles = CMsgQAngle.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.render_tick_count = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.render_tick_fraction = reader.float();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.player_tick_count = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 61) {
            break;
          }

          message.player_tick_fraction = reader.float();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.cl_interp = CSGOInterpolationInfoPB_CL.decode(reader, reader.uint32());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.sv_interp0 = CSGOInterpolationInfoPB.decode(reader, reader.uint32());
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.sv_interp1 = CSGOInterpolationInfoPB.decode(reader, reader.uint32());
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.player_interp = CSGOInterpolationInfoPB.decode(reader, reader.uint32());
          continue;
        }
        case 64: {
          if (tag !== 512) {
            break;
          }

          message.frame_number = reader.int32();
          continue;
        }
        case 65: {
          if (tag !== 520) {
            break;
          }

          message.target_ent_index = reader.int32();
          continue;
        }
        case 66: {
          if (tag !== 530) {
            break;
          }

          message.shoot_position = CMsgVector.decode(reader, reader.uint32());
          continue;
        }
        case 67: {
          if (tag !== 538) {
            break;
          }

          message.target_head_pos_check = CMsgVector.decode(reader, reader.uint32());
          continue;
        }
        case 68: {
          if (tag !== 546) {
            break;
          }

          message.target_abs_pos_check = CMsgVector.decode(reader, reader.uint32());
          continue;
        }
        case 69: {
          if (tag !== 554) {
            break;
          }

          message.target_abs_ang_check = CMsgQAngle.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCSGOUserCmdPB(): CSGOUserCmdPB {
  return {
    base: undefined,
    input_history: [],
    attack1_start_history_index: undefined,
    attack2_start_history_index: undefined,
    left_hand_desired: undefined,
    is_predicting_body_shot_fx: undefined,
    is_predicting_head_shot_fx: undefined,
    is_predicting_kill_ragdolls: undefined,
  };
}

export const CSGOUserCmdPB: MessageFns<CSGOUserCmdPB> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CSGOUserCmdPB {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCSGOUserCmdPB();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.base = CBaseUserCmdPB.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.input_history.push(CSGOInputHistoryEntryPB.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.attack1_start_history_index = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.attack2_start_history_index = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.left_hand_desired = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.is_predicting_body_shot_fx = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.is_predicting_head_shot_fx = reader.bool();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.is_predicting_kill_ragdolls = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface MessageFns<T> {
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
