// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: demo.proto

/* eslint-disable */
import { BinaryReader } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export const EDemoCommands = {
  DEM_Error: -1,
  DEM_Stop: 0,
  DEM_FileHeader: 1,
  DEM_FileInfo: 2,
  DEM_SyncTick: 3,
  DEM_SendTables: 4,
  DEM_ClassInfo: 5,
  DEM_StringTables: 6,
  DEM_Packet: 7,
  DEM_SignonPacket: 8,
  DEM_ConsoleCmd: 9,
  DEM_CustomData: 10,
  DEM_CustomDataCallbacks: 11,
  DEM_UserCmd: 12,
  DEM_FullPacket: 13,
  DEM_SaveGame: 14,
  DEM_SpawnGroups: 15,
  DEM_AnimationData: 16,
  DEM_AnimationHeader: 17,
  DEM_Recovery: 18,
  DEM_Max: 19,
  DEM_IsCompressed: 64,
} as const;

export type EDemoCommands = typeof EDemoCommands[keyof typeof EDemoCommands];

export namespace EDemoCommands {
  export type DEM_Error = typeof EDemoCommands.DEM_Error;
  export type DEM_Stop = typeof EDemoCommands.DEM_Stop;
  export type DEM_FileHeader = typeof EDemoCommands.DEM_FileHeader;
  export type DEM_FileInfo = typeof EDemoCommands.DEM_FileInfo;
  export type DEM_SyncTick = typeof EDemoCommands.DEM_SyncTick;
  export type DEM_SendTables = typeof EDemoCommands.DEM_SendTables;
  export type DEM_ClassInfo = typeof EDemoCommands.DEM_ClassInfo;
  export type DEM_StringTables = typeof EDemoCommands.DEM_StringTables;
  export type DEM_Packet = typeof EDemoCommands.DEM_Packet;
  export type DEM_SignonPacket = typeof EDemoCommands.DEM_SignonPacket;
  export type DEM_ConsoleCmd = typeof EDemoCommands.DEM_ConsoleCmd;
  export type DEM_CustomData = typeof EDemoCommands.DEM_CustomData;
  export type DEM_CustomDataCallbacks = typeof EDemoCommands.DEM_CustomDataCallbacks;
  export type DEM_UserCmd = typeof EDemoCommands.DEM_UserCmd;
  export type DEM_FullPacket = typeof EDemoCommands.DEM_FullPacket;
  export type DEM_SaveGame = typeof EDemoCommands.DEM_SaveGame;
  export type DEM_SpawnGroups = typeof EDemoCommands.DEM_SpawnGroups;
  export type DEM_AnimationData = typeof EDemoCommands.DEM_AnimationData;
  export type DEM_AnimationHeader = typeof EDemoCommands.DEM_AnimationHeader;
  export type DEM_Recovery = typeof EDemoCommands.DEM_Recovery;
  export type DEM_Max = typeof EDemoCommands.DEM_Max;
  export type DEM_IsCompressed = typeof EDemoCommands.DEM_IsCompressed;
}

export interface CDemoFileHeader {
  demo_file_stamp?: string | undefined;
  patch_version?: number | undefined;
  server_name?: string | undefined;
  client_name?: string | undefined;
  map_name?: string | undefined;
  game_directory?: string | undefined;
  fullpackets_version?: number | undefined;
  allow_clientside_entities?: boolean | undefined;
  allow_clientside_particles?: boolean | undefined;
  addons?: string | undefined;
  demo_version_name?: string | undefined;
  demo_version_guid?: string | undefined;
  build_num?: number | undefined;
  game?: string | undefined;
  server_start_tick?: number | undefined;
}

export interface CGameInfo {
  dota?: CGameInfo_CDotaGameInfo | undefined;
  cs?: CGameInfo_CCSGameInfo | undefined;
}

export interface CGameInfo_CDotaGameInfo {
  match_id?: string | undefined;
  game_mode?: number | undefined;
  game_winner?: number | undefined;
  player_info: CGameInfo_CDotaGameInfo_CPlayerInfo[];
  leagueid?: number | undefined;
  picks_bans: CGameInfo_CDotaGameInfo_CHeroSelectEvent[];
  radiant_team_id?: number | undefined;
  dire_team_id?: number | undefined;
  radiant_team_tag?: string | undefined;
  dire_team_tag?: string | undefined;
  end_time?: number | undefined;
}

export interface CGameInfo_CDotaGameInfo_CPlayerInfo {
  hero_name?: string | undefined;
  player_name?: string | undefined;
  is_fake_client?: boolean | undefined;
  steamid?: string | undefined;
  game_team?: number | undefined;
}

export interface CGameInfo_CDotaGameInfo_CHeroSelectEvent {
  is_pick?: boolean | undefined;
  team?: number | undefined;
  hero_id?: number | undefined;
}

export interface CGameInfo_CCSGameInfo {
  round_start_ticks: number[];
}

export interface CDemoFileInfo {
  playback_time?: number | undefined;
  playback_ticks?: number | undefined;
  playback_frames?: number | undefined;
  game_info?: CGameInfo | undefined;
}

export interface CDemoPacket {
  data?: Uint8Array | undefined;
}

export interface CDemoFullPacket {
  string_table?: CDemoStringTables | undefined;
  packet?: CDemoPacket | undefined;
}

export interface CDemoSaveGame {
  data?: Uint8Array | undefined;
  steam_id?: string | undefined;
  signature?: string | undefined;
  version?: number | undefined;
}

export interface CDemoSyncTick {
}

export interface CDemoConsoleCmd {
  cmdstring?: string | undefined;
}

export interface CDemoSendTables {
  data?: Uint8Array | undefined;
}

export interface CDemoClassInfo {
  classes: CDemoClassInfo_class_t[];
}

export interface CDemoClassInfo_class_t {
  class_id?: number | undefined;
  network_name?: string | undefined;
  table_name?: string | undefined;
}

export interface CDemoCustomData {
  callback_index?: number | undefined;
  data?: Uint8Array | undefined;
}

export interface CDemoCustomDataCallbacks {
  save_id: string[];
}

export interface CDemoAnimationHeader {
  entity_id?: number | undefined;
  tick?: number | undefined;
  data?: Uint8Array | undefined;
}

export interface CDemoAnimationData {
  entity_id?: number | undefined;
  start_tick?: number | undefined;
  end_tick?: number | undefined;
  data?: Uint8Array | undefined;
  data_checksum?: string | undefined;
}

export interface CDemoStringTables {
  tables: CDemoStringTables_table_t[];
}

export interface CDemoStringTables_items_t {
  str?: string | undefined;
  data?: Uint8Array | undefined;
}

export interface CDemoStringTables_table_t {
  table_name?: string | undefined;
  items: CDemoStringTables_items_t[];
  items_clientside: CDemoStringTables_items_t[];
  table_flags?: number | undefined;
}

export interface CDemoStop {
}

export interface CDemoUserCmd {
  cmd_number?: number | undefined;
  data?: Uint8Array | undefined;
}

export interface CDemoSpawnGroups {
  msgs: Uint8Array[];
}

export interface CDemoSpawnGroupsHLTVBroadcast {
  data?: Uint8Array | undefined;
}

export interface CDemoRecovery {
  initial_spawn_group?: CDemoRecovery_DemoInitialSpawnGroupEntry | undefined;
  spawn_group_message?: Uint8Array | undefined;
}

export interface CDemoRecovery_DemoInitialSpawnGroupEntry {
  spawngrouphandle?: number | undefined;
  was_created?: boolean | undefined;
}

function createBaseCDemoFileHeader(): CDemoFileHeader {
  return {
    demo_file_stamp: undefined,
    patch_version: undefined,
    server_name: undefined,
    client_name: undefined,
    map_name: undefined,
    game_directory: undefined,
    fullpackets_version: undefined,
    allow_clientside_entities: undefined,
    allow_clientside_particles: undefined,
    addons: undefined,
    demo_version_name: undefined,
    demo_version_guid: undefined,
    build_num: undefined,
    game: undefined,
    server_start_tick: undefined,
  };
}

export const CDemoFileHeader: MessageFns<CDemoFileHeader> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CDemoFileHeader {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCDemoFileHeader();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.demo_file_stamp = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.patch_version = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.server_name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.client_name = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.map_name = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.game_directory = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.fullpackets_version = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.allow_clientside_entities = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.allow_clientside_particles = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.addons = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.demo_version_name = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.demo_version_guid = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.build_num = reader.int32();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.game = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.server_start_tick = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCGameInfo(): CGameInfo {
  return { dota: undefined, cs: undefined };
}

export const CGameInfo: MessageFns<CGameInfo> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CGameInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCGameInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.dota = CGameInfo_CDotaGameInfo.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.cs = CGameInfo_CCSGameInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCGameInfo_CDotaGameInfo(): CGameInfo_CDotaGameInfo {
  return {
    match_id: undefined,
    game_mode: undefined,
    game_winner: undefined,
    player_info: [],
    leagueid: undefined,
    picks_bans: [],
    radiant_team_id: undefined,
    dire_team_id: undefined,
    radiant_team_tag: undefined,
    dire_team_tag: undefined,
    end_time: undefined,
  };
}

export const CGameInfo_CDotaGameInfo: MessageFns<CGameInfo_CDotaGameInfo> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CGameInfo_CDotaGameInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCGameInfo_CDotaGameInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.match_id = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.game_mode = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.game_winner = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.player_info.push(CGameInfo_CDotaGameInfo_CPlayerInfo.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.leagueid = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.picks_bans.push(CGameInfo_CDotaGameInfo_CHeroSelectEvent.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.radiant_team_id = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.dire_team_id = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.radiant_team_tag = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.dire_team_tag = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.end_time = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCGameInfo_CDotaGameInfo_CPlayerInfo(): CGameInfo_CDotaGameInfo_CPlayerInfo {
  return {
    hero_name: undefined,
    player_name: undefined,
    is_fake_client: undefined,
    steamid: undefined,
    game_team: undefined,
  };
}

export const CGameInfo_CDotaGameInfo_CPlayerInfo: MessageFns<CGameInfo_CDotaGameInfo_CPlayerInfo> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CGameInfo_CDotaGameInfo_CPlayerInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCGameInfo_CDotaGameInfo_CPlayerInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.hero_name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.player_name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.is_fake_client = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.steamid = reader.uint64().toString();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.game_team = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCGameInfo_CDotaGameInfo_CHeroSelectEvent(): CGameInfo_CDotaGameInfo_CHeroSelectEvent {
  return { is_pick: undefined, team: undefined, hero_id: undefined };
}

export const CGameInfo_CDotaGameInfo_CHeroSelectEvent: MessageFns<CGameInfo_CDotaGameInfo_CHeroSelectEvent> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CGameInfo_CDotaGameInfo_CHeroSelectEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCGameInfo_CDotaGameInfo_CHeroSelectEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.is_pick = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.team = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.hero_id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCGameInfo_CCSGameInfo(): CGameInfo_CCSGameInfo {
  return { round_start_ticks: [] };
}

export const CGameInfo_CCSGameInfo: MessageFns<CGameInfo_CCSGameInfo> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CGameInfo_CCSGameInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCGameInfo_CCSGameInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.round_start_ticks.push(reader.int32());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.round_start_ticks.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCDemoFileInfo(): CDemoFileInfo {
  return { playback_time: undefined, playback_ticks: undefined, playback_frames: undefined, game_info: undefined };
}

export const CDemoFileInfo: MessageFns<CDemoFileInfo> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CDemoFileInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCDemoFileInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.playback_time = reader.float();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.playback_ticks = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.playback_frames = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.game_info = CGameInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCDemoPacket(): CDemoPacket {
  return { data: undefined };
}

export const CDemoPacket: MessageFns<CDemoPacket> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CDemoPacket {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCDemoPacket();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCDemoFullPacket(): CDemoFullPacket {
  return { string_table: undefined, packet: undefined };
}

export const CDemoFullPacket: MessageFns<CDemoFullPacket> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CDemoFullPacket {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCDemoFullPacket();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.string_table = CDemoStringTables.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.packet = CDemoPacket.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCDemoSaveGame(): CDemoSaveGame {
  return { data: undefined, steam_id: undefined, signature: undefined, version: undefined };
}

export const CDemoSaveGame: MessageFns<CDemoSaveGame> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CDemoSaveGame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCDemoSaveGame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.steam_id = reader.fixed64().toString();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.signature = reader.fixed64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.version = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCDemoSyncTick(): CDemoSyncTick {
  return {};
}

export const CDemoSyncTick: MessageFns<CDemoSyncTick> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CDemoSyncTick {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCDemoSyncTick();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCDemoConsoleCmd(): CDemoConsoleCmd {
  return { cmdstring: undefined };
}

export const CDemoConsoleCmd: MessageFns<CDemoConsoleCmd> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CDemoConsoleCmd {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCDemoConsoleCmd();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmdstring = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCDemoSendTables(): CDemoSendTables {
  return { data: undefined };
}

export const CDemoSendTables: MessageFns<CDemoSendTables> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CDemoSendTables {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCDemoSendTables();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCDemoClassInfo(): CDemoClassInfo {
  return { classes: [] };
}

export const CDemoClassInfo: MessageFns<CDemoClassInfo> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CDemoClassInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCDemoClassInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.classes.push(CDemoClassInfo_class_t.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCDemoClassInfo_class_t(): CDemoClassInfo_class_t {
  return { class_id: undefined, network_name: undefined, table_name: undefined };
}

export const CDemoClassInfo_class_t: MessageFns<CDemoClassInfo_class_t> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CDemoClassInfo_class_t {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCDemoClassInfo_class_t();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.class_id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.network_name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.table_name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCDemoCustomData(): CDemoCustomData {
  return { callback_index: undefined, data: undefined };
}

export const CDemoCustomData: MessageFns<CDemoCustomData> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CDemoCustomData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCDemoCustomData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.callback_index = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCDemoCustomDataCallbacks(): CDemoCustomDataCallbacks {
  return { save_id: [] };
}

export const CDemoCustomDataCallbacks: MessageFns<CDemoCustomDataCallbacks> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CDemoCustomDataCallbacks {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCDemoCustomDataCallbacks();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.save_id.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCDemoAnimationHeader(): CDemoAnimationHeader {
  return { entity_id: undefined, tick: undefined, data: undefined };
}

export const CDemoAnimationHeader: MessageFns<CDemoAnimationHeader> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CDemoAnimationHeader {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCDemoAnimationHeader();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.entity_id = reader.sint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.tick = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCDemoAnimationData(): CDemoAnimationData {
  return {
    entity_id: undefined,
    start_tick: undefined,
    end_tick: undefined,
    data: undefined,
    data_checksum: undefined,
  };
}

export const CDemoAnimationData: MessageFns<CDemoAnimationData> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CDemoAnimationData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCDemoAnimationData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.entity_id = reader.sint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.start_tick = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.end_tick = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.data_checksum = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCDemoStringTables(): CDemoStringTables {
  return { tables: [] };
}

export const CDemoStringTables: MessageFns<CDemoStringTables> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CDemoStringTables {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCDemoStringTables();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tables.push(CDemoStringTables_table_t.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCDemoStringTables_items_t(): CDemoStringTables_items_t {
  return { str: undefined, data: undefined };
}

export const CDemoStringTables_items_t: MessageFns<CDemoStringTables_items_t> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CDemoStringTables_items_t {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCDemoStringTables_items_t();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.str = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCDemoStringTables_table_t(): CDemoStringTables_table_t {
  return { table_name: undefined, items: [], items_clientside: [], table_flags: undefined };
}

export const CDemoStringTables_table_t: MessageFns<CDemoStringTables_table_t> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CDemoStringTables_table_t {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCDemoStringTables_table_t();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.table_name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.items.push(CDemoStringTables_items_t.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.items_clientside.push(CDemoStringTables_items_t.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.table_flags = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCDemoStop(): CDemoStop {
  return {};
}

export const CDemoStop: MessageFns<CDemoStop> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CDemoStop {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCDemoStop();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCDemoUserCmd(): CDemoUserCmd {
  return { cmd_number: undefined, data: undefined };
}

export const CDemoUserCmd: MessageFns<CDemoUserCmd> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CDemoUserCmd {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCDemoUserCmd();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.cmd_number = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCDemoSpawnGroups(): CDemoSpawnGroups {
  return { msgs: [] };
}

export const CDemoSpawnGroups: MessageFns<CDemoSpawnGroups> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CDemoSpawnGroups {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCDemoSpawnGroups();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.msgs.push(reader.bytes());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCDemoSpawnGroupsHLTVBroadcast(): CDemoSpawnGroupsHLTVBroadcast {
  return { data: undefined };
}

export const CDemoSpawnGroupsHLTVBroadcast: MessageFns<CDemoSpawnGroupsHLTVBroadcast> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CDemoSpawnGroupsHLTVBroadcast {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCDemoSpawnGroupsHLTVBroadcast();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCDemoRecovery(): CDemoRecovery {
  return { initial_spawn_group: undefined, spawn_group_message: undefined };
}

export const CDemoRecovery: MessageFns<CDemoRecovery> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CDemoRecovery {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCDemoRecovery();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.initial_spawn_group = CDemoRecovery_DemoInitialSpawnGroupEntry.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.spawn_group_message = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCDemoRecovery_DemoInitialSpawnGroupEntry(): CDemoRecovery_DemoInitialSpawnGroupEntry {
  return { spawngrouphandle: undefined, was_created: undefined };
}

export const CDemoRecovery_DemoInitialSpawnGroupEntry: MessageFns<CDemoRecovery_DemoInitialSpawnGroupEntry> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CDemoRecovery_DemoInitialSpawnGroupEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCDemoRecovery_DemoInitialSpawnGroupEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.spawngrouphandle = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.was_created = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface MessageFns<T> {
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
