// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: econ_gcmessages.proto

/* eslint-disable */
import { BinaryReader } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export const EGCItemMsg = {
  k_EMsgGCBase: 1000,
  k_EMsgGCSetItemPosition: 1001,
  k_EMsgGCCraft: 1002,
  k_EMsgGCCraftResponse: 1003,
  k_EMsgGCDelete: 1004,
  k_EMsgGCVerifyCacheSubscription: 1005,
  k_EMsgGCNameItem: 1006,
  k_EMsgGCUnlockCrate_DEPRECATED: 1007,
  k_EMsgGCUnlockCrateResponse: 1008,
  k_EMsgGCPaintItem: 1009,
  k_EMsgGCPaintItemResponse: 1010,
  k_EMsgGCGoldenWrenchBroadcast: 1011,
  k_EMsgGCMOTDRequest: 1012,
  k_EMsgGCMOTDRequestResponse: 1013,
  k_EMsgGCAddItemToSocket_DEPRECATED: 1014,
  k_EMsgGCAddItemToSocketResponse_DEPRECATED: 1015,
  k_EMsgGCAddSocketToBaseItem_DEPRECATED: 1016,
  k_EMsgGCAddSocketToItem_DEPRECATED: 1017,
  k_EMsgGCAddSocketToItemResponse_DEPRECATED: 1018,
  k_EMsgGCNameBaseItem: 1019,
  k_EMsgGCNameBaseItemResponse: 1020,
  k_EMsgGCRemoveSocketItem_DEPRECATED: 1021,
  k_EMsgGCRemoveSocketItemResponse_DEPRECATED: 1022,
  k_EMsgGCCustomizeItemTexture: 1023,
  k_EMsgGCCustomizeItemTextureResponse: 1024,
  k_EMsgGCUseItemRequest: 1025,
  k_EMsgGCUseItemResponse: 1026,
  k_EMsgGCGiftedItems_DEPRECATED: 1027,
  k_EMsgGCRemoveItemName: 1030,
  k_EMsgGCRemoveItemPaint: 1031,
  k_EMsgGCGiftWrapItem: 1032,
  k_EMsgGCGiftWrapItemResponse: 1033,
  k_EMsgGCDeliverGift: 1034,
  k_EMsgGCDeliverGiftResponseGiver: 1035,
  k_EMsgGCDeliverGiftResponseReceiver: 1036,
  k_EMsgGCUnwrapGiftRequest: 1037,
  k_EMsgGCUnwrapGiftResponse: 1038,
  k_EMsgGCSetItemStyle: 1039,
  k_EMsgGCUsedClaimCodeItem: 1040,
  k_EMsgGCSortItems: 1041,
  k_EMsgGC_RevolvingLootList_DEPRECATED: 1042,
  k_EMsgGCLookupAccount: 1043,
  k_EMsgGCLookupAccountResponse: 1044,
  k_EMsgGCLookupAccountName: 1045,
  k_EMsgGCLookupAccountNameResponse: 1046,
  k_EMsgGCUpdateItemSchema: 1049,
  k_EMsgGCRemoveCustomTexture: 1051,
  k_EMsgGCRemoveCustomTextureResponse: 1052,
  k_EMsgGCRemoveMakersMark: 1053,
  k_EMsgGCRemoveMakersMarkResponse: 1054,
  k_EMsgGCRemoveUniqueCraftIndex: 1055,
  k_EMsgGCRemoveUniqueCraftIndexResponse: 1056,
  k_EMsgGCSaxxyBroadcast: 1057,
  k_EMsgGCBackpackSortFinished: 1058,
  k_EMsgGCCollectItem: 1061,
  k_EMsgGCItemAcknowledged__DEPRECATED: 1062,
  k_EMsgGC_ReportAbuse: 1065,
  k_EMsgGC_ReportAbuseResponse: 1066,
  k_EMsgGCNameItemNotification: 1068,
  k_EMsgGCApplyConsumableEffects: 1069,
  k_EMsgGCConsumableExhausted: 1070,
  k_EMsgGCShowItemsPickedUp: 1071,
  k_EMsgGCClientDisplayNotification: 1072,
  k_EMsgGCApplyStrangePart: 1073,
  k_EMsgGC_IncrementKillCountAttribute: 1074,
  k_EMsgGC_IncrementKillCountResponse: 1075,
  k_EMsgGCApplyPennantUpgrade: 1076,
  k_EMsgGCSetItemPositions: 1077,
  k_EMsgGCApplyEggEssence: 1078,
  k_EMsgGCNameEggEssenceResponse: 1079,
  k_EMsgGCPaintKitItem: 1080,
  k_EMsgGCPaintKitBaseItem: 1081,
  k_EMsgGCPaintKitItemResponse: 1082,
  k_EMsgGCGiftedItems: 1083,
  k_EMsgGCUnlockItemStyle: 1084,
  k_EMsgGCUnlockItemStyleResponse: 1085,
  k_EMsgGCApplySticker: 1086,
  k_EMsgGCItemAcknowledged: 1087,
  k_EMsgGCStatTrakSwap: 1088,
  k_EMsgGCUserTrackTimePlayedConsecutively: 1089,
  k_EMsgGCItemCustomizationNotification: 1090,
  k_EMsgGCModifyItemAttribute: 1091,
  k_EMsgGCCasketItemAdd: 1092,
  k_EMsgGCCasketItemExtract: 1093,
  k_EMsgGCCasketItemLoadContents: 1094,
  k_EMsgGCServerBrowser_FavoriteServer: 1601,
  k_EMsgGCServerBrowser_BlacklistServer: 1602,
  k_EMsgGCServerRentalsBase: 1700,
  k_EMsgGCItemPreviewCheckStatus: 1701,
  k_EMsgGCItemPreviewStatusResponse: 1702,
  k_EMsgGCItemPreviewRequest: 1703,
  k_EMsgGCItemPreviewRequestResponse: 1704,
  k_EMsgGCItemPreviewExpire: 1705,
  k_EMsgGCItemPreviewExpireNotification: 1706,
  k_EMsgGCItemPreviewItemBoughtNotification: 1707,
  k_EMsgGCDev_NewItemRequest: 2001,
  k_EMsgGCDev_NewItemRequestResponse: 2002,
  k_EMsgGCDev_PaintKitDropItem: 2003,
  k_EMsgGCDev_SchemaReservationRequest: 2004,
  k_EMsgGCStoreGetUserData: 2500,
  k_EMsgGCStoreGetUserDataResponse: 2501,
  k_EMsgGCStorePurchaseInit_DEPRECATED: 2502,
  k_EMsgGCStorePurchaseInitResponse_DEPRECATED: 2503,
  k_EMsgGCStorePurchaseFinalize: 2504,
  k_EMsgGCStorePurchaseFinalizeResponse: 2505,
  k_EMsgGCStorePurchaseCancel: 2506,
  k_EMsgGCStorePurchaseCancelResponse: 2507,
  k_EMsgGCStorePurchaseQueryTxn: 2508,
  k_EMsgGCStorePurchaseQueryTxnResponse: 2509,
  k_EMsgGCStorePurchaseInit: 2510,
  k_EMsgGCStorePurchaseInitResponse: 2511,
  k_EMsgGCBannedWordListRequest: 2512,
  k_EMsgGCBannedWordListResponse: 2513,
  k_EMsgGCToGCBannedWordListBroadcast: 2514,
  k_EMsgGCToGCBannedWordListUpdated: 2515,
  k_EMsgGCToGCDirtySDOCache: 2516,
  k_EMsgGCToGCDirtyMultipleSDOCache: 2517,
  k_EMsgGCToGCUpdateSQLKeyValue: 2518,
  k_EMsgGCToGCIsTrustedServer: 2519,
  k_EMsgGCToGCIsTrustedServerResponse: 2520,
  k_EMsgGCToGCBroadcastConsoleCommand: 2521,
  k_EMsgGCServerVersionUpdated: 2522,
  k_EMsgGCToGCWebAPIAccountChanged: 2524,
  k_EMsgGCRequestAnnouncements: 2525,
  k_EMsgGCRequestAnnouncementsResponse: 2526,
  k_EMsgGCRequestPassportItemGrant: 2527,
  k_EMsgGCClientVersionUpdated: 2528,
  k_EMsgGCRecurringSubscriptionStatus: 2530,
  k_EMsgGCAdjustEquipSlotsManual: 2531,
  k_EMsgGCAdjustEquipSlotsShuffle: 2532,
  k_EMsgGCOpenCrate: 2534,
  k_EMsgGCAcknowledgeRentalExpiration: 2535,
  k_EMsgGCVolatileItemLoadContents: 2536,
  UNRECOGNIZED: -1,
} as const;

export type EGCItemMsg = typeof EGCItemMsg[keyof typeof EGCItemMsg];

export namespace EGCItemMsg {
  export type k_EMsgGCBase = typeof EGCItemMsg.k_EMsgGCBase;
  export type k_EMsgGCSetItemPosition = typeof EGCItemMsg.k_EMsgGCSetItemPosition;
  export type k_EMsgGCCraft = typeof EGCItemMsg.k_EMsgGCCraft;
  export type k_EMsgGCCraftResponse = typeof EGCItemMsg.k_EMsgGCCraftResponse;
  export type k_EMsgGCDelete = typeof EGCItemMsg.k_EMsgGCDelete;
  export type k_EMsgGCVerifyCacheSubscription = typeof EGCItemMsg.k_EMsgGCVerifyCacheSubscription;
  export type k_EMsgGCNameItem = typeof EGCItemMsg.k_EMsgGCNameItem;
  export type k_EMsgGCUnlockCrate_DEPRECATED = typeof EGCItemMsg.k_EMsgGCUnlockCrate_DEPRECATED;
  export type k_EMsgGCUnlockCrateResponse = typeof EGCItemMsg.k_EMsgGCUnlockCrateResponse;
  export type k_EMsgGCPaintItem = typeof EGCItemMsg.k_EMsgGCPaintItem;
  export type k_EMsgGCPaintItemResponse = typeof EGCItemMsg.k_EMsgGCPaintItemResponse;
  export type k_EMsgGCGoldenWrenchBroadcast = typeof EGCItemMsg.k_EMsgGCGoldenWrenchBroadcast;
  export type k_EMsgGCMOTDRequest = typeof EGCItemMsg.k_EMsgGCMOTDRequest;
  export type k_EMsgGCMOTDRequestResponse = typeof EGCItemMsg.k_EMsgGCMOTDRequestResponse;
  export type k_EMsgGCAddItemToSocket_DEPRECATED = typeof EGCItemMsg.k_EMsgGCAddItemToSocket_DEPRECATED;
  export type k_EMsgGCAddItemToSocketResponse_DEPRECATED = typeof EGCItemMsg.k_EMsgGCAddItemToSocketResponse_DEPRECATED;
  export type k_EMsgGCAddSocketToBaseItem_DEPRECATED = typeof EGCItemMsg.k_EMsgGCAddSocketToBaseItem_DEPRECATED;
  export type k_EMsgGCAddSocketToItem_DEPRECATED = typeof EGCItemMsg.k_EMsgGCAddSocketToItem_DEPRECATED;
  export type k_EMsgGCAddSocketToItemResponse_DEPRECATED = typeof EGCItemMsg.k_EMsgGCAddSocketToItemResponse_DEPRECATED;
  export type k_EMsgGCNameBaseItem = typeof EGCItemMsg.k_EMsgGCNameBaseItem;
  export type k_EMsgGCNameBaseItemResponse = typeof EGCItemMsg.k_EMsgGCNameBaseItemResponse;
  export type k_EMsgGCRemoveSocketItem_DEPRECATED = typeof EGCItemMsg.k_EMsgGCRemoveSocketItem_DEPRECATED;
  export type k_EMsgGCRemoveSocketItemResponse_DEPRECATED =
    typeof EGCItemMsg.k_EMsgGCRemoveSocketItemResponse_DEPRECATED;
  export type k_EMsgGCCustomizeItemTexture = typeof EGCItemMsg.k_EMsgGCCustomizeItemTexture;
  export type k_EMsgGCCustomizeItemTextureResponse = typeof EGCItemMsg.k_EMsgGCCustomizeItemTextureResponse;
  export type k_EMsgGCUseItemRequest = typeof EGCItemMsg.k_EMsgGCUseItemRequest;
  export type k_EMsgGCUseItemResponse = typeof EGCItemMsg.k_EMsgGCUseItemResponse;
  export type k_EMsgGCGiftedItems_DEPRECATED = typeof EGCItemMsg.k_EMsgGCGiftedItems_DEPRECATED;
  export type k_EMsgGCRemoveItemName = typeof EGCItemMsg.k_EMsgGCRemoveItemName;
  export type k_EMsgGCRemoveItemPaint = typeof EGCItemMsg.k_EMsgGCRemoveItemPaint;
  export type k_EMsgGCGiftWrapItem = typeof EGCItemMsg.k_EMsgGCGiftWrapItem;
  export type k_EMsgGCGiftWrapItemResponse = typeof EGCItemMsg.k_EMsgGCGiftWrapItemResponse;
  export type k_EMsgGCDeliverGift = typeof EGCItemMsg.k_EMsgGCDeliverGift;
  export type k_EMsgGCDeliverGiftResponseGiver = typeof EGCItemMsg.k_EMsgGCDeliverGiftResponseGiver;
  export type k_EMsgGCDeliverGiftResponseReceiver = typeof EGCItemMsg.k_EMsgGCDeliverGiftResponseReceiver;
  export type k_EMsgGCUnwrapGiftRequest = typeof EGCItemMsg.k_EMsgGCUnwrapGiftRequest;
  export type k_EMsgGCUnwrapGiftResponse = typeof EGCItemMsg.k_EMsgGCUnwrapGiftResponse;
  export type k_EMsgGCSetItemStyle = typeof EGCItemMsg.k_EMsgGCSetItemStyle;
  export type k_EMsgGCUsedClaimCodeItem = typeof EGCItemMsg.k_EMsgGCUsedClaimCodeItem;
  export type k_EMsgGCSortItems = typeof EGCItemMsg.k_EMsgGCSortItems;
  export type k_EMsgGC_RevolvingLootList_DEPRECATED = typeof EGCItemMsg.k_EMsgGC_RevolvingLootList_DEPRECATED;
  export type k_EMsgGCLookupAccount = typeof EGCItemMsg.k_EMsgGCLookupAccount;
  export type k_EMsgGCLookupAccountResponse = typeof EGCItemMsg.k_EMsgGCLookupAccountResponse;
  export type k_EMsgGCLookupAccountName = typeof EGCItemMsg.k_EMsgGCLookupAccountName;
  export type k_EMsgGCLookupAccountNameResponse = typeof EGCItemMsg.k_EMsgGCLookupAccountNameResponse;
  export type k_EMsgGCUpdateItemSchema = typeof EGCItemMsg.k_EMsgGCUpdateItemSchema;
  export type k_EMsgGCRemoveCustomTexture = typeof EGCItemMsg.k_EMsgGCRemoveCustomTexture;
  export type k_EMsgGCRemoveCustomTextureResponse = typeof EGCItemMsg.k_EMsgGCRemoveCustomTextureResponse;
  export type k_EMsgGCRemoveMakersMark = typeof EGCItemMsg.k_EMsgGCRemoveMakersMark;
  export type k_EMsgGCRemoveMakersMarkResponse = typeof EGCItemMsg.k_EMsgGCRemoveMakersMarkResponse;
  export type k_EMsgGCRemoveUniqueCraftIndex = typeof EGCItemMsg.k_EMsgGCRemoveUniqueCraftIndex;
  export type k_EMsgGCRemoveUniqueCraftIndexResponse = typeof EGCItemMsg.k_EMsgGCRemoveUniqueCraftIndexResponse;
  export type k_EMsgGCSaxxyBroadcast = typeof EGCItemMsg.k_EMsgGCSaxxyBroadcast;
  export type k_EMsgGCBackpackSortFinished = typeof EGCItemMsg.k_EMsgGCBackpackSortFinished;
  export type k_EMsgGCCollectItem = typeof EGCItemMsg.k_EMsgGCCollectItem;
  export type k_EMsgGCItemAcknowledged__DEPRECATED = typeof EGCItemMsg.k_EMsgGCItemAcknowledged__DEPRECATED;
  export type k_EMsgGC_ReportAbuse = typeof EGCItemMsg.k_EMsgGC_ReportAbuse;
  export type k_EMsgGC_ReportAbuseResponse = typeof EGCItemMsg.k_EMsgGC_ReportAbuseResponse;
  export type k_EMsgGCNameItemNotification = typeof EGCItemMsg.k_EMsgGCNameItemNotification;
  export type k_EMsgGCApplyConsumableEffects = typeof EGCItemMsg.k_EMsgGCApplyConsumableEffects;
  export type k_EMsgGCConsumableExhausted = typeof EGCItemMsg.k_EMsgGCConsumableExhausted;
  export type k_EMsgGCShowItemsPickedUp = typeof EGCItemMsg.k_EMsgGCShowItemsPickedUp;
  export type k_EMsgGCClientDisplayNotification = typeof EGCItemMsg.k_EMsgGCClientDisplayNotification;
  export type k_EMsgGCApplyStrangePart = typeof EGCItemMsg.k_EMsgGCApplyStrangePart;
  export type k_EMsgGC_IncrementKillCountAttribute = typeof EGCItemMsg.k_EMsgGC_IncrementKillCountAttribute;
  export type k_EMsgGC_IncrementKillCountResponse = typeof EGCItemMsg.k_EMsgGC_IncrementKillCountResponse;
  export type k_EMsgGCApplyPennantUpgrade = typeof EGCItemMsg.k_EMsgGCApplyPennantUpgrade;
  export type k_EMsgGCSetItemPositions = typeof EGCItemMsg.k_EMsgGCSetItemPositions;
  export type k_EMsgGCApplyEggEssence = typeof EGCItemMsg.k_EMsgGCApplyEggEssence;
  export type k_EMsgGCNameEggEssenceResponse = typeof EGCItemMsg.k_EMsgGCNameEggEssenceResponse;
  export type k_EMsgGCPaintKitItem = typeof EGCItemMsg.k_EMsgGCPaintKitItem;
  export type k_EMsgGCPaintKitBaseItem = typeof EGCItemMsg.k_EMsgGCPaintKitBaseItem;
  export type k_EMsgGCPaintKitItemResponse = typeof EGCItemMsg.k_EMsgGCPaintKitItemResponse;
  export type k_EMsgGCGiftedItems = typeof EGCItemMsg.k_EMsgGCGiftedItems;
  export type k_EMsgGCUnlockItemStyle = typeof EGCItemMsg.k_EMsgGCUnlockItemStyle;
  export type k_EMsgGCUnlockItemStyleResponse = typeof EGCItemMsg.k_EMsgGCUnlockItemStyleResponse;
  export type k_EMsgGCApplySticker = typeof EGCItemMsg.k_EMsgGCApplySticker;
  export type k_EMsgGCItemAcknowledged = typeof EGCItemMsg.k_EMsgGCItemAcknowledged;
  export type k_EMsgGCStatTrakSwap = typeof EGCItemMsg.k_EMsgGCStatTrakSwap;
  export type k_EMsgGCUserTrackTimePlayedConsecutively = typeof EGCItemMsg.k_EMsgGCUserTrackTimePlayedConsecutively;
  export type k_EMsgGCItemCustomizationNotification = typeof EGCItemMsg.k_EMsgGCItemCustomizationNotification;
  export type k_EMsgGCModifyItemAttribute = typeof EGCItemMsg.k_EMsgGCModifyItemAttribute;
  export type k_EMsgGCCasketItemAdd = typeof EGCItemMsg.k_EMsgGCCasketItemAdd;
  export type k_EMsgGCCasketItemExtract = typeof EGCItemMsg.k_EMsgGCCasketItemExtract;
  export type k_EMsgGCCasketItemLoadContents = typeof EGCItemMsg.k_EMsgGCCasketItemLoadContents;
  export type k_EMsgGCServerBrowser_FavoriteServer = typeof EGCItemMsg.k_EMsgGCServerBrowser_FavoriteServer;
  export type k_EMsgGCServerBrowser_BlacklistServer = typeof EGCItemMsg.k_EMsgGCServerBrowser_BlacklistServer;
  export type k_EMsgGCServerRentalsBase = typeof EGCItemMsg.k_EMsgGCServerRentalsBase;
  export type k_EMsgGCItemPreviewCheckStatus = typeof EGCItemMsg.k_EMsgGCItemPreviewCheckStatus;
  export type k_EMsgGCItemPreviewStatusResponse = typeof EGCItemMsg.k_EMsgGCItemPreviewStatusResponse;
  export type k_EMsgGCItemPreviewRequest = typeof EGCItemMsg.k_EMsgGCItemPreviewRequest;
  export type k_EMsgGCItemPreviewRequestResponse = typeof EGCItemMsg.k_EMsgGCItemPreviewRequestResponse;
  export type k_EMsgGCItemPreviewExpire = typeof EGCItemMsg.k_EMsgGCItemPreviewExpire;
  export type k_EMsgGCItemPreviewExpireNotification = typeof EGCItemMsg.k_EMsgGCItemPreviewExpireNotification;
  export type k_EMsgGCItemPreviewItemBoughtNotification = typeof EGCItemMsg.k_EMsgGCItemPreviewItemBoughtNotification;
  export type k_EMsgGCDev_NewItemRequest = typeof EGCItemMsg.k_EMsgGCDev_NewItemRequest;
  export type k_EMsgGCDev_NewItemRequestResponse = typeof EGCItemMsg.k_EMsgGCDev_NewItemRequestResponse;
  export type k_EMsgGCDev_PaintKitDropItem = typeof EGCItemMsg.k_EMsgGCDev_PaintKitDropItem;
  export type k_EMsgGCDev_SchemaReservationRequest = typeof EGCItemMsg.k_EMsgGCDev_SchemaReservationRequest;
  export type k_EMsgGCStoreGetUserData = typeof EGCItemMsg.k_EMsgGCStoreGetUserData;
  export type k_EMsgGCStoreGetUserDataResponse = typeof EGCItemMsg.k_EMsgGCStoreGetUserDataResponse;
  export type k_EMsgGCStorePurchaseInit_DEPRECATED = typeof EGCItemMsg.k_EMsgGCStorePurchaseInit_DEPRECATED;
  export type k_EMsgGCStorePurchaseInitResponse_DEPRECATED =
    typeof EGCItemMsg.k_EMsgGCStorePurchaseInitResponse_DEPRECATED;
  export type k_EMsgGCStorePurchaseFinalize = typeof EGCItemMsg.k_EMsgGCStorePurchaseFinalize;
  export type k_EMsgGCStorePurchaseFinalizeResponse = typeof EGCItemMsg.k_EMsgGCStorePurchaseFinalizeResponse;
  export type k_EMsgGCStorePurchaseCancel = typeof EGCItemMsg.k_EMsgGCStorePurchaseCancel;
  export type k_EMsgGCStorePurchaseCancelResponse = typeof EGCItemMsg.k_EMsgGCStorePurchaseCancelResponse;
  export type k_EMsgGCStorePurchaseQueryTxn = typeof EGCItemMsg.k_EMsgGCStorePurchaseQueryTxn;
  export type k_EMsgGCStorePurchaseQueryTxnResponse = typeof EGCItemMsg.k_EMsgGCStorePurchaseQueryTxnResponse;
  export type k_EMsgGCStorePurchaseInit = typeof EGCItemMsg.k_EMsgGCStorePurchaseInit;
  export type k_EMsgGCStorePurchaseInitResponse = typeof EGCItemMsg.k_EMsgGCStorePurchaseInitResponse;
  export type k_EMsgGCBannedWordListRequest = typeof EGCItemMsg.k_EMsgGCBannedWordListRequest;
  export type k_EMsgGCBannedWordListResponse = typeof EGCItemMsg.k_EMsgGCBannedWordListResponse;
  export type k_EMsgGCToGCBannedWordListBroadcast = typeof EGCItemMsg.k_EMsgGCToGCBannedWordListBroadcast;
  export type k_EMsgGCToGCBannedWordListUpdated = typeof EGCItemMsg.k_EMsgGCToGCBannedWordListUpdated;
  export type k_EMsgGCToGCDirtySDOCache = typeof EGCItemMsg.k_EMsgGCToGCDirtySDOCache;
  export type k_EMsgGCToGCDirtyMultipleSDOCache = typeof EGCItemMsg.k_EMsgGCToGCDirtyMultipleSDOCache;
  export type k_EMsgGCToGCUpdateSQLKeyValue = typeof EGCItemMsg.k_EMsgGCToGCUpdateSQLKeyValue;
  export type k_EMsgGCToGCIsTrustedServer = typeof EGCItemMsg.k_EMsgGCToGCIsTrustedServer;
  export type k_EMsgGCToGCIsTrustedServerResponse = typeof EGCItemMsg.k_EMsgGCToGCIsTrustedServerResponse;
  export type k_EMsgGCToGCBroadcastConsoleCommand = typeof EGCItemMsg.k_EMsgGCToGCBroadcastConsoleCommand;
  export type k_EMsgGCServerVersionUpdated = typeof EGCItemMsg.k_EMsgGCServerVersionUpdated;
  export type k_EMsgGCToGCWebAPIAccountChanged = typeof EGCItemMsg.k_EMsgGCToGCWebAPIAccountChanged;
  export type k_EMsgGCRequestAnnouncements = typeof EGCItemMsg.k_EMsgGCRequestAnnouncements;
  export type k_EMsgGCRequestAnnouncementsResponse = typeof EGCItemMsg.k_EMsgGCRequestAnnouncementsResponse;
  export type k_EMsgGCRequestPassportItemGrant = typeof EGCItemMsg.k_EMsgGCRequestPassportItemGrant;
  export type k_EMsgGCClientVersionUpdated = typeof EGCItemMsg.k_EMsgGCClientVersionUpdated;
  export type k_EMsgGCRecurringSubscriptionStatus = typeof EGCItemMsg.k_EMsgGCRecurringSubscriptionStatus;
  export type k_EMsgGCAdjustEquipSlotsManual = typeof EGCItemMsg.k_EMsgGCAdjustEquipSlotsManual;
  export type k_EMsgGCAdjustEquipSlotsShuffle = typeof EGCItemMsg.k_EMsgGCAdjustEquipSlotsShuffle;
  export type k_EMsgGCOpenCrate = typeof EGCItemMsg.k_EMsgGCOpenCrate;
  export type k_EMsgGCAcknowledgeRentalExpiration = typeof EGCItemMsg.k_EMsgGCAcknowledgeRentalExpiration;
  export type k_EMsgGCVolatileItemLoadContents = typeof EGCItemMsg.k_EMsgGCVolatileItemLoadContents;
  export type UNRECOGNIZED = typeof EGCItemMsg.UNRECOGNIZED;
}

export const EGCMsgResponse = {
  k_EGCMsgResponseOK: 0,
  k_EGCMsgResponseDenied: 1,
  k_EGCMsgResponseServerError: 2,
  k_EGCMsgResponseTimeout: 3,
  k_EGCMsgResponseInvalid: 4,
  k_EGCMsgResponseNoMatch: 5,
  k_EGCMsgResponseUnknownError: 6,
  k_EGCMsgResponseNotLoggedOn: 7,
  k_EGCMsgFailedToCreate: 8,
  k_EGCMsgLimitExceeded: 9,
  k_EGCMsgCommitUnfinalized: 10,
  UNRECOGNIZED: -1,
} as const;

export type EGCMsgResponse = typeof EGCMsgResponse[keyof typeof EGCMsgResponse];

export namespace EGCMsgResponse {
  export type k_EGCMsgResponseOK = typeof EGCMsgResponse.k_EGCMsgResponseOK;
  export type k_EGCMsgResponseDenied = typeof EGCMsgResponse.k_EGCMsgResponseDenied;
  export type k_EGCMsgResponseServerError = typeof EGCMsgResponse.k_EGCMsgResponseServerError;
  export type k_EGCMsgResponseTimeout = typeof EGCMsgResponse.k_EGCMsgResponseTimeout;
  export type k_EGCMsgResponseInvalid = typeof EGCMsgResponse.k_EGCMsgResponseInvalid;
  export type k_EGCMsgResponseNoMatch = typeof EGCMsgResponse.k_EGCMsgResponseNoMatch;
  export type k_EGCMsgResponseUnknownError = typeof EGCMsgResponse.k_EGCMsgResponseUnknownError;
  export type k_EGCMsgResponseNotLoggedOn = typeof EGCMsgResponse.k_EGCMsgResponseNotLoggedOn;
  export type k_EGCMsgFailedToCreate = typeof EGCMsgResponse.k_EGCMsgFailedToCreate;
  export type k_EGCMsgLimitExceeded = typeof EGCMsgResponse.k_EGCMsgLimitExceeded;
  export type k_EGCMsgCommitUnfinalized = typeof EGCMsgResponse.k_EGCMsgCommitUnfinalized;
  export type UNRECOGNIZED = typeof EGCMsgResponse.UNRECOGNIZED;
}

export const EUnlockStyle = {
  k_UnlockStyle_Succeeded: 0,
  k_UnlockStyle_Failed_PreReq: 1,
  k_UnlockStyle_Failed_CantAfford: 2,
  k_UnlockStyle_Failed_CantCommit: 3,
  k_UnlockStyle_Failed_CantLockCache: 4,
  k_UnlockStyle_Failed_CantAffordAttrib: 5,
  UNRECOGNIZED: -1,
} as const;

export type EUnlockStyle = typeof EUnlockStyle[keyof typeof EUnlockStyle];

export namespace EUnlockStyle {
  export type k_UnlockStyle_Succeeded = typeof EUnlockStyle.k_UnlockStyle_Succeeded;
  export type k_UnlockStyle_Failed_PreReq = typeof EUnlockStyle.k_UnlockStyle_Failed_PreReq;
  export type k_UnlockStyle_Failed_CantAfford = typeof EUnlockStyle.k_UnlockStyle_Failed_CantAfford;
  export type k_UnlockStyle_Failed_CantCommit = typeof EUnlockStyle.k_UnlockStyle_Failed_CantCommit;
  export type k_UnlockStyle_Failed_CantLockCache = typeof EUnlockStyle.k_UnlockStyle_Failed_CantLockCache;
  export type k_UnlockStyle_Failed_CantAffordAttrib = typeof EUnlockStyle.k_UnlockStyle_Failed_CantAffordAttrib;
  export type UNRECOGNIZED = typeof EUnlockStyle.UNRECOGNIZED;
}

export const EGCItemCustomizationNotification = {
  k_EGCItemCustomizationNotification_NameItem: 1006,
  k_EGCItemCustomizationNotification_UnlockCrate: 1007,
  k_EGCItemCustomizationNotification_XRayItemReveal: 1008,
  k_EGCItemCustomizationNotification_XRayItemClaim: 1009,
  k_EGCItemCustomizationNotification_CasketTooFull: 1011,
  k_EGCItemCustomizationNotification_CasketContents: 1012,
  k_EGCItemCustomizationNotification_CasketAdded: 1013,
  k_EGCItemCustomizationNotification_CasketRemoved: 1014,
  k_EGCItemCustomizationNotification_CasketInvFull: 1015,
  k_EGCItemCustomizationNotification_NameBaseItem: 1019,
  k_EGCItemCustomizationNotification_RemoveItemName: 1030,
  k_EGCItemCustomizationNotification_RemoveSticker: 1053,
  k_EGCItemCustomizationNotification_ExtractSticker: 1054,
  k_EGCItemCustomizationNotification_EncapsulateSticker: 1055,
  k_EGCItemCustomizationNotification_ApplySticker: 1086,
  k_EGCItemCustomizationNotification_StatTrakSwap: 1088,
  k_EGCItemCustomizationNotification_RemovePatch: 1089,
  k_EGCItemCustomizationNotification_ApplyPatch: 1090,
  k_EGCItemCustomizationNotification_ApplyKeychain: 1091,
  k_EGCItemCustomizationNotification_RemoveKeychain: 1092,
  k_EGCItemCustomizationNotification_ActivateFanToken: 9178,
  k_EGCItemCustomizationNotification_ActivateOperationCoin: 9179,
  k_EGCItemCustomizationNotification_GraffitiUnseal: 9185,
  k_EGCItemCustomizationNotification_GenerateSouvenir: 9204,
  k_EGCItemCustomizationNotification_ClientRedeemMissionReward: 9209,
  k_EGCItemCustomizationNotification_ClientRedeemFreeReward: 9219,
  k_EGCItemCustomizationNotification_XpShopUseTicket: 9221,
  k_EGCItemCustomizationNotification_XpShopAckTracks: 9222,
  UNRECOGNIZED: -1,
} as const;

export type EGCItemCustomizationNotification =
  typeof EGCItemCustomizationNotification[keyof typeof EGCItemCustomizationNotification];

export namespace EGCItemCustomizationNotification {
  export type k_EGCItemCustomizationNotification_NameItem =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_NameItem;
  export type k_EGCItemCustomizationNotification_UnlockCrate =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_UnlockCrate;
  export type k_EGCItemCustomizationNotification_XRayItemReveal =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_XRayItemReveal;
  export type k_EGCItemCustomizationNotification_XRayItemClaim =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_XRayItemClaim;
  export type k_EGCItemCustomizationNotification_CasketTooFull =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_CasketTooFull;
  export type k_EGCItemCustomizationNotification_CasketContents =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_CasketContents;
  export type k_EGCItemCustomizationNotification_CasketAdded =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_CasketAdded;
  export type k_EGCItemCustomizationNotification_CasketRemoved =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_CasketRemoved;
  export type k_EGCItemCustomizationNotification_CasketInvFull =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_CasketInvFull;
  export type k_EGCItemCustomizationNotification_NameBaseItem =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_NameBaseItem;
  export type k_EGCItemCustomizationNotification_RemoveItemName =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_RemoveItemName;
  export type k_EGCItemCustomizationNotification_RemoveSticker =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_RemoveSticker;
  export type k_EGCItemCustomizationNotification_ExtractSticker =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_ExtractSticker;
  export type k_EGCItemCustomizationNotification_EncapsulateSticker =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_EncapsulateSticker;
  export type k_EGCItemCustomizationNotification_ApplySticker =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_ApplySticker;
  export type k_EGCItemCustomizationNotification_StatTrakSwap =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_StatTrakSwap;
  export type k_EGCItemCustomizationNotification_RemovePatch =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_RemovePatch;
  export type k_EGCItemCustomizationNotification_ApplyPatch =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_ApplyPatch;
  export type k_EGCItemCustomizationNotification_ApplyKeychain =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_ApplyKeychain;
  export type k_EGCItemCustomizationNotification_RemoveKeychain =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_RemoveKeychain;
  export type k_EGCItemCustomizationNotification_ActivateFanToken =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_ActivateFanToken;
  export type k_EGCItemCustomizationNotification_ActivateOperationCoin =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_ActivateOperationCoin;
  export type k_EGCItemCustomizationNotification_GraffitiUnseal =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_GraffitiUnseal;
  export type k_EGCItemCustomizationNotification_GenerateSouvenir =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_GenerateSouvenir;
  export type k_EGCItemCustomizationNotification_ClientRedeemMissionReward =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_ClientRedeemMissionReward;
  export type k_EGCItemCustomizationNotification_ClientRedeemFreeReward =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_ClientRedeemFreeReward;
  export type k_EGCItemCustomizationNotification_XpShopUseTicket =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_XpShopUseTicket;
  export type k_EGCItemCustomizationNotification_XpShopAckTracks =
    typeof EGCItemCustomizationNotification.k_EGCItemCustomizationNotification_XpShopAckTracks;
  export type UNRECOGNIZED = typeof EGCItemCustomizationNotification.UNRECOGNIZED;
}

export interface CMsgGCGiftedItems {
  accountid?: number | undefined;
  giftdefindex?: number | undefined;
  max_gifts_possible?: number | undefined;
  num_eligible_recipients?: number | undefined;
  recipients_accountids: number[];
}

export interface CMsgGCDev_SchemaReservationRequest {
  schema_typename?: string | undefined;
  instance_name?: string | undefined;
  context?: string | undefined;
  id?: string | undefined;
}

export interface CMsgCasketItem {
  casket_item_id?: string | undefined;
  item_item_id?: string | undefined;
}

export interface CMsgGCUserTrackTimePlayedConsecutively {
  state?: number | undefined;
}

export interface CMsgGCItemCustomizationNotification {
  item_id: string[];
  request?: number | undefined;
  extra_data: string[];
}

function createBaseCMsgGCGiftedItems(): CMsgGCGiftedItems {
  return {
    accountid: undefined,
    giftdefindex: undefined,
    max_gifts_possible: undefined,
    num_eligible_recipients: undefined,
    recipients_accountids: [],
  };
}

export const CMsgGCGiftedItems: MessageFns<CMsgGCGiftedItems> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgGCGiftedItems {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgGCGiftedItems();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.accountid = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.giftdefindex = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.max_gifts_possible = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.num_eligible_recipients = reader.uint32();
          continue;
        }
        case 5: {
          if (tag === 40) {
            message.recipients_accountids.push(reader.uint32());

            continue;
          }

          if (tag === 42) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.recipients_accountids.push(reader.uint32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgGCDev_SchemaReservationRequest(): CMsgGCDev_SchemaReservationRequest {
  return { schema_typename: undefined, instance_name: undefined, context: undefined, id: undefined };
}

export const CMsgGCDev_SchemaReservationRequest: MessageFns<CMsgGCDev_SchemaReservationRequest> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgGCDev_SchemaReservationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgGCDev_SchemaReservationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.schema_typename = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.instance_name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.context = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.id = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgCasketItem(): CMsgCasketItem {
  return { casket_item_id: undefined, item_item_id: undefined };
}

export const CMsgCasketItem: MessageFns<CMsgCasketItem> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgCasketItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgCasketItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.casket_item_id = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.item_item_id = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgGCUserTrackTimePlayedConsecutively(): CMsgGCUserTrackTimePlayedConsecutively {
  return { state: undefined };
}

export const CMsgGCUserTrackTimePlayedConsecutively: MessageFns<CMsgGCUserTrackTimePlayedConsecutively> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgGCUserTrackTimePlayedConsecutively {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgGCUserTrackTimePlayedConsecutively();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.state = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgGCItemCustomizationNotification(): CMsgGCItemCustomizationNotification {
  return { item_id: [], request: undefined, extra_data: [] };
}

export const CMsgGCItemCustomizationNotification: MessageFns<CMsgGCItemCustomizationNotification> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgGCItemCustomizationNotification {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgGCItemCustomizationNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.item_id.push(reader.uint64().toString());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.item_id.push(reader.uint64().toString());
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.request = reader.uint32();
          continue;
        }
        case 3: {
          if (tag === 24) {
            message.extra_data.push(reader.uint64().toString());

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.extra_data.push(reader.uint64().toString());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface MessageFns<T> {
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
