// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: engine_gcmessages.proto

/* eslint-disable */
import { BinaryReader } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface CEngineGotvSyncPacket {
  match_id?: string | undefined;
  instance_id?: number | undefined;
  signupfragment?: number | undefined;
  currentfragment?: number | undefined;
  tickrate?: number | undefined;
  tick?: number | undefined;
  rtdelay?: number | undefined;
  rcvage?: number | undefined;
  keyframe_interval?: number | undefined;
  cdndelay?: number | undefined;
}

function createBaseCEngineGotvSyncPacket(): CEngineGotvSyncPacket {
  return {
    match_id: undefined,
    instance_id: undefined,
    signupfragment: undefined,
    currentfragment: undefined,
    tickrate: undefined,
    tick: undefined,
    rtdelay: undefined,
    rcvage: undefined,
    keyframe_interval: undefined,
    cdndelay: undefined,
  };
}

export const CEngineGotvSyncPacket: MessageFns<CEngineGotvSyncPacket> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CEngineGotvSyncPacket {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCEngineGotvSyncPacket();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.match_id = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.instance_id = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.signupfragment = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.currentfragment = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.tickrate = reader.float();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.tick = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 69) {
            break;
          }

          message.rtdelay = reader.float();
          continue;
        }
        case 9: {
          if (tag !== 77) {
            break;
          }

          message.rcvage = reader.float();
          continue;
        }
        case 10: {
          if (tag !== 85) {
            break;
          }

          message.keyframe_interval = reader.float();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.cdndelay = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface MessageFns<T> {
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
