// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: fatdemo.proto

/* eslint-disable */
import { BinaryReader } from "@bufbuild/protobuf/wire";
import { CMsgQAngle, CMsgVector } from "./networkbasetypes.js";

export const protobufPackage = "";

export const EHitGroup = {
  EHG_Generic: 0,
  EHG_Head: 1,
  EHG_Chest: 2,
  EHG_Stomach: 3,
  EHG_LeftArm: 4,
  EHG_RightArm: 5,
  EHG_LeftLeg: 6,
  EHG_RightLeg: 7,
  EHG_Gear: 8,
  EHG_Miss: 9,
  UNRECOGNIZED: -1,
} as const;

export type EHitGroup = typeof EHitGroup[keyof typeof EHitGroup];

export namespace EHitGroup {
  export type EHG_Generic = typeof EHitGroup.EHG_Generic;
  export type EHG_Head = typeof EHitGroup.EHG_Head;
  export type EHG_Chest = typeof EHitGroup.EHG_Chest;
  export type EHG_Stomach = typeof EHitGroup.EHG_Stomach;
  export type EHG_LeftArm = typeof EHitGroup.EHG_LeftArm;
  export type EHG_RightArm = typeof EHitGroup.EHG_RightArm;
  export type EHG_LeftLeg = typeof EHitGroup.EHG_LeftLeg;
  export type EHG_RightLeg = typeof EHitGroup.EHG_RightLeg;
  export type EHG_Gear = typeof EHitGroup.EHG_Gear;
  export type EHG_Miss = typeof EHitGroup.EHG_Miss;
  export type UNRECOGNIZED = typeof EHitGroup.UNRECOGNIZED;
}

export const ETeam = { ET_Unknown: 0, ET_Spectator: 1, ET_Terrorist: 2, ET_CT: 3, UNRECOGNIZED: -1 } as const;

export type ETeam = typeof ETeam[keyof typeof ETeam];

export namespace ETeam {
  export type ET_Unknown = typeof ETeam.ET_Unknown;
  export type ET_Spectator = typeof ETeam.ET_Spectator;
  export type ET_Terrorist = typeof ETeam.ET_Terrorist;
  export type ET_CT = typeof ETeam.ET_CT;
  export type UNRECOGNIZED = typeof ETeam.UNRECOGNIZED;
}

export const EWeaponType = {
  EWT_Knife: 0,
  EWT_Pistol: 1,
  EWT_SubMachineGun: 2,
  EWT_Rifle: 3,
  EWT_Shotgun: 4,
  EWT_SniperRifle: 5,
  EWT_MachineGun: 6,
  EWT_C4: 7,
  EWT_Grenade: 8,
  EWT_Equipment: 9,
  EWT_StackableItem: 10,
  EWT_Unknown: 11,
  UNRECOGNIZED: -1,
} as const;

export type EWeaponType = typeof EWeaponType[keyof typeof EWeaponType];

export namespace EWeaponType {
  export type EWT_Knife = typeof EWeaponType.EWT_Knife;
  export type EWT_Pistol = typeof EWeaponType.EWT_Pistol;
  export type EWT_SubMachineGun = typeof EWeaponType.EWT_SubMachineGun;
  export type EWT_Rifle = typeof EWeaponType.EWT_Rifle;
  export type EWT_Shotgun = typeof EWeaponType.EWT_Shotgun;
  export type EWT_SniperRifle = typeof EWeaponType.EWT_SniperRifle;
  export type EWT_MachineGun = typeof EWeaponType.EWT_MachineGun;
  export type EWT_C4 = typeof EWeaponType.EWT_C4;
  export type EWT_Grenade = typeof EWeaponType.EWT_Grenade;
  export type EWT_Equipment = typeof EWeaponType.EWT_Equipment;
  export type EWT_StackableItem = typeof EWeaponType.EWT_StackableItem;
  export type EWT_Unknown = typeof EWeaponType.EWT_Unknown;
  export type UNRECOGNIZED = typeof EWeaponType.UNRECOGNIZED;
}

export interface MLDict {
  key?: string | undefined;
  val_string?: string | undefined;
  val_int?: number | undefined;
  val_float?: number | undefined;
}

export interface MLEvent {
  event_name?: string | undefined;
  data: MLDict[];
}

export interface MLMatchState {
  game_mode?: string | undefined;
  phase?: string | undefined;
  round?: number | undefined;
  score_ct?: number | undefined;
  score_t?: number | undefined;
}

export interface MLRoundState {
  phase?: string | undefined;
  win_team?: ETeam | undefined;
  bomb_state?: string | undefined;
}

export interface MLWeaponState {
  index?: number | undefined;
  name?: string | undefined;
  type?: EWeaponType | undefined;
  ammo_clip?: number | undefined;
  ammo_clip_max?: number | undefined;
  ammo_reserve?: number | undefined;
  state?: string | undefined;
  recoil_index?: number | undefined;
}

export interface MLPlayerState {
  account_id?: number | undefined;
  player_slot?: number | undefined;
  entindex?: number | undefined;
  name?: string | undefined;
  clan?: string | undefined;
  team?: ETeam | undefined;
  abspos?: CMsgVector | undefined;
  eyeangle?: CMsgQAngle | undefined;
  eyeangle_fwd?: CMsgVector | undefined;
  health?: number | undefined;
  armor?: number | undefined;
  flashed?: number | undefined;
  smoked?: number | undefined;
  money?: number | undefined;
  round_kills?: number | undefined;
  round_killhs?: number | undefined;
  burning?: number | undefined;
  helmet?: boolean | undefined;
  defuse_kit?: boolean | undefined;
  weapons: MLWeaponState[];
}

export interface MLGameState {
  match?: MLMatchState | undefined;
  round?: MLRoundState | undefined;
  players: MLPlayerState[];
}

export interface MLDemoHeader {
  map_name?: string | undefined;
  tick_rate?: number | undefined;
  version?: number | undefined;
  steam_universe?: number | undefined;
}

export interface MLTick {
  tick_count?: number | undefined;
  state?: MLGameState | undefined;
  events: MLEvent[];
}

export interface VacNetShot {
  steamid_player?: string | undefined;
  round_number?: number | undefined;
  hit_type?: number | undefined;
  weapon_type?: number | undefined;
  distance_to_hurt_target?: number | undefined;
  delta_yaw_window: number[];
  delta_pitch_window: number[];
}

function createBaseMLDict(): MLDict {
  return { key: undefined, val_string: undefined, val_int: undefined, val_float: undefined };
}

export const MLDict: MessageFns<MLDict> = {
  decode(input: BinaryReader | Uint8Array, length?: number): MLDict {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLDict();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.val_string = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.val_int = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.val_float = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseMLEvent(): MLEvent {
  return { event_name: undefined, data: [] };
}

export const MLEvent: MessageFns<MLEvent> = {
  decode(input: BinaryReader | Uint8Array, length?: number): MLEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.event_name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data.push(MLDict.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseMLMatchState(): MLMatchState {
  return { game_mode: undefined, phase: undefined, round: undefined, score_ct: undefined, score_t: undefined };
}

export const MLMatchState: MessageFns<MLMatchState> = {
  decode(input: BinaryReader | Uint8Array, length?: number): MLMatchState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLMatchState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.game_mode = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.phase = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.round = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.score_ct = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.score_t = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseMLRoundState(): MLRoundState {
  return { phase: undefined, win_team: undefined, bomb_state: undefined };
}

export const MLRoundState: MessageFns<MLRoundState> = {
  decode(input: BinaryReader | Uint8Array, length?: number): MLRoundState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLRoundState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.phase = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.win_team = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.bomb_state = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseMLWeaponState(): MLWeaponState {
  return {
    index: undefined,
    name: undefined,
    type: undefined,
    ammo_clip: undefined,
    ammo_clip_max: undefined,
    ammo_reserve: undefined,
    state: undefined,
    recoil_index: undefined,
  };
}

export const MLWeaponState: MessageFns<MLWeaponState> = {
  decode(input: BinaryReader | Uint8Array, length?: number): MLWeaponState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLWeaponState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.index = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.ammo_clip = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.ammo_clip_max = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.ammo_reserve = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.state = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 69) {
            break;
          }

          message.recoil_index = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseMLPlayerState(): MLPlayerState {
  return {
    account_id: undefined,
    player_slot: undefined,
    entindex: undefined,
    name: undefined,
    clan: undefined,
    team: undefined,
    abspos: undefined,
    eyeangle: undefined,
    eyeangle_fwd: undefined,
    health: undefined,
    armor: undefined,
    flashed: undefined,
    smoked: undefined,
    money: undefined,
    round_kills: undefined,
    round_killhs: undefined,
    burning: undefined,
    helmet: undefined,
    defuse_kit: undefined,
    weapons: [],
  };
}

export const MLPlayerState: MessageFns<MLPlayerState> = {
  decode(input: BinaryReader | Uint8Array, length?: number): MLPlayerState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLPlayerState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.account_id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.player_slot = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.entindex = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.clan = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.team = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.abspos = CMsgVector.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.eyeangle = CMsgQAngle.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.eyeangle_fwd = CMsgVector.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.health = reader.int32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.armor = reader.int32();
          continue;
        }
        case 12: {
          if (tag !== 101) {
            break;
          }

          message.flashed = reader.float();
          continue;
        }
        case 13: {
          if (tag !== 109) {
            break;
          }

          message.smoked = reader.float();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.money = reader.int32();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.round_kills = reader.int32();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.round_killhs = reader.int32();
          continue;
        }
        case 17: {
          if (tag !== 141) {
            break;
          }

          message.burning = reader.float();
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.helmet = reader.bool();
          continue;
        }
        case 19: {
          if (tag !== 152) {
            break;
          }

          message.defuse_kit = reader.bool();
          continue;
        }
        case 20: {
          if (tag !== 162) {
            break;
          }

          message.weapons.push(MLWeaponState.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseMLGameState(): MLGameState {
  return { match: undefined, round: undefined, players: [] };
}

export const MLGameState: MessageFns<MLGameState> = {
  decode(input: BinaryReader | Uint8Array, length?: number): MLGameState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLGameState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.match = MLMatchState.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.round = MLRoundState.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.players.push(MLPlayerState.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseMLDemoHeader(): MLDemoHeader {
  return { map_name: undefined, tick_rate: undefined, version: undefined, steam_universe: undefined };
}

export const MLDemoHeader: MessageFns<MLDemoHeader> = {
  decode(input: BinaryReader | Uint8Array, length?: number): MLDemoHeader {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLDemoHeader();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.map_name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.tick_rate = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.version = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.steam_universe = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseMLTick(): MLTick {
  return { tick_count: undefined, state: undefined, events: [] };
}

export const MLTick: MessageFns<MLTick> = {
  decode(input: BinaryReader | Uint8Array, length?: number): MLTick {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLTick();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.tick_count = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.state = MLGameState.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.events.push(MLEvent.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseVacNetShot(): VacNetShot {
  return {
    steamid_player: undefined,
    round_number: undefined,
    hit_type: undefined,
    weapon_type: undefined,
    distance_to_hurt_target: undefined,
    delta_yaw_window: [],
    delta_pitch_window: [],
  };
}

export const VacNetShot: MessageFns<VacNetShot> = {
  decode(input: BinaryReader | Uint8Array, length?: number): VacNetShot {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVacNetShot();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.steamid_player = reader.fixed64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.round_number = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.hit_type = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.weapon_type = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.distance_to_hurt_target = reader.float();
          continue;
        }
        case 6: {
          if (tag === 53) {
            message.delta_yaw_window.push(reader.float());

            continue;
          }

          if (tag === 50) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.delta_yaw_window.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 7: {
          if (tag === 61) {
            message.delta_pitch_window.push(reader.float());

            continue;
          }

          if (tag === 58) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.delta_pitch_window.push(reader.float());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface MessageFns<T> {
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
