// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: steammessages_helprequest.steamworkssdk.proto

/* eslint-disable */
import { BinaryReader } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface CHelpRequestLogs_UploadUserApplicationLog_Request {
  appid?: number | undefined;
  log_type?: string | undefined;
  version_string?: string | undefined;
  log_contents?: string | undefined;
}

export interface CHelpRequestLogs_UploadUserApplicationLog_Response {
  id?: string | undefined;
}

function createBaseCHelpRequestLogs_UploadUserApplicationLog_Request(): CHelpRequestLogs_UploadUserApplicationLog_Request {
  return { appid: undefined, log_type: undefined, version_string: undefined, log_contents: undefined };
}

export const CHelpRequestLogs_UploadUserApplicationLog_Request: MessageFns<
  CHelpRequestLogs_UploadUserApplicationLog_Request
> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CHelpRequestLogs_UploadUserApplicationLog_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCHelpRequestLogs_UploadUserApplicationLog_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.appid = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.log_type = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.version_string = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.log_contents = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCHelpRequestLogs_UploadUserApplicationLog_Response(): CHelpRequestLogs_UploadUserApplicationLog_Response {
  return { id: undefined };
}

export const CHelpRequestLogs_UploadUserApplicationLog_Response: MessageFns<
  CHelpRequestLogs_UploadUserApplicationLog_Response
> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CHelpRequestLogs_UploadUserApplicationLog_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCHelpRequestLogs_UploadUserApplicationLog_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface MessageFns<T> {
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
