// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: steammessages_player.steamworkssdk.proto

/* eslint-disable */
import { BinaryReader } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export const ENotificationSetting = {
  k_ENotificationSettingNotifyUseDefault: 0,
  k_ENotificationSettingAlways: 1,
  k_ENotificationSettingNever: 2,
  UNRECOGNIZED: -1,
} as const;

export type ENotificationSetting = typeof ENotificationSetting[keyof typeof ENotificationSetting];

export namespace ENotificationSetting {
  export type k_ENotificationSettingNotifyUseDefault =
    typeof ENotificationSetting.k_ENotificationSettingNotifyUseDefault;
  export type k_ENotificationSettingAlways = typeof ENotificationSetting.k_ENotificationSettingAlways;
  export type k_ENotificationSettingNever = typeof ENotificationSetting.k_ENotificationSettingNever;
  export type UNRECOGNIZED = typeof ENotificationSetting.UNRECOGNIZED;
}

export interface CPlayer_GetMutualFriendsForIncomingInvites_Request {
}

export interface CPlayer_IncomingInviteMutualFriendList {
  steamid?: string | undefined;
  mutual_friend_account_ids: number[];
}

export interface CPlayer_GetMutualFriendsForIncomingInvites_Response {
  incoming_invite_mutual_friends_lists: CPlayer_IncomingInviteMutualFriendList[];
}

export interface CPlayer_GetFriendsGameplayInfo_Request {
  appid?: number | undefined;
}

export interface CPlayer_GetFriendsGameplayInfo_Response {
  your_info?: CPlayer_GetFriendsGameplayInfo_Response_OwnGameplayInfo | undefined;
  in_game: CPlayer_GetFriendsGameplayInfo_Response_FriendsGameplayInfo[];
  played_recently: CPlayer_GetFriendsGameplayInfo_Response_FriendsGameplayInfo[];
  played_ever: CPlayer_GetFriendsGameplayInfo_Response_FriendsGameplayInfo[];
  owns: CPlayer_GetFriendsGameplayInfo_Response_FriendsGameplayInfo[];
  in_wishlist: CPlayer_GetFriendsGameplayInfo_Response_FriendsGameplayInfo[];
}

export interface CPlayer_GetFriendsGameplayInfo_Response_FriendsGameplayInfo {
  steamid?: string | undefined;
  minutes_played?: number | undefined;
  minutes_played_forever?: number | undefined;
}

export interface CPlayer_GetFriendsGameplayInfo_Response_OwnGameplayInfo {
  steamid?: string | undefined;
  minutes_played?: number | undefined;
  minutes_played_forever?: number | undefined;
  in_wishlist?: boolean | undefined;
  owned?: boolean | undefined;
}

export interface CPlayer_GetGameBadgeLevels_Request {
  appid?: number | undefined;
}

export interface CPlayer_GetGameBadgeLevels_Response {
  player_level?: number | undefined;
  badges: CPlayer_GetGameBadgeLevels_Response_Badge[];
}

export interface CPlayer_GetGameBadgeLevels_Response_Badge {
  level?: number | undefined;
  series?: number | undefined;
  border_color?: number | undefined;
}

export interface CPlayer_GetLastPlayedTimes_Request {
  min_last_played?: number | undefined;
}

export interface CPlayer_GetLastPlayedTimes_Response {
  games: CPlayer_GetLastPlayedTimes_Response_Game[];
}

export interface CPlayer_GetLastPlayedTimes_Response_Game {
  appid?: number | undefined;
  last_playtime?: number | undefined;
  playtime_2weeks?: number | undefined;
  playtime_forever?: number | undefined;
  first_playtime?: number | undefined;
}

export interface CPlayer_AcceptSSA_Request {
}

export interface CPlayer_AcceptSSA_Response {
}

export interface CPlayer_GetNicknameList_Request {
}

export interface CPlayer_GetNicknameList_Response {
  nicknames: CPlayer_GetNicknameList_Response_PlayerNickname[];
}

export interface CPlayer_GetNicknameList_Response_PlayerNickname {
  accountid?: number | undefined;
  nickname?: string | undefined;
}

export interface CPlayer_GetPerFriendPreferences_Request {
}

export interface PerFriendPreferences {
  accountid?: number | undefined;
  nickname?: string | undefined;
  notifications_showingame?: ENotificationSetting | undefined;
  notifications_showonline?: ENotificationSetting | undefined;
  notifications_showmessages?: ENotificationSetting | undefined;
  sounds_showingame?: ENotificationSetting | undefined;
  sounds_showonline?: ENotificationSetting | undefined;
  sounds_showmessages?: ENotificationSetting | undefined;
  notifications_sendmobile?: ENotificationSetting | undefined;
}

export interface CPlayer_GetPerFriendPreferences_Response {
  preferences: PerFriendPreferences[];
}

export interface CPlayer_SetPerFriendPreferences_Request {
  preferences?: PerFriendPreferences | undefined;
}

export interface CPlayer_SetPerFriendPreferences_Response {
}

export interface CPlayer_AddFriend_Request {
  steamid?: string | undefined;
}

export interface CPlayer_AddFriend_Response {
  invite_sent?: boolean | undefined;
  friend_relationship?: number | undefined;
}

export interface CPlayer_RemoveFriend_Request {
  steamid?: string | undefined;
}

export interface CPlayer_RemoveFriend_Response {
  friend_relationship?: number | undefined;
}

export interface CPlayer_IgnoreFriend_Request {
  steamid?: string | undefined;
  unignore?: boolean | undefined;
}

export interface CPlayer_IgnoreFriend_Response {
  friend_relationship?: number | undefined;
}

export interface CPlayer_GetCommunityPreferences_Request {
}

export interface CPlayer_CommunityPreferences {
  hide_adult_content_violence?: boolean | undefined;
  hide_adult_content_sex?: boolean | undefined;
  parenthesize_nicknames?: boolean | undefined;
  timestamp_updated?: number | undefined;
}

export interface CPlayer_GetCommunityPreferences_Response {
  preferences?: CPlayer_CommunityPreferences | undefined;
}

export interface CPlayer_SetCommunityPreferences_Request {
  preferences?: CPlayer_CommunityPreferences | undefined;
}

export interface CPlayer_SetCommunityPreferences_Response {
}

export interface CPlayer_GetNewSteamAnnouncementState_Request {
  language?: number | undefined;
}

export interface CPlayer_GetNewSteamAnnouncementState_Response {
  state?: number | undefined;
  announcement_headline?: string | undefined;
  announcement_url?: string | undefined;
  time_posted?: number | undefined;
  announcement_gid?: string | undefined;
}

export interface CPlayer_UpdateSteamAnnouncementLastRead_Request {
  announcement_gid?: string | undefined;
  time_posted?: number | undefined;
}

export interface CPlayer_UpdateSteamAnnouncementLastRead_Response {
}

function createBaseCPlayer_GetMutualFriendsForIncomingInvites_Request(): CPlayer_GetMutualFriendsForIncomingInvites_Request {
  return {};
}

export const CPlayer_GetMutualFriendsForIncomingInvites_Request: MessageFns<
  CPlayer_GetMutualFriendsForIncomingInvites_Request
> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_GetMutualFriendsForIncomingInvites_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_GetMutualFriendsForIncomingInvites_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_IncomingInviteMutualFriendList(): CPlayer_IncomingInviteMutualFriendList {
  return { steamid: undefined, mutual_friend_account_ids: [] };
}

export const CPlayer_IncomingInviteMutualFriendList: MessageFns<CPlayer_IncomingInviteMutualFriendList> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_IncomingInviteMutualFriendList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_IncomingInviteMutualFriendList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.steamid = reader.fixed64().toString();
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.mutual_friend_account_ids.push(reader.uint32());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.mutual_friend_account_ids.push(reader.uint32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_GetMutualFriendsForIncomingInvites_Response(): CPlayer_GetMutualFriendsForIncomingInvites_Response {
  return { incoming_invite_mutual_friends_lists: [] };
}

export const CPlayer_GetMutualFriendsForIncomingInvites_Response: MessageFns<
  CPlayer_GetMutualFriendsForIncomingInvites_Response
> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_GetMutualFriendsForIncomingInvites_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_GetMutualFriendsForIncomingInvites_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.incoming_invite_mutual_friends_lists.push(
            CPlayer_IncomingInviteMutualFriendList.decode(reader, reader.uint32()),
          );
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_GetFriendsGameplayInfo_Request(): CPlayer_GetFriendsGameplayInfo_Request {
  return { appid: undefined };
}

export const CPlayer_GetFriendsGameplayInfo_Request: MessageFns<CPlayer_GetFriendsGameplayInfo_Request> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_GetFriendsGameplayInfo_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_GetFriendsGameplayInfo_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.appid = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_GetFriendsGameplayInfo_Response(): CPlayer_GetFriendsGameplayInfo_Response {
  return { your_info: undefined, in_game: [], played_recently: [], played_ever: [], owns: [], in_wishlist: [] };
}

export const CPlayer_GetFriendsGameplayInfo_Response: MessageFns<CPlayer_GetFriendsGameplayInfo_Response> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_GetFriendsGameplayInfo_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_GetFriendsGameplayInfo_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.your_info = CPlayer_GetFriendsGameplayInfo_Response_OwnGameplayInfo.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.in_game.push(
            CPlayer_GetFriendsGameplayInfo_Response_FriendsGameplayInfo.decode(reader, reader.uint32()),
          );
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.played_recently.push(
            CPlayer_GetFriendsGameplayInfo_Response_FriendsGameplayInfo.decode(reader, reader.uint32()),
          );
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.played_ever.push(
            CPlayer_GetFriendsGameplayInfo_Response_FriendsGameplayInfo.decode(reader, reader.uint32()),
          );
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.owns.push(
            CPlayer_GetFriendsGameplayInfo_Response_FriendsGameplayInfo.decode(reader, reader.uint32()),
          );
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.in_wishlist.push(
            CPlayer_GetFriendsGameplayInfo_Response_FriendsGameplayInfo.decode(reader, reader.uint32()),
          );
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_GetFriendsGameplayInfo_Response_FriendsGameplayInfo(): CPlayer_GetFriendsGameplayInfo_Response_FriendsGameplayInfo {
  return { steamid: undefined, minutes_played: undefined, minutes_played_forever: undefined };
}

export const CPlayer_GetFriendsGameplayInfo_Response_FriendsGameplayInfo: MessageFns<
  CPlayer_GetFriendsGameplayInfo_Response_FriendsGameplayInfo
> = {
  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): CPlayer_GetFriendsGameplayInfo_Response_FriendsGameplayInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_GetFriendsGameplayInfo_Response_FriendsGameplayInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.steamid = reader.fixed64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.minutes_played = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.minutes_played_forever = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_GetFriendsGameplayInfo_Response_OwnGameplayInfo(): CPlayer_GetFriendsGameplayInfo_Response_OwnGameplayInfo {
  return {
    steamid: undefined,
    minutes_played: undefined,
    minutes_played_forever: undefined,
    in_wishlist: undefined,
    owned: undefined,
  };
}

export const CPlayer_GetFriendsGameplayInfo_Response_OwnGameplayInfo: MessageFns<
  CPlayer_GetFriendsGameplayInfo_Response_OwnGameplayInfo
> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_GetFriendsGameplayInfo_Response_OwnGameplayInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_GetFriendsGameplayInfo_Response_OwnGameplayInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.steamid = reader.fixed64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.minutes_played = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.minutes_played_forever = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.in_wishlist = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.owned = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_GetGameBadgeLevels_Request(): CPlayer_GetGameBadgeLevels_Request {
  return { appid: undefined };
}

export const CPlayer_GetGameBadgeLevels_Request: MessageFns<CPlayer_GetGameBadgeLevels_Request> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_GetGameBadgeLevels_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_GetGameBadgeLevels_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.appid = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_GetGameBadgeLevels_Response(): CPlayer_GetGameBadgeLevels_Response {
  return { player_level: undefined, badges: [] };
}

export const CPlayer_GetGameBadgeLevels_Response: MessageFns<CPlayer_GetGameBadgeLevels_Response> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_GetGameBadgeLevels_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_GetGameBadgeLevels_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.player_level = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.badges.push(CPlayer_GetGameBadgeLevels_Response_Badge.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_GetGameBadgeLevels_Response_Badge(): CPlayer_GetGameBadgeLevels_Response_Badge {
  return { level: undefined, series: undefined, border_color: undefined };
}

export const CPlayer_GetGameBadgeLevels_Response_Badge: MessageFns<CPlayer_GetGameBadgeLevels_Response_Badge> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_GetGameBadgeLevels_Response_Badge {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_GetGameBadgeLevels_Response_Badge();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.level = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.series = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.border_color = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_GetLastPlayedTimes_Request(): CPlayer_GetLastPlayedTimes_Request {
  return { min_last_played: undefined };
}

export const CPlayer_GetLastPlayedTimes_Request: MessageFns<CPlayer_GetLastPlayedTimes_Request> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_GetLastPlayedTimes_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_GetLastPlayedTimes_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.min_last_played = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_GetLastPlayedTimes_Response(): CPlayer_GetLastPlayedTimes_Response {
  return { games: [] };
}

export const CPlayer_GetLastPlayedTimes_Response: MessageFns<CPlayer_GetLastPlayedTimes_Response> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_GetLastPlayedTimes_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_GetLastPlayedTimes_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.games.push(CPlayer_GetLastPlayedTimes_Response_Game.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_GetLastPlayedTimes_Response_Game(): CPlayer_GetLastPlayedTimes_Response_Game {
  return {
    appid: undefined,
    last_playtime: undefined,
    playtime_2weeks: undefined,
    playtime_forever: undefined,
    first_playtime: undefined,
  };
}

export const CPlayer_GetLastPlayedTimes_Response_Game: MessageFns<CPlayer_GetLastPlayedTimes_Response_Game> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_GetLastPlayedTimes_Response_Game {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_GetLastPlayedTimes_Response_Game();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.appid = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.last_playtime = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.playtime_2weeks = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.playtime_forever = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.first_playtime = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_AcceptSSA_Request(): CPlayer_AcceptSSA_Request {
  return {};
}

export const CPlayer_AcceptSSA_Request: MessageFns<CPlayer_AcceptSSA_Request> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_AcceptSSA_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_AcceptSSA_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_AcceptSSA_Response(): CPlayer_AcceptSSA_Response {
  return {};
}

export const CPlayer_AcceptSSA_Response: MessageFns<CPlayer_AcceptSSA_Response> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_AcceptSSA_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_AcceptSSA_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_GetNicknameList_Request(): CPlayer_GetNicknameList_Request {
  return {};
}

export const CPlayer_GetNicknameList_Request: MessageFns<CPlayer_GetNicknameList_Request> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_GetNicknameList_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_GetNicknameList_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_GetNicknameList_Response(): CPlayer_GetNicknameList_Response {
  return { nicknames: [] };
}

export const CPlayer_GetNicknameList_Response: MessageFns<CPlayer_GetNicknameList_Response> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_GetNicknameList_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_GetNicknameList_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nicknames.push(CPlayer_GetNicknameList_Response_PlayerNickname.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_GetNicknameList_Response_PlayerNickname(): CPlayer_GetNicknameList_Response_PlayerNickname {
  return { accountid: undefined, nickname: undefined };
}

export const CPlayer_GetNicknameList_Response_PlayerNickname: MessageFns<
  CPlayer_GetNicknameList_Response_PlayerNickname
> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_GetNicknameList_Response_PlayerNickname {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_GetNicknameList_Response_PlayerNickname();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.accountid = reader.fixed32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nickname = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_GetPerFriendPreferences_Request(): CPlayer_GetPerFriendPreferences_Request {
  return {};
}

export const CPlayer_GetPerFriendPreferences_Request: MessageFns<CPlayer_GetPerFriendPreferences_Request> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_GetPerFriendPreferences_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_GetPerFriendPreferences_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBasePerFriendPreferences(): PerFriendPreferences {
  return {
    accountid: undefined,
    nickname: undefined,
    notifications_showingame: undefined,
    notifications_showonline: undefined,
    notifications_showmessages: undefined,
    sounds_showingame: undefined,
    sounds_showonline: undefined,
    sounds_showmessages: undefined,
    notifications_sendmobile: undefined,
  };
}

export const PerFriendPreferences: MessageFns<PerFriendPreferences> = {
  decode(input: BinaryReader | Uint8Array, length?: number): PerFriendPreferences {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePerFriendPreferences();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.accountid = reader.fixed32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nickname = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.notifications_showingame = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.notifications_showonline = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.notifications_showmessages = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.sounds_showingame = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.sounds_showonline = reader.int32() as any;
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.sounds_showmessages = reader.int32() as any;
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.notifications_sendmobile = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_GetPerFriendPreferences_Response(): CPlayer_GetPerFriendPreferences_Response {
  return { preferences: [] };
}

export const CPlayer_GetPerFriendPreferences_Response: MessageFns<CPlayer_GetPerFriendPreferences_Response> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_GetPerFriendPreferences_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_GetPerFriendPreferences_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.preferences.push(PerFriendPreferences.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_SetPerFriendPreferences_Request(): CPlayer_SetPerFriendPreferences_Request {
  return { preferences: undefined };
}

export const CPlayer_SetPerFriendPreferences_Request: MessageFns<CPlayer_SetPerFriendPreferences_Request> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_SetPerFriendPreferences_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_SetPerFriendPreferences_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.preferences = PerFriendPreferences.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_SetPerFriendPreferences_Response(): CPlayer_SetPerFriendPreferences_Response {
  return {};
}

export const CPlayer_SetPerFriendPreferences_Response: MessageFns<CPlayer_SetPerFriendPreferences_Response> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_SetPerFriendPreferences_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_SetPerFriendPreferences_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_AddFriend_Request(): CPlayer_AddFriend_Request {
  return { steamid: undefined };
}

export const CPlayer_AddFriend_Request: MessageFns<CPlayer_AddFriend_Request> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_AddFriend_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_AddFriend_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.steamid = reader.fixed64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_AddFriend_Response(): CPlayer_AddFriend_Response {
  return { invite_sent: undefined, friend_relationship: undefined };
}

export const CPlayer_AddFriend_Response: MessageFns<CPlayer_AddFriend_Response> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_AddFriend_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_AddFriend_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.invite_sent = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.friend_relationship = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_RemoveFriend_Request(): CPlayer_RemoveFriend_Request {
  return { steamid: undefined };
}

export const CPlayer_RemoveFriend_Request: MessageFns<CPlayer_RemoveFriend_Request> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_RemoveFriend_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_RemoveFriend_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.steamid = reader.fixed64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_RemoveFriend_Response(): CPlayer_RemoveFriend_Response {
  return { friend_relationship: undefined };
}

export const CPlayer_RemoveFriend_Response: MessageFns<CPlayer_RemoveFriend_Response> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_RemoveFriend_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_RemoveFriend_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.friend_relationship = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_IgnoreFriend_Request(): CPlayer_IgnoreFriend_Request {
  return { steamid: undefined, unignore: undefined };
}

export const CPlayer_IgnoreFriend_Request: MessageFns<CPlayer_IgnoreFriend_Request> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_IgnoreFriend_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_IgnoreFriend_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.steamid = reader.fixed64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.unignore = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_IgnoreFriend_Response(): CPlayer_IgnoreFriend_Response {
  return { friend_relationship: undefined };
}

export const CPlayer_IgnoreFriend_Response: MessageFns<CPlayer_IgnoreFriend_Response> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_IgnoreFriend_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_IgnoreFriend_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.friend_relationship = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_GetCommunityPreferences_Request(): CPlayer_GetCommunityPreferences_Request {
  return {};
}

export const CPlayer_GetCommunityPreferences_Request: MessageFns<CPlayer_GetCommunityPreferences_Request> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_GetCommunityPreferences_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_GetCommunityPreferences_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_CommunityPreferences(): CPlayer_CommunityPreferences {
  return {
    hide_adult_content_violence: undefined,
    hide_adult_content_sex: undefined,
    parenthesize_nicknames: undefined,
    timestamp_updated: undefined,
  };
}

export const CPlayer_CommunityPreferences: MessageFns<CPlayer_CommunityPreferences> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_CommunityPreferences {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_CommunityPreferences();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.hide_adult_content_violence = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.hide_adult_content_sex = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.parenthesize_nicknames = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.timestamp_updated = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_GetCommunityPreferences_Response(): CPlayer_GetCommunityPreferences_Response {
  return { preferences: undefined };
}

export const CPlayer_GetCommunityPreferences_Response: MessageFns<CPlayer_GetCommunityPreferences_Response> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_GetCommunityPreferences_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_GetCommunityPreferences_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.preferences = CPlayer_CommunityPreferences.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_SetCommunityPreferences_Request(): CPlayer_SetCommunityPreferences_Request {
  return { preferences: undefined };
}

export const CPlayer_SetCommunityPreferences_Request: MessageFns<CPlayer_SetCommunityPreferences_Request> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_SetCommunityPreferences_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_SetCommunityPreferences_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.preferences = CPlayer_CommunityPreferences.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_SetCommunityPreferences_Response(): CPlayer_SetCommunityPreferences_Response {
  return {};
}

export const CPlayer_SetCommunityPreferences_Response: MessageFns<CPlayer_SetCommunityPreferences_Response> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_SetCommunityPreferences_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_SetCommunityPreferences_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_GetNewSteamAnnouncementState_Request(): CPlayer_GetNewSteamAnnouncementState_Request {
  return { language: undefined };
}

export const CPlayer_GetNewSteamAnnouncementState_Request: MessageFns<CPlayer_GetNewSteamAnnouncementState_Request> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_GetNewSteamAnnouncementState_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_GetNewSteamAnnouncementState_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.language = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_GetNewSteamAnnouncementState_Response(): CPlayer_GetNewSteamAnnouncementState_Response {
  return {
    state: undefined,
    announcement_headline: undefined,
    announcement_url: undefined,
    time_posted: undefined,
    announcement_gid: undefined,
  };
}

export const CPlayer_GetNewSteamAnnouncementState_Response: MessageFns<CPlayer_GetNewSteamAnnouncementState_Response> =
  {
    decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_GetNewSteamAnnouncementState_Response {
      const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCPlayer_GetNewSteamAnnouncementState_Response();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.state = reader.int32();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.announcement_headline = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.announcement_url = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.time_posted = reader.uint32();
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.announcement_gid = reader.uint64().toString();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    },
  };

function createBaseCPlayer_UpdateSteamAnnouncementLastRead_Request(): CPlayer_UpdateSteamAnnouncementLastRead_Request {
  return { announcement_gid: undefined, time_posted: undefined };
}

export const CPlayer_UpdateSteamAnnouncementLastRead_Request: MessageFns<
  CPlayer_UpdateSteamAnnouncementLastRead_Request
> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_UpdateSteamAnnouncementLastRead_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_UpdateSteamAnnouncementLastRead_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.announcement_gid = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.time_posted = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCPlayer_UpdateSteamAnnouncementLastRead_Response(): CPlayer_UpdateSteamAnnouncementLastRead_Response {
  return {};
}

export const CPlayer_UpdateSteamAnnouncementLastRead_Response: MessageFns<
  CPlayer_UpdateSteamAnnouncementLastRead_Response
> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CPlayer_UpdateSteamAnnouncementLastRead_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlayer_UpdateSteamAnnouncementLastRead_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface MessageFns<T> {
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
