// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: steammessages_oauth.steamworkssdk.proto

/* eslint-disable */
import { BinaryReader } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface COAuthToken_ImplicitGrantNoPrompt_Request {
  clientid?: string | undefined;
}

export interface COAuthToken_ImplicitGrantNoPrompt_Response {
  access_token?: string | undefined;
  redirect_uri?: string | undefined;
}

function createBaseCOAuthToken_ImplicitGrantNoPrompt_Request(): COAuthToken_ImplicitGrantNoPrompt_Request {
  return { clientid: undefined };
}

export const COAuthToken_ImplicitGrantNoPrompt_Request: MessageFns<COAuthToken_ImplicitGrantNoPrompt_Request> = {
  decode(input: BinaryReader | Uint8Array, length?: number): COAuthToken_ImplicitGrantNoPrompt_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCOAuthToken_ImplicitGrantNoPrompt_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clientid = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCOAuthToken_ImplicitGrantNoPrompt_Response(): COAuthToken_ImplicitGrantNoPrompt_Response {
  return { access_token: undefined, redirect_uri: undefined };
}

export const COAuthToken_ImplicitGrantNoPrompt_Response: MessageFns<COAuthToken_ImplicitGrantNoPrompt_Response> = {
  decode(input: BinaryReader | Uint8Array, length?: number): COAuthToken_ImplicitGrantNoPrompt_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCOAuthToken_ImplicitGrantNoPrompt_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.access_token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.redirect_uri = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface MessageFns<T> {
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
