// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: steammessages_steamlearn.steamworkssdk.proto

/* eslint-disable */
import { BinaryReader } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export const ESteamLearnDataType = {
  STEAMLEARN_DATATYPE_INVALID: 0,
  STEAMLEARN_DATATYPE_INT32: 1,
  STEAMLEARN_DATATYPE_FLOAT32: 2,
  STEAMLEARN_DATATYPE_BOOL: 3,
  STEAMLEARN_DATATYPE_STRING: 4,
  STEAMLEARN_DATATYPE_OBJECT: 5,
  UNRECOGNIZED: -1,
} as const;

export type ESteamLearnDataType = typeof ESteamLearnDataType[keyof typeof ESteamLearnDataType];

export namespace ESteamLearnDataType {
  export type STEAMLEARN_DATATYPE_INVALID = typeof ESteamLearnDataType.STEAMLEARN_DATATYPE_INVALID;
  export type STEAMLEARN_DATATYPE_INT32 = typeof ESteamLearnDataType.STEAMLEARN_DATATYPE_INT32;
  export type STEAMLEARN_DATATYPE_FLOAT32 = typeof ESteamLearnDataType.STEAMLEARN_DATATYPE_FLOAT32;
  export type STEAMLEARN_DATATYPE_BOOL = typeof ESteamLearnDataType.STEAMLEARN_DATATYPE_BOOL;
  export type STEAMLEARN_DATATYPE_STRING = typeof ESteamLearnDataType.STEAMLEARN_DATATYPE_STRING;
  export type STEAMLEARN_DATATYPE_OBJECT = typeof ESteamLearnDataType.STEAMLEARN_DATATYPE_OBJECT;
  export type UNRECOGNIZED = typeof ESteamLearnDataType.UNRECOGNIZED;
}

export const ESteammLearnRegisterDataSourceResult = {
  STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_ERROR: 0,
  STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_SUCCESS_CREATED: 1,
  STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_SUCCESS_FOUND: 2,
  STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_ERROR_GENERIC: 3,
  STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_ERROR_INVALID_NAME: 4,
  STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_ERROR_INVALID_VERSION: 5,
  STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_ERROR_DATA_CHANGED: 6,
  STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_ERROR_DATA_INVALID: 7,
  STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_ERROR_FORBIDDEN: 8,
  STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_ERROR_INVALID_TIMESTAMP: 9,
  STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_DISABLED: 10,
  UNRECOGNIZED: -1,
} as const;

export type ESteammLearnRegisterDataSourceResult =
  typeof ESteammLearnRegisterDataSourceResult[keyof typeof ESteammLearnRegisterDataSourceResult];

export namespace ESteammLearnRegisterDataSourceResult {
  export type STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_ERROR =
    typeof ESteammLearnRegisterDataSourceResult.STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_ERROR;
  export type STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_SUCCESS_CREATED =
    typeof ESteammLearnRegisterDataSourceResult.STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_SUCCESS_CREATED;
  export type STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_SUCCESS_FOUND =
    typeof ESteammLearnRegisterDataSourceResult.STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_SUCCESS_FOUND;
  export type STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_ERROR_GENERIC =
    typeof ESteammLearnRegisterDataSourceResult.STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_ERROR_GENERIC;
  export type STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_ERROR_INVALID_NAME =
    typeof ESteammLearnRegisterDataSourceResult.STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_ERROR_INVALID_NAME;
  export type STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_ERROR_INVALID_VERSION =
    typeof ESteammLearnRegisterDataSourceResult.STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_ERROR_INVALID_VERSION;
  export type STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_ERROR_DATA_CHANGED =
    typeof ESteammLearnRegisterDataSourceResult.STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_ERROR_DATA_CHANGED;
  export type STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_ERROR_DATA_INVALID =
    typeof ESteammLearnRegisterDataSourceResult.STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_ERROR_DATA_INVALID;
  export type STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_ERROR_FORBIDDEN =
    typeof ESteammLearnRegisterDataSourceResult.STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_ERROR_FORBIDDEN;
  export type STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_ERROR_INVALID_TIMESTAMP =
    typeof ESteammLearnRegisterDataSourceResult.STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_ERROR_INVALID_TIMESTAMP;
  export type STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_DISABLED =
    typeof ESteammLearnRegisterDataSourceResult.STEAMLEARN_REGISTER_DATA_SOURCE_RESULT_DISABLED;
  export type UNRECOGNIZED = typeof ESteammLearnRegisterDataSourceResult.UNRECOGNIZED;
}

export const ESteamLearnCacheDataResult = {
  STEAMLEARN_CACHE_DATA_ERROR: 0,
  STEAMLEARN_CACHE_DATA_SUCCESS: 1,
  STEAMLEARN_CACHE_DATA_ERROR_UNKNOWN_DATA_SOURCE: 2,
  STEAMLEARN_CACHE_DATA_ERROR_UNCACHED_DATA_SOURCE: 3,
  STEAMLEARN_CACHE_DATA_ERROR_INVALID_KEYS: 4,
  STEAMLEARN_CACHE_DATA_ERROR_FORBIDDEN: 5,
  STEAMLEARN_CACHE_DATA_ERROR_INVALID_TIMESTAMP: 6,
  STEAMLEARN_CACHE_DATA_DISABLED: 7,
  UNRECOGNIZED: -1,
} as const;

export type ESteamLearnCacheDataResult = typeof ESteamLearnCacheDataResult[keyof typeof ESteamLearnCacheDataResult];

export namespace ESteamLearnCacheDataResult {
  export type STEAMLEARN_CACHE_DATA_ERROR = typeof ESteamLearnCacheDataResult.STEAMLEARN_CACHE_DATA_ERROR;
  export type STEAMLEARN_CACHE_DATA_SUCCESS = typeof ESteamLearnCacheDataResult.STEAMLEARN_CACHE_DATA_SUCCESS;
  export type STEAMLEARN_CACHE_DATA_ERROR_UNKNOWN_DATA_SOURCE =
    typeof ESteamLearnCacheDataResult.STEAMLEARN_CACHE_DATA_ERROR_UNKNOWN_DATA_SOURCE;
  export type STEAMLEARN_CACHE_DATA_ERROR_UNCACHED_DATA_SOURCE =
    typeof ESteamLearnCacheDataResult.STEAMLEARN_CACHE_DATA_ERROR_UNCACHED_DATA_SOURCE;
  export type STEAMLEARN_CACHE_DATA_ERROR_INVALID_KEYS =
    typeof ESteamLearnCacheDataResult.STEAMLEARN_CACHE_DATA_ERROR_INVALID_KEYS;
  export type STEAMLEARN_CACHE_DATA_ERROR_FORBIDDEN =
    typeof ESteamLearnCacheDataResult.STEAMLEARN_CACHE_DATA_ERROR_FORBIDDEN;
  export type STEAMLEARN_CACHE_DATA_ERROR_INVALID_TIMESTAMP =
    typeof ESteamLearnCacheDataResult.STEAMLEARN_CACHE_DATA_ERROR_INVALID_TIMESTAMP;
  export type STEAMLEARN_CACHE_DATA_DISABLED = typeof ESteamLearnCacheDataResult.STEAMLEARN_CACHE_DATA_DISABLED;
  export type UNRECOGNIZED = typeof ESteamLearnCacheDataResult.UNRECOGNIZED;
}

export const ESteamLearnSnapshotProjectResult = {
  STEAMLEARN_SNAPSHOT_PROJECT_ERROR: 0,
  STEAMLEARN_SNAPSHOT_PROJECT_SUCCESS_STORED: 1,
  STEAMLEARN_SNAPSHOT_PROJECT_SUCCESS_QUEUED: 2,
  STEAMLEARN_SNAPSHOT_PROJECT_ERROR_INVALID_PROJECT_ID: 3,
  STEAMLEARN_SNAPSHOT_PROJECT_ERROR_UNKNOWN_DATA_SOURCE: 4,
  STEAMLEARN_SNAPSHOT_PROJECT_ERROR_INVALID_DATA_SOURCE_KEY: 5,
  STEAMLEARN_SNAPSHOT_PROJECT_ERROR_MISSING_CACHE_DURATION: 6,
  STEAMLEARN_SNAPSHOT_PROJECT_ERROR_NO_PUBLISHED_CONFIG: 7,
  STEAMLEARN_SNAPSHOT_PROJECT_ERROR_FORBIDDEN: 8,
  STEAMLEARN_SNAPSHOT_PROJECT_ERROR_INVALID_TIMESTAMP: 9,
  STEAMLEARN_SNAPSHOT_PROJECT_ERROR_INTERNAL_DATA_SOURCE_ERROR: 10,
  STEAMLEARN_SNAPSHOT_PROJECT_DISABLED: 11,
  STEAMLEARN_SNAPSHOT_PROJECT_ERROR_INVALID_PUBLISHED_VERSION: 12,
  UNRECOGNIZED: -1,
} as const;

export type ESteamLearnSnapshotProjectResult =
  typeof ESteamLearnSnapshotProjectResult[keyof typeof ESteamLearnSnapshotProjectResult];

export namespace ESteamLearnSnapshotProjectResult {
  export type STEAMLEARN_SNAPSHOT_PROJECT_ERROR =
    typeof ESteamLearnSnapshotProjectResult.STEAMLEARN_SNAPSHOT_PROJECT_ERROR;
  export type STEAMLEARN_SNAPSHOT_PROJECT_SUCCESS_STORED =
    typeof ESteamLearnSnapshotProjectResult.STEAMLEARN_SNAPSHOT_PROJECT_SUCCESS_STORED;
  export type STEAMLEARN_SNAPSHOT_PROJECT_SUCCESS_QUEUED =
    typeof ESteamLearnSnapshotProjectResult.STEAMLEARN_SNAPSHOT_PROJECT_SUCCESS_QUEUED;
  export type STEAMLEARN_SNAPSHOT_PROJECT_ERROR_INVALID_PROJECT_ID =
    typeof ESteamLearnSnapshotProjectResult.STEAMLEARN_SNAPSHOT_PROJECT_ERROR_INVALID_PROJECT_ID;
  export type STEAMLEARN_SNAPSHOT_PROJECT_ERROR_UNKNOWN_DATA_SOURCE =
    typeof ESteamLearnSnapshotProjectResult.STEAMLEARN_SNAPSHOT_PROJECT_ERROR_UNKNOWN_DATA_SOURCE;
  export type STEAMLEARN_SNAPSHOT_PROJECT_ERROR_INVALID_DATA_SOURCE_KEY =
    typeof ESteamLearnSnapshotProjectResult.STEAMLEARN_SNAPSHOT_PROJECT_ERROR_INVALID_DATA_SOURCE_KEY;
  export type STEAMLEARN_SNAPSHOT_PROJECT_ERROR_MISSING_CACHE_DURATION =
    typeof ESteamLearnSnapshotProjectResult.STEAMLEARN_SNAPSHOT_PROJECT_ERROR_MISSING_CACHE_DURATION;
  export type STEAMLEARN_SNAPSHOT_PROJECT_ERROR_NO_PUBLISHED_CONFIG =
    typeof ESteamLearnSnapshotProjectResult.STEAMLEARN_SNAPSHOT_PROJECT_ERROR_NO_PUBLISHED_CONFIG;
  export type STEAMLEARN_SNAPSHOT_PROJECT_ERROR_FORBIDDEN =
    typeof ESteamLearnSnapshotProjectResult.STEAMLEARN_SNAPSHOT_PROJECT_ERROR_FORBIDDEN;
  export type STEAMLEARN_SNAPSHOT_PROJECT_ERROR_INVALID_TIMESTAMP =
    typeof ESteamLearnSnapshotProjectResult.STEAMLEARN_SNAPSHOT_PROJECT_ERROR_INVALID_TIMESTAMP;
  export type STEAMLEARN_SNAPSHOT_PROJECT_ERROR_INTERNAL_DATA_SOURCE_ERROR =
    typeof ESteamLearnSnapshotProjectResult.STEAMLEARN_SNAPSHOT_PROJECT_ERROR_INTERNAL_DATA_SOURCE_ERROR;
  export type STEAMLEARN_SNAPSHOT_PROJECT_DISABLED =
    typeof ESteamLearnSnapshotProjectResult.STEAMLEARN_SNAPSHOT_PROJECT_DISABLED;
  export type STEAMLEARN_SNAPSHOT_PROJECT_ERROR_INVALID_PUBLISHED_VERSION =
    typeof ESteamLearnSnapshotProjectResult.STEAMLEARN_SNAPSHOT_PROJECT_ERROR_INVALID_PUBLISHED_VERSION;
  export type UNRECOGNIZED = typeof ESteamLearnSnapshotProjectResult.UNRECOGNIZED;
}

export const ESteamLearnGetHMACKeysResult = { STEAMLEARN_GET_HMAC_KEYS_SUCCESS: 0, UNRECOGNIZED: -1 } as const;

export type ESteamLearnGetHMACKeysResult =
  typeof ESteamLearnGetHMACKeysResult[keyof typeof ESteamLearnGetHMACKeysResult];

export namespace ESteamLearnGetHMACKeysResult {
  export type STEAMLEARN_GET_HMAC_KEYS_SUCCESS = typeof ESteamLearnGetHMACKeysResult.STEAMLEARN_GET_HMAC_KEYS_SUCCESS;
  export type UNRECOGNIZED = typeof ESteamLearnGetHMACKeysResult.UNRECOGNIZED;
}

export const ESteamLearnInferenceResult = {
  STEAMLEARN_INFERENCE_ERROR: 0,
  STEAMLEARN_INFERENCE_SUCCESS: 1,
  STEAMLEARN_INFERENCE_ERROR_INVALID_PROJECT_ID: 2,
  STEAMLEARN_INFERENCE_ERROR_MISSING_CACHED_SCHEMA_DATA: 3,
  STEAMLEARN_INFERENCE_ERROR_NO_PUBLISHED_CONFIG: 4,
  STEAMLEARN_INFERENCE_ERROR_FORBIDDEN: 5,
  STEAMLEARN_INFERENCE_ERROR_INVALID_TIMESTAMP: 6,
  STEAMLEARN_INFERENCE_ERROR_INVALID_PUBLISHED_VERSION: 7,
  STEAMLEARN_INFERENCE_ERROR_NO_FETCH_ID_FOUND: 8,
  STEAMLEARN_INFERENCE_ERROR_TOO_BUSY: 9,
  UNRECOGNIZED: -1,
} as const;

export type ESteamLearnInferenceResult = typeof ESteamLearnInferenceResult[keyof typeof ESteamLearnInferenceResult];

export namespace ESteamLearnInferenceResult {
  export type STEAMLEARN_INFERENCE_ERROR = typeof ESteamLearnInferenceResult.STEAMLEARN_INFERENCE_ERROR;
  export type STEAMLEARN_INFERENCE_SUCCESS = typeof ESteamLearnInferenceResult.STEAMLEARN_INFERENCE_SUCCESS;
  export type STEAMLEARN_INFERENCE_ERROR_INVALID_PROJECT_ID =
    typeof ESteamLearnInferenceResult.STEAMLEARN_INFERENCE_ERROR_INVALID_PROJECT_ID;
  export type STEAMLEARN_INFERENCE_ERROR_MISSING_CACHED_SCHEMA_DATA =
    typeof ESteamLearnInferenceResult.STEAMLEARN_INFERENCE_ERROR_MISSING_CACHED_SCHEMA_DATA;
  export type STEAMLEARN_INFERENCE_ERROR_NO_PUBLISHED_CONFIG =
    typeof ESteamLearnInferenceResult.STEAMLEARN_INFERENCE_ERROR_NO_PUBLISHED_CONFIG;
  export type STEAMLEARN_INFERENCE_ERROR_FORBIDDEN =
    typeof ESteamLearnInferenceResult.STEAMLEARN_INFERENCE_ERROR_FORBIDDEN;
  export type STEAMLEARN_INFERENCE_ERROR_INVALID_TIMESTAMP =
    typeof ESteamLearnInferenceResult.STEAMLEARN_INFERENCE_ERROR_INVALID_TIMESTAMP;
  export type STEAMLEARN_INFERENCE_ERROR_INVALID_PUBLISHED_VERSION =
    typeof ESteamLearnInferenceResult.STEAMLEARN_INFERENCE_ERROR_INVALID_PUBLISHED_VERSION;
  export type STEAMLEARN_INFERENCE_ERROR_NO_FETCH_ID_FOUND =
    typeof ESteamLearnInferenceResult.STEAMLEARN_INFERENCE_ERROR_NO_FETCH_ID_FOUND;
  export type STEAMLEARN_INFERENCE_ERROR_TOO_BUSY =
    typeof ESteamLearnInferenceResult.STEAMLEARN_INFERENCE_ERROR_TOO_BUSY;
  export type UNRECOGNIZED = typeof ESteamLearnInferenceResult.UNRECOGNIZED;
}

export const ESteamLearnInferenceMetadataResult = {
  STEAMLEARN_INFERENCE_METADATA_ERROR: 0,
  STEAMLEARN_INFERENCE_METADATA_SUCCESS: 1,
  STEAMLEARN_INFERENCE_METADATA_ERROR_INVALID_PROJECT_ID: 2,
  STEAMLEARN_INFERENCE_METADATA_ERROR_NO_PUBLISHED_CONFIG: 3,
  STEAMLEARN_INFERENCE_METADATA_ERROR_FORBIDDEN: 4,
  STEAMLEARN_INFERENCE_METADATA_ERROR_INVALID_TIMESTAMP: 5,
  STEAMLEARN_INFERENCE_METADATA_ERROR_INVALID_PUBLISHED_VERSION: 6,
  STEAMLEARN_INFERENCE_METADATA_ERROR_NO_FETCH_ID_FOUND: 7,
  UNRECOGNIZED: -1,
} as const;

export type ESteamLearnInferenceMetadataResult =
  typeof ESteamLearnInferenceMetadataResult[keyof typeof ESteamLearnInferenceMetadataResult];

export namespace ESteamLearnInferenceMetadataResult {
  export type STEAMLEARN_INFERENCE_METADATA_ERROR =
    typeof ESteamLearnInferenceMetadataResult.STEAMLEARN_INFERENCE_METADATA_ERROR;
  export type STEAMLEARN_INFERENCE_METADATA_SUCCESS =
    typeof ESteamLearnInferenceMetadataResult.STEAMLEARN_INFERENCE_METADATA_SUCCESS;
  export type STEAMLEARN_INFERENCE_METADATA_ERROR_INVALID_PROJECT_ID =
    typeof ESteamLearnInferenceMetadataResult.STEAMLEARN_INFERENCE_METADATA_ERROR_INVALID_PROJECT_ID;
  export type STEAMLEARN_INFERENCE_METADATA_ERROR_NO_PUBLISHED_CONFIG =
    typeof ESteamLearnInferenceMetadataResult.STEAMLEARN_INFERENCE_METADATA_ERROR_NO_PUBLISHED_CONFIG;
  export type STEAMLEARN_INFERENCE_METADATA_ERROR_FORBIDDEN =
    typeof ESteamLearnInferenceMetadataResult.STEAMLEARN_INFERENCE_METADATA_ERROR_FORBIDDEN;
  export type STEAMLEARN_INFERENCE_METADATA_ERROR_INVALID_TIMESTAMP =
    typeof ESteamLearnInferenceMetadataResult.STEAMLEARN_INFERENCE_METADATA_ERROR_INVALID_TIMESTAMP;
  export type STEAMLEARN_INFERENCE_METADATA_ERROR_INVALID_PUBLISHED_VERSION =
    typeof ESteamLearnInferenceMetadataResult.STEAMLEARN_INFERENCE_METADATA_ERROR_INVALID_PUBLISHED_VERSION;
  export type STEAMLEARN_INFERENCE_METADATA_ERROR_NO_FETCH_ID_FOUND =
    typeof ESteamLearnInferenceMetadataResult.STEAMLEARN_INFERENCE_METADATA_ERROR_NO_FETCH_ID_FOUND;
  export type UNRECOGNIZED = typeof ESteamLearnInferenceMetadataResult.UNRECOGNIZED;
}

export interface CMsgSteamLearnDataSourceDescObject {
  elements: CMsgSteamLearnDataSourceDescElement[];
}

export interface CMsgSteamLearnDataSourceDescElement {
  name?: string | undefined;
  data_type?: ESteamLearnDataType | undefined;
  object?: CMsgSteamLearnDataSourceDescObject | undefined;
  count?: number | undefined;
}

export interface CMsgSteamLearnDataSource {
  id?: number | undefined;
  name?: string | undefined;
  version?: number | undefined;
  source_description?: string | undefined;
  structure?: CMsgSteamLearnDataSourceDescObject | undefined;
  structure_crc?: number | undefined;
  cache_duration_seconds?: number | undefined;
}

export interface CMsgSteamLearnDataObject {
  elements: CMsgSteamLearnDataElement[];
}

export interface CMsgSteamLearnDataElement {
  name?: string | undefined;
  data_int32s: number[];
  data_floats: number[];
  data_bools: boolean[];
  data_strings: string[];
  data_objects: CMsgSteamLearnDataObject[];
}

export interface CMsgSteamLearnData {
  data_source_id?: number | undefined;
  keys: string[];
  data_object?: CMsgSteamLearnDataObject | undefined;
}

export interface CMsgSteamLearnDataList {
  data: CMsgSteamLearnData[];
}

export interface CMsgSteamLearn_AccessData {
  publisher_id?: number | undefined;
  timestamp?: number | undefined;
  random_value?: string | undefined;
}

export interface CMsgSteamLearn_RegisterDataSource_Request {
  access_token?: string | undefined;
  access_data?: CMsgSteamLearn_AccessData | undefined;
  data_source?: CMsgSteamLearnDataSource | undefined;
}

export interface CMsgSteamLearn_RegisterDataSource_Response {
  result?: ESteammLearnRegisterDataSourceResult | undefined;
  data_source?: CMsgSteamLearnDataSource | undefined;
}

export interface CMsgSteamLearn_CacheData_Request {
  access_token?: string | undefined;
  access_data?: CMsgSteamLearn_AccessData | undefined;
  data?: CMsgSteamLearnData | undefined;
}

export interface CMsgSteamLearn_CacheData_Response {
  cache_data_result?: ESteamLearnCacheDataResult | undefined;
}

export interface CMsgSteamLearn_SnapshotProject_Request {
  access_token?: string | undefined;
  access_data?: CMsgSteamLearn_AccessData | undefined;
  project_id?: number | undefined;
  published_version?: number | undefined;
  keys: string[];
  data: CMsgSteamLearnData[];
  pending_data_limit_seconds?: number | undefined;
}

export interface CMsgSteamLearn_SnapshotProject_Response {
  snapshot_result?: ESteamLearnSnapshotProjectResult | undefined;
}

export interface CMsgSteamLearn_BatchOperation_Request {
  cache_data_requests: CMsgSteamLearn_CacheData_Request[];
  snapshot_requests: CMsgSteamLearn_SnapshotProject_Request[];
}

export interface CMsgSteamLearn_BatchOperation_Response {
  cache_data_responses: CMsgSteamLearn_CacheData_Response[];
  snapshot_responses: CMsgSteamLearn_SnapshotProject_Response[];
}

export interface CMsgSteamLearnHMACKeys {
  register_data_source_key?: string | undefined;
  cache_data_keys: CMsgSteamLearnHMACKeys_CacheDataKeys[];
  snapshot_project_keys: CMsgSteamLearnHMACKeys_SnapshotProjectKeys[];
}

export interface CMsgSteamLearnHMACKeys_CacheDataKeys {
  data_source_id?: number | undefined;
  version?: number | undefined;
  key?: string | undefined;
}

export interface CMsgSteamLearnHMACKeys_SnapshotProjectKeys {
  project_id?: number | undefined;
  published_version?: number | undefined;
  key?: string | undefined;
}

export interface CMsgSteamLearn_GetHMACKeys_Request {
  appid?: number | undefined;
}

export interface CMsgSteamLearn_GetHMACKeys_Response {
  result?: ESteamLearnGetHMACKeysResult | undefined;
  keys?: CMsgSteamLearnHMACKeys | undefined;
}

export interface CMsgSteamLearn_Inference_Request {
  access_token?: string | undefined;
  access_data?: CMsgSteamLearn_AccessData | undefined;
  project_id?: number | undefined;
  published_version?: number | undefined;
  override_train_id?: number | undefined;
  data?: CMsgSteamLearnDataList | undefined;
  additional_data: number[];
}

export interface CMsgSteamLearn_InferenceMetadata_Request {
  access_token?: string | undefined;
  access_data?: CMsgSteamLearn_AccessData | undefined;
  project_id?: number | undefined;
  published_version?: number | undefined;
  override_train_id?: number | undefined;
}

export interface CMsgSteamLearn_InferenceMetadataBackend_Request {
  project_id?: number | undefined;
  fetch_id?: number | undefined;
}

export interface CMsgSteamLearn_InferenceMetadata_Response {
  inference_metadata_result?: ESteamLearnInferenceMetadataResult | undefined;
  row_range?: CMsgSteamLearn_InferenceMetadata_Response_RowRange | undefined;
  ranges: CMsgSteamLearn_InferenceMetadata_Response_Range[];
  std_devs: CMsgSteamLearn_InferenceMetadata_Response_StdDev[];
  compact_tables: CMsgSteamLearn_InferenceMetadata_Response_CompactTable[];
  kmeans: CMsgSteamLearn_InferenceMetadata_Response_KMeans[];
  snapshot_histogram?: CMsgSteamLearn_InferenceMetadata_Response_SnapshotHistogram | undefined;
}

export interface CMsgSteamLearn_InferenceMetadata_Response_RowRange {
  min_row?: string | undefined;
  max_row?: string | undefined;
}

export interface CMsgSteamLearn_InferenceMetadata_Response_Range {
  data_element_path?: string | undefined;
  min_value?: number | undefined;
  max_value?: number | undefined;
}

export interface CMsgSteamLearn_InferenceMetadata_Response_StdDev {
  data_element_path?: string | undefined;
  mean?: number | undefined;
  std_dev?: number | undefined;
}

export interface CMsgSteamLearn_InferenceMetadata_Response_CompactTable {
  name?: string | undefined;
  map_values: CMsgSteamLearn_InferenceMetadata_Response_CompactTable_MapValuesEntry[];
  map_mappings: CMsgSteamLearn_InferenceMetadata_Response_CompactTable_MapMappingsEntry[];
}

export interface CMsgSteamLearn_InferenceMetadata_Response_CompactTable_Entry {
  value?: number | undefined;
  mapping?: number | undefined;
  count?: string | undefined;
}

export interface CMsgSteamLearn_InferenceMetadata_Response_CompactTable_MapValuesEntry {
  key?: number | undefined;
  value?: CMsgSteamLearn_InferenceMetadata_Response_CompactTable_Entry | undefined;
}

export interface CMsgSteamLearn_InferenceMetadata_Response_CompactTable_MapMappingsEntry {
  key?: number | undefined;
  value?: CMsgSteamLearn_InferenceMetadata_Response_CompactTable_Entry | undefined;
}

export interface CMsgSteamLearn_InferenceMetadata_Response_KMeans {
  name?: string | undefined;
  clusters: CMsgSteamLearn_InferenceMetadata_Response_KMeans_Cluster[];
}

export interface CMsgSteamLearn_InferenceMetadata_Response_KMeans_Cluster {
  x?: number | undefined;
  y?: number | undefined;
  radius?: number | undefined;
  radius_75pct?: number | undefined;
  radius_50pct?: number | undefined;
  radius_25pct?: number | undefined;
}

export interface CMsgSteamLearn_InferenceMetadata_Response_SnapshotHistogram {
  min_value?: number | undefined;
  max_value?: number | undefined;
  num_buckets?: number | undefined;
  bucket_counts: number[];
}

export interface CMsgSteamLearn_InferenceBackend_Response {
  outputs: CMsgSteamLearn_InferenceBackend_Response_Output[];
}

export interface CMsgSteamLearn_InferenceBackend_Response_BinaryCrossEntropyOutput {
  value?: number | undefined;
}

export interface CMsgSteamLearn_InferenceBackend_Response_MutliBinaryCrossEntropyOutput {
  weight: number[];
  value: number[];
}

export interface CMsgSteamLearn_InferenceBackend_Response_CategoricalCrossEntropyOutput {
  weight: number[];
  value: number[];
}

export interface CMsgSteamLearn_InferenceBackend_Response_Output {
  binary_crossentropy?: CMsgSteamLearn_InferenceBackend_Response_BinaryCrossEntropyOutput | undefined;
  categorical_crossentropy?: CMsgSteamLearn_InferenceBackend_Response_CategoricalCrossEntropyOutput | undefined;
  multi_binary_crossentropy?: CMsgSteamLearn_InferenceBackend_Response_MutliBinaryCrossEntropyOutput | undefined;
}

export interface CMsgSteamLearn_Inference_Response {
  inference_result?: ESteamLearnInferenceResult | undefined;
  backend_response?: CMsgSteamLearn_InferenceBackend_Response | undefined;
}

function createBaseCMsgSteamLearnDataSourceDescObject(): CMsgSteamLearnDataSourceDescObject {
  return { elements: [] };
}

export const CMsgSteamLearnDataSourceDescObject: MessageFns<CMsgSteamLearnDataSourceDescObject> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearnDataSourceDescObject {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearnDataSourceDescObject();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.elements.push(CMsgSteamLearnDataSourceDescElement.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearnDataSourceDescElement(): CMsgSteamLearnDataSourceDescElement {
  return { name: undefined, data_type: undefined, object: undefined, count: undefined };
}

export const CMsgSteamLearnDataSourceDescElement: MessageFns<CMsgSteamLearnDataSourceDescElement> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearnDataSourceDescElement {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearnDataSourceDescElement();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.data_type = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.object = CMsgSteamLearnDataSourceDescObject.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.count = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearnDataSource(): CMsgSteamLearnDataSource {
  return {
    id: undefined,
    name: undefined,
    version: undefined,
    source_description: undefined,
    structure: undefined,
    structure_crc: undefined,
    cache_duration_seconds: undefined,
  };
}

export const CMsgSteamLearnDataSource: MessageFns<CMsgSteamLearnDataSource> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearnDataSource {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearnDataSource();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.version = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.source_description = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.structure = CMsgSteamLearnDataSourceDescObject.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.structure_crc = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.cache_duration_seconds = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearnDataObject(): CMsgSteamLearnDataObject {
  return { elements: [] };
}

export const CMsgSteamLearnDataObject: MessageFns<CMsgSteamLearnDataObject> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearnDataObject {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearnDataObject();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.elements.push(CMsgSteamLearnDataElement.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearnDataElement(): CMsgSteamLearnDataElement {
  return { name: undefined, data_int32s: [], data_floats: [], data_bools: [], data_strings: [], data_objects: [] };
}

export const CMsgSteamLearnDataElement: MessageFns<CMsgSteamLearnDataElement> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearnDataElement {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearnDataElement();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 20: {
          if (tag === 160) {
            message.data_int32s.push(reader.int32());

            continue;
          }

          if (tag === 162) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.data_int32s.push(reader.int32());
            }

            continue;
          }

          break;
        }
        case 21: {
          if (tag === 173) {
            message.data_floats.push(reader.float());

            continue;
          }

          if (tag === 170) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.data_floats.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 22: {
          if (tag === 176) {
            message.data_bools.push(reader.bool());

            continue;
          }

          if (tag === 178) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.data_bools.push(reader.bool());
            }

            continue;
          }

          break;
        }
        case 23: {
          if (tag !== 186) {
            break;
          }

          message.data_strings.push(reader.string());
          continue;
        }
        case 24: {
          if (tag !== 194) {
            break;
          }

          message.data_objects.push(CMsgSteamLearnDataObject.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearnData(): CMsgSteamLearnData {
  return { data_source_id: undefined, keys: [], data_object: undefined };
}

export const CMsgSteamLearnData: MessageFns<CMsgSteamLearnData> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearnData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearnData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.data_source_id = reader.uint32();
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.keys.push(reader.uint64().toString());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.keys.push(reader.uint64().toString());
            }

            continue;
          }

          break;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.data_object = CMsgSteamLearnDataObject.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearnDataList(): CMsgSteamLearnDataList {
  return { data: [] };
}

export const CMsgSteamLearnDataList: MessageFns<CMsgSteamLearnDataList> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearnDataList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearnDataList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data.push(CMsgSteamLearnData.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_AccessData(): CMsgSteamLearn_AccessData {
  return { publisher_id: undefined, timestamp: undefined, random_value: undefined };
}

export const CMsgSteamLearn_AccessData: MessageFns<CMsgSteamLearn_AccessData> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearn_AccessData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_AccessData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.publisher_id = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestamp = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.random_value = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_RegisterDataSource_Request(): CMsgSteamLearn_RegisterDataSource_Request {
  return { access_token: undefined, access_data: undefined, data_source: undefined };
}

export const CMsgSteamLearn_RegisterDataSource_Request: MessageFns<CMsgSteamLearn_RegisterDataSource_Request> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearn_RegisterDataSource_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_RegisterDataSource_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.access_token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.access_data = CMsgSteamLearn_AccessData.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.data_source = CMsgSteamLearnDataSource.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_RegisterDataSource_Response(): CMsgSteamLearn_RegisterDataSource_Response {
  return { result: undefined, data_source: undefined };
}

export const CMsgSteamLearn_RegisterDataSource_Response: MessageFns<CMsgSteamLearn_RegisterDataSource_Response> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearn_RegisterDataSource_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_RegisterDataSource_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.result = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data_source = CMsgSteamLearnDataSource.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_CacheData_Request(): CMsgSteamLearn_CacheData_Request {
  return { access_token: undefined, access_data: undefined, data: undefined };
}

export const CMsgSteamLearn_CacheData_Request: MessageFns<CMsgSteamLearn_CacheData_Request> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearn_CacheData_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_CacheData_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.access_token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.access_data = CMsgSteamLearn_AccessData.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.data = CMsgSteamLearnData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_CacheData_Response(): CMsgSteamLearn_CacheData_Response {
  return { cache_data_result: undefined };
}

export const CMsgSteamLearn_CacheData_Response: MessageFns<CMsgSteamLearn_CacheData_Response> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearn_CacheData_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_CacheData_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.cache_data_result = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_SnapshotProject_Request(): CMsgSteamLearn_SnapshotProject_Request {
  return {
    access_token: undefined,
    access_data: undefined,
    project_id: undefined,
    published_version: undefined,
    keys: [],
    data: [],
    pending_data_limit_seconds: undefined,
  };
}

export const CMsgSteamLearn_SnapshotProject_Request: MessageFns<CMsgSteamLearn_SnapshotProject_Request> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearn_SnapshotProject_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_SnapshotProject_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.access_token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.access_data = CMsgSteamLearn_AccessData.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.project_id = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.published_version = reader.uint32();
          continue;
        }
        case 4: {
          if (tag === 32) {
            message.keys.push(reader.uint64().toString());

            continue;
          }

          if (tag === 34) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.keys.push(reader.uint64().toString());
            }

            continue;
          }

          break;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.data.push(CMsgSteamLearnData.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.pending_data_limit_seconds = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_SnapshotProject_Response(): CMsgSteamLearn_SnapshotProject_Response {
  return { snapshot_result: undefined };
}

export const CMsgSteamLearn_SnapshotProject_Response: MessageFns<CMsgSteamLearn_SnapshotProject_Response> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearn_SnapshotProject_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_SnapshotProject_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.snapshot_result = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_BatchOperation_Request(): CMsgSteamLearn_BatchOperation_Request {
  return { cache_data_requests: [], snapshot_requests: [] };
}

export const CMsgSteamLearn_BatchOperation_Request: MessageFns<CMsgSteamLearn_BatchOperation_Request> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearn_BatchOperation_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_BatchOperation_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cache_data_requests.push(CMsgSteamLearn_CacheData_Request.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.snapshot_requests.push(CMsgSteamLearn_SnapshotProject_Request.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_BatchOperation_Response(): CMsgSteamLearn_BatchOperation_Response {
  return { cache_data_responses: [], snapshot_responses: [] };
}

export const CMsgSteamLearn_BatchOperation_Response: MessageFns<CMsgSteamLearn_BatchOperation_Response> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearn_BatchOperation_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_BatchOperation_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cache_data_responses.push(CMsgSteamLearn_CacheData_Response.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.snapshot_responses.push(CMsgSteamLearn_SnapshotProject_Response.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearnHMACKeys(): CMsgSteamLearnHMACKeys {
  return { register_data_source_key: undefined, cache_data_keys: [], snapshot_project_keys: [] };
}

export const CMsgSteamLearnHMACKeys: MessageFns<CMsgSteamLearnHMACKeys> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearnHMACKeys {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearnHMACKeys();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.register_data_source_key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.cache_data_keys.push(CMsgSteamLearnHMACKeys_CacheDataKeys.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.snapshot_project_keys.push(
            CMsgSteamLearnHMACKeys_SnapshotProjectKeys.decode(reader, reader.uint32()),
          );
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearnHMACKeys_CacheDataKeys(): CMsgSteamLearnHMACKeys_CacheDataKeys {
  return { data_source_id: undefined, version: undefined, key: undefined };
}

export const CMsgSteamLearnHMACKeys_CacheDataKeys: MessageFns<CMsgSteamLearnHMACKeys_CacheDataKeys> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearnHMACKeys_CacheDataKeys {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearnHMACKeys_CacheDataKeys();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.data_source_id = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.version = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.key = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearnHMACKeys_SnapshotProjectKeys(): CMsgSteamLearnHMACKeys_SnapshotProjectKeys {
  return { project_id: undefined, published_version: undefined, key: undefined };
}

export const CMsgSteamLearnHMACKeys_SnapshotProjectKeys: MessageFns<CMsgSteamLearnHMACKeys_SnapshotProjectKeys> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearnHMACKeys_SnapshotProjectKeys {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearnHMACKeys_SnapshotProjectKeys();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.project_id = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.published_version = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.key = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_GetHMACKeys_Request(): CMsgSteamLearn_GetHMACKeys_Request {
  return { appid: undefined };
}

export const CMsgSteamLearn_GetHMACKeys_Request: MessageFns<CMsgSteamLearn_GetHMACKeys_Request> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearn_GetHMACKeys_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_GetHMACKeys_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.appid = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_GetHMACKeys_Response(): CMsgSteamLearn_GetHMACKeys_Response {
  return { result: undefined, keys: undefined };
}

export const CMsgSteamLearn_GetHMACKeys_Response: MessageFns<CMsgSteamLearn_GetHMACKeys_Response> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearn_GetHMACKeys_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_GetHMACKeys_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.result = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.keys = CMsgSteamLearnHMACKeys.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_Inference_Request(): CMsgSteamLearn_Inference_Request {
  return {
    access_token: undefined,
    access_data: undefined,
    project_id: undefined,
    published_version: undefined,
    override_train_id: undefined,
    data: undefined,
    additional_data: [],
  };
}

export const CMsgSteamLearn_Inference_Request: MessageFns<CMsgSteamLearn_Inference_Request> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearn_Inference_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_Inference_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.access_token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.access_data = CMsgSteamLearn_AccessData.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.project_id = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.published_version = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.override_train_id = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.data = CMsgSteamLearnDataList.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag === 61) {
            message.additional_data.push(reader.float());

            continue;
          }

          if (tag === 58) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.additional_data.push(reader.float());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_InferenceMetadata_Request(): CMsgSteamLearn_InferenceMetadata_Request {
  return {
    access_token: undefined,
    access_data: undefined,
    project_id: undefined,
    published_version: undefined,
    override_train_id: undefined,
  };
}

export const CMsgSteamLearn_InferenceMetadata_Request: MessageFns<CMsgSteamLearn_InferenceMetadata_Request> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearn_InferenceMetadata_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_InferenceMetadata_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.access_token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.access_data = CMsgSteamLearn_AccessData.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.project_id = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.published_version = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.override_train_id = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_InferenceMetadataBackend_Request(): CMsgSteamLearn_InferenceMetadataBackend_Request {
  return { project_id: undefined, fetch_id: undefined };
}

export const CMsgSteamLearn_InferenceMetadataBackend_Request: MessageFns<
  CMsgSteamLearn_InferenceMetadataBackend_Request
> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearn_InferenceMetadataBackend_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_InferenceMetadataBackend_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.project_id = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.fetch_id = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_InferenceMetadata_Response(): CMsgSteamLearn_InferenceMetadata_Response {
  return {
    inference_metadata_result: undefined,
    row_range: undefined,
    ranges: [],
    std_devs: [],
    compact_tables: [],
    kmeans: [],
    snapshot_histogram: undefined,
  };
}

export const CMsgSteamLearn_InferenceMetadata_Response: MessageFns<CMsgSteamLearn_InferenceMetadata_Response> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearn_InferenceMetadata_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_InferenceMetadata_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.inference_metadata_result = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.row_range = CMsgSteamLearn_InferenceMetadata_Response_RowRange.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ranges.push(CMsgSteamLearn_InferenceMetadata_Response_Range.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.std_devs.push(CMsgSteamLearn_InferenceMetadata_Response_StdDev.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.compact_tables.push(
            CMsgSteamLearn_InferenceMetadata_Response_CompactTable.decode(reader, reader.uint32()),
          );
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.kmeans.push(CMsgSteamLearn_InferenceMetadata_Response_KMeans.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.snapshot_histogram = CMsgSteamLearn_InferenceMetadata_Response_SnapshotHistogram.decode(
            reader,
            reader.uint32(),
          );
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_InferenceMetadata_Response_RowRange(): CMsgSteamLearn_InferenceMetadata_Response_RowRange {
  return { min_row: undefined, max_row: undefined };
}

export const CMsgSteamLearn_InferenceMetadata_Response_RowRange: MessageFns<
  CMsgSteamLearn_InferenceMetadata_Response_RowRange
> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearn_InferenceMetadata_Response_RowRange {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_InferenceMetadata_Response_RowRange();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.min_row = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.max_row = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_InferenceMetadata_Response_Range(): CMsgSteamLearn_InferenceMetadata_Response_Range {
  return { data_element_path: undefined, min_value: undefined, max_value: undefined };
}

export const CMsgSteamLearn_InferenceMetadata_Response_Range: MessageFns<
  CMsgSteamLearn_InferenceMetadata_Response_Range
> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearn_InferenceMetadata_Response_Range {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_InferenceMetadata_Response_Range();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data_element_path = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.min_value = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.max_value = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_InferenceMetadata_Response_StdDev(): CMsgSteamLearn_InferenceMetadata_Response_StdDev {
  return { data_element_path: undefined, mean: undefined, std_dev: undefined };
}

export const CMsgSteamLearn_InferenceMetadata_Response_StdDev: MessageFns<
  CMsgSteamLearn_InferenceMetadata_Response_StdDev
> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearn_InferenceMetadata_Response_StdDev {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_InferenceMetadata_Response_StdDev();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data_element_path = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.mean = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.std_dev = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_InferenceMetadata_Response_CompactTable(): CMsgSteamLearn_InferenceMetadata_Response_CompactTable {
  return { name: undefined, map_values: [], map_mappings: [] };
}

export const CMsgSteamLearn_InferenceMetadata_Response_CompactTable: MessageFns<
  CMsgSteamLearn_InferenceMetadata_Response_CompactTable
> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearn_InferenceMetadata_Response_CompactTable {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_InferenceMetadata_Response_CompactTable();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.map_values.push(
            CMsgSteamLearn_InferenceMetadata_Response_CompactTable_MapValuesEntry.decode(reader, reader.uint32()),
          );
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.map_mappings.push(
            CMsgSteamLearn_InferenceMetadata_Response_CompactTable_MapMappingsEntry.decode(reader, reader.uint32()),
          );
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_InferenceMetadata_Response_CompactTable_Entry(): CMsgSteamLearn_InferenceMetadata_Response_CompactTable_Entry {
  return { value: undefined, mapping: undefined, count: undefined };
}

export const CMsgSteamLearn_InferenceMetadata_Response_CompactTable_Entry: MessageFns<
  CMsgSteamLearn_InferenceMetadata_Response_CompactTable_Entry
> = {
  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): CMsgSteamLearn_InferenceMetadata_Response_CompactTable_Entry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_InferenceMetadata_Response_CompactTable_Entry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.value = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.mapping = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.count = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_InferenceMetadata_Response_CompactTable_MapValuesEntry(): CMsgSteamLearn_InferenceMetadata_Response_CompactTable_MapValuesEntry {
  return { key: undefined, value: undefined };
}

export const CMsgSteamLearn_InferenceMetadata_Response_CompactTable_MapValuesEntry: MessageFns<
  CMsgSteamLearn_InferenceMetadata_Response_CompactTable_MapValuesEntry
> = {
  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): CMsgSteamLearn_InferenceMetadata_Response_CompactTable_MapValuesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_InferenceMetadata_Response_CompactTable_MapValuesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.key = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = CMsgSteamLearn_InferenceMetadata_Response_CompactTable_Entry.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_InferenceMetadata_Response_CompactTable_MapMappingsEntry(): CMsgSteamLearn_InferenceMetadata_Response_CompactTable_MapMappingsEntry {
  return { key: undefined, value: undefined };
}

export const CMsgSteamLearn_InferenceMetadata_Response_CompactTable_MapMappingsEntry: MessageFns<
  CMsgSteamLearn_InferenceMetadata_Response_CompactTable_MapMappingsEntry
> = {
  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): CMsgSteamLearn_InferenceMetadata_Response_CompactTable_MapMappingsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_InferenceMetadata_Response_CompactTable_MapMappingsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.key = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = CMsgSteamLearn_InferenceMetadata_Response_CompactTable_Entry.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_InferenceMetadata_Response_KMeans(): CMsgSteamLearn_InferenceMetadata_Response_KMeans {
  return { name: undefined, clusters: [] };
}

export const CMsgSteamLearn_InferenceMetadata_Response_KMeans: MessageFns<
  CMsgSteamLearn_InferenceMetadata_Response_KMeans
> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearn_InferenceMetadata_Response_KMeans {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_InferenceMetadata_Response_KMeans();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clusters.push(
            CMsgSteamLearn_InferenceMetadata_Response_KMeans_Cluster.decode(reader, reader.uint32()),
          );
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_InferenceMetadata_Response_KMeans_Cluster(): CMsgSteamLearn_InferenceMetadata_Response_KMeans_Cluster {
  return {
    x: undefined,
    y: undefined,
    radius: undefined,
    radius_75pct: undefined,
    radius_50pct: undefined,
    radius_25pct: undefined,
  };
}

export const CMsgSteamLearn_InferenceMetadata_Response_KMeans_Cluster: MessageFns<
  CMsgSteamLearn_InferenceMetadata_Response_KMeans_Cluster
> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearn_InferenceMetadata_Response_KMeans_Cluster {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_InferenceMetadata_Response_KMeans_Cluster();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.x = reader.float();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.y = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.radius = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.radius_75pct = reader.float();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.radius_50pct = reader.float();
          continue;
        }
        case 6: {
          if (tag !== 53) {
            break;
          }

          message.radius_25pct = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_InferenceMetadata_Response_SnapshotHistogram(): CMsgSteamLearn_InferenceMetadata_Response_SnapshotHistogram {
  return { min_value: undefined, max_value: undefined, num_buckets: undefined, bucket_counts: [] };
}

export const CMsgSteamLearn_InferenceMetadata_Response_SnapshotHistogram: MessageFns<
  CMsgSteamLearn_InferenceMetadata_Response_SnapshotHistogram
> = {
  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): CMsgSteamLearn_InferenceMetadata_Response_SnapshotHistogram {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_InferenceMetadata_Response_SnapshotHistogram();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.min_value = reader.float();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.max_value = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.num_buckets = reader.uint32();
          continue;
        }
        case 4: {
          if (tag === 32) {
            message.bucket_counts.push(reader.uint32());

            continue;
          }

          if (tag === 34) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.bucket_counts.push(reader.uint32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_InferenceBackend_Response(): CMsgSteamLearn_InferenceBackend_Response {
  return { outputs: [] };
}

export const CMsgSteamLearn_InferenceBackend_Response: MessageFns<CMsgSteamLearn_InferenceBackend_Response> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearn_InferenceBackend_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_InferenceBackend_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.outputs.push(CMsgSteamLearn_InferenceBackend_Response_Output.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_InferenceBackend_Response_BinaryCrossEntropyOutput(): CMsgSteamLearn_InferenceBackend_Response_BinaryCrossEntropyOutput {
  return { value: undefined };
}

export const CMsgSteamLearn_InferenceBackend_Response_BinaryCrossEntropyOutput: MessageFns<
  CMsgSteamLearn_InferenceBackend_Response_BinaryCrossEntropyOutput
> = {
  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): CMsgSteamLearn_InferenceBackend_Response_BinaryCrossEntropyOutput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_InferenceBackend_Response_BinaryCrossEntropyOutput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.value = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_InferenceBackend_Response_MutliBinaryCrossEntropyOutput(): CMsgSteamLearn_InferenceBackend_Response_MutliBinaryCrossEntropyOutput {
  return { weight: [], value: [] };
}

export const CMsgSteamLearn_InferenceBackend_Response_MutliBinaryCrossEntropyOutput: MessageFns<
  CMsgSteamLearn_InferenceBackend_Response_MutliBinaryCrossEntropyOutput
> = {
  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): CMsgSteamLearn_InferenceBackend_Response_MutliBinaryCrossEntropyOutput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_InferenceBackend_Response_MutliBinaryCrossEntropyOutput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 13) {
            message.weight.push(reader.float());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.weight.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag === 21) {
            message.value.push(reader.float());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.value.push(reader.float());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_InferenceBackend_Response_CategoricalCrossEntropyOutput(): CMsgSteamLearn_InferenceBackend_Response_CategoricalCrossEntropyOutput {
  return { weight: [], value: [] };
}

export const CMsgSteamLearn_InferenceBackend_Response_CategoricalCrossEntropyOutput: MessageFns<
  CMsgSteamLearn_InferenceBackend_Response_CategoricalCrossEntropyOutput
> = {
  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): CMsgSteamLearn_InferenceBackend_Response_CategoricalCrossEntropyOutput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_InferenceBackend_Response_CategoricalCrossEntropyOutput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 13) {
            message.weight.push(reader.float());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.weight.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag === 21) {
            message.value.push(reader.float());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.value.push(reader.float());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_InferenceBackend_Response_Output(): CMsgSteamLearn_InferenceBackend_Response_Output {
  return { binary_crossentropy: undefined, categorical_crossentropy: undefined, multi_binary_crossentropy: undefined };
}

export const CMsgSteamLearn_InferenceBackend_Response_Output: MessageFns<
  CMsgSteamLearn_InferenceBackend_Response_Output
> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearn_InferenceBackend_Response_Output {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_InferenceBackend_Response_Output();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.binary_crossentropy = CMsgSteamLearn_InferenceBackend_Response_BinaryCrossEntropyOutput.decode(
            reader,
            reader.uint32(),
          );
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.categorical_crossentropy = CMsgSteamLearn_InferenceBackend_Response_CategoricalCrossEntropyOutput
            .decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.multi_binary_crossentropy = CMsgSteamLearn_InferenceBackend_Response_MutliBinaryCrossEntropyOutput
            .decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamLearn_Inference_Response(): CMsgSteamLearn_Inference_Response {
  return { inference_result: undefined, backend_response: undefined };
}

export const CMsgSteamLearn_Inference_Response: MessageFns<CMsgSteamLearn_Inference_Response> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamLearn_Inference_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamLearn_Inference_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.inference_result = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.backend_response = CMsgSteamLearn_InferenceBackend_Response.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface MessageFns<T> {
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
