// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: steamdatagram_messages_auth.proto

/* eslint-disable */
import { BinaryReader } from "@bufbuild/protobuf/wire";
import { CMsgSteamDatagramCertificateSigned } from "./steamnetworkingsockets_messages_certs.js";

export const protobufPackage = "";

export interface CMsgSteamDatagramRelayAuthTicket {
  time_expiry?: number | undefined;
  authorized_client_identity_string?: string | undefined;
  gameserver_identity_string?: string | undefined;
  authorized_public_ip?: number | undefined;
  gameserver_address?: Uint8Array | undefined;
  app_id?: number | undefined;
  virtual_port?: number | undefined;
  extra_fields: CMsgSteamDatagramRelayAuthTicket_ExtraField[];
  legacy_authorized_steam_id?: string | undefined;
  legacy_gameserver_steam_id?: string | undefined;
  legacy_gameserver_pop_id?: number | undefined;
  legacy_authorized_client_identity_binary?: Uint8Array | undefined;
  legacy_gameserver_identity_binary?: Uint8Array | undefined;
}

export interface CMsgSteamDatagramRelayAuthTicket_ExtraField {
  name?: string | undefined;
  string_value?: string | undefined;
  int64_value?: string | undefined;
  fixed64_value?: string | undefined;
}

export interface CMsgSteamDatagramSignedRelayAuthTicket {
  reserved_do_not_use?: string | undefined;
  ticket?: Uint8Array | undefined;
  signature?: Uint8Array | undefined;
  key_id?: string | undefined;
  certs: CMsgSteamDatagramCertificateSigned[];
}

export interface CMsgSteamDatagramCachedCredentialsForApp {
  private_key?: Uint8Array | undefined;
  cert?: Uint8Array | undefined;
  relay_tickets: Uint8Array[];
}

export interface CMsgSteamDatagramGameCoordinatorServerLogin {
  time_generated?: number | undefined;
  appid?: number | undefined;
  routing?: Uint8Array | undefined;
  appdata?: Uint8Array | undefined;
  legacy_identity_binary?: Uint8Array | undefined;
  identity_string?: string | undefined;
  dummy_steam_id?: string | undefined;
}

export interface CMsgSteamDatagramSignedGameCoordinatorServerLogin {
  cert?: CMsgSteamDatagramCertificateSigned | undefined;
  login?: Uint8Array | undefined;
  signature?: Uint8Array | undefined;
}

export interface CMsgSteamDatagramHostedServerAddressPlaintext {
  ipv4?: number | undefined;
  ipv6?: Uint8Array | undefined;
  port?: number | undefined;
  routing_secret?: string | undefined;
  protocol_version?: number | undefined;
}

function createBaseCMsgSteamDatagramRelayAuthTicket(): CMsgSteamDatagramRelayAuthTicket {
  return {
    time_expiry: undefined,
    authorized_client_identity_string: undefined,
    gameserver_identity_string: undefined,
    authorized_public_ip: undefined,
    gameserver_address: undefined,
    app_id: undefined,
    virtual_port: undefined,
    extra_fields: [],
    legacy_authorized_steam_id: undefined,
    legacy_gameserver_steam_id: undefined,
    legacy_gameserver_pop_id: undefined,
    legacy_authorized_client_identity_binary: undefined,
    legacy_gameserver_identity_binary: undefined,
  };
}

export const CMsgSteamDatagramRelayAuthTicket: MessageFns<CMsgSteamDatagramRelayAuthTicket> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamDatagramRelayAuthTicket {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamDatagramRelayAuthTicket();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.time_expiry = reader.fixed32();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.authorized_client_identity_string = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.gameserver_identity_string = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.authorized_public_ip = reader.fixed32();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.gameserver_address = reader.bytes();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.app_id = reader.uint32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.virtual_port = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.extra_fields.push(CMsgSteamDatagramRelayAuthTicket_ExtraField.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.legacy_authorized_steam_id = reader.fixed64().toString();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.legacy_gameserver_steam_id = reader.fixed64().toString();
          continue;
        }
        case 9: {
          if (tag !== 77) {
            break;
          }

          message.legacy_gameserver_pop_id = reader.fixed32();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.legacy_authorized_client_identity_binary = reader.bytes();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.legacy_gameserver_identity_binary = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamDatagramRelayAuthTicket_ExtraField(): CMsgSteamDatagramRelayAuthTicket_ExtraField {
  return { name: undefined, string_value: undefined, int64_value: undefined, fixed64_value: undefined };
}

export const CMsgSteamDatagramRelayAuthTicket_ExtraField: MessageFns<CMsgSteamDatagramRelayAuthTicket_ExtraField> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamDatagramRelayAuthTicket_ExtraField {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamDatagramRelayAuthTicket_ExtraField();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.string_value = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.int64_value = reader.sint64().toString();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.fixed64_value = reader.fixed64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamDatagramSignedRelayAuthTicket(): CMsgSteamDatagramSignedRelayAuthTicket {
  return { reserved_do_not_use: undefined, ticket: undefined, signature: undefined, key_id: undefined, certs: [] };
}

export const CMsgSteamDatagramSignedRelayAuthTicket: MessageFns<CMsgSteamDatagramSignedRelayAuthTicket> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamDatagramSignedRelayAuthTicket {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamDatagramSignedRelayAuthTicket();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.reserved_do_not_use = reader.fixed64().toString();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ticket = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.signature = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.key_id = reader.fixed64().toString();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.certs.push(CMsgSteamDatagramCertificateSigned.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamDatagramCachedCredentialsForApp(): CMsgSteamDatagramCachedCredentialsForApp {
  return { private_key: undefined, cert: undefined, relay_tickets: [] };
}

export const CMsgSteamDatagramCachedCredentialsForApp: MessageFns<CMsgSteamDatagramCachedCredentialsForApp> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamDatagramCachedCredentialsForApp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamDatagramCachedCredentialsForApp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.private_key = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.cert = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.relay_tickets.push(reader.bytes());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamDatagramGameCoordinatorServerLogin(): CMsgSteamDatagramGameCoordinatorServerLogin {
  return {
    time_generated: undefined,
    appid: undefined,
    routing: undefined,
    appdata: undefined,
    legacy_identity_binary: undefined,
    identity_string: undefined,
    dummy_steam_id: undefined,
  };
}

export const CMsgSteamDatagramGameCoordinatorServerLogin: MessageFns<CMsgSteamDatagramGameCoordinatorServerLogin> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamDatagramGameCoordinatorServerLogin {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamDatagramGameCoordinatorServerLogin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.time_generated = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.appid = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.routing = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.appdata = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.legacy_identity_binary = reader.bytes();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.identity_string = reader.string();
          continue;
        }
        case 99: {
          if (tag !== 793) {
            break;
          }

          message.dummy_steam_id = reader.fixed64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamDatagramSignedGameCoordinatorServerLogin(): CMsgSteamDatagramSignedGameCoordinatorServerLogin {
  return { cert: undefined, login: undefined, signature: undefined };
}

export const CMsgSteamDatagramSignedGameCoordinatorServerLogin: MessageFns<
  CMsgSteamDatagramSignedGameCoordinatorServerLogin
> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamDatagramSignedGameCoordinatorServerLogin {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamDatagramSignedGameCoordinatorServerLogin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cert = CMsgSteamDatagramCertificateSigned.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.login = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.signature = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamDatagramHostedServerAddressPlaintext(): CMsgSteamDatagramHostedServerAddressPlaintext {
  return { ipv4: undefined, ipv6: undefined, port: undefined, routing_secret: undefined, protocol_version: undefined };
}

export const CMsgSteamDatagramHostedServerAddressPlaintext: MessageFns<CMsgSteamDatagramHostedServerAddressPlaintext> =
  {
    decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamDatagramHostedServerAddressPlaintext {
      const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCMsgSteamDatagramHostedServerAddressPlaintext();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 13) {
              break;
            }

            message.ipv4 = reader.fixed32();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.ipv6 = reader.bytes();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.port = reader.uint32();
            continue;
          }
          case 4: {
            if (tag !== 33) {
              break;
            }

            message.routing_secret = reader.fixed64().toString();
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.protocol_version = reader.uint32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    },
  };

export interface MessageFns<T> {
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
