// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: steamnetworkingsockets_messages_udp.proto

/* eslint-disable */
import { BinaryReader } from "@bufbuild/protobuf/wire";
import {
  CMsgSteamDatagramConnectionQuality,
  CMsgSteamDatagramSessionCryptInfoSigned,
} from "./steamnetworkingsockets_messages.js";
import {
  CMsgSteamDatagramCertificateSigned,
  CMsgSteamNetworkingIdentityLegacyBinary,
} from "./steamnetworkingsockets_messages_certs.js";

export const protobufPackage = "";

export const ESteamNetworkingUDPMsgID = {
  k_ESteamNetworkingUDPMsg_ChallengeRequest: 32,
  k_ESteamNetworkingUDPMsg_ChallengeReply: 33,
  k_ESteamNetworkingUDPMsg_ConnectRequest: 34,
  k_ESteamNetworkingUDPMsg_ConnectOK: 35,
  k_ESteamNetworkingUDPMsg_ConnectionClosed: 36,
  k_ESteamNetworkingUDPMsg_NoConnection: 37,
  UNRECOGNIZED: -1,
} as const;

export type ESteamNetworkingUDPMsgID = typeof ESteamNetworkingUDPMsgID[keyof typeof ESteamNetworkingUDPMsgID];

export namespace ESteamNetworkingUDPMsgID {
  export type k_ESteamNetworkingUDPMsg_ChallengeRequest =
    typeof ESteamNetworkingUDPMsgID.k_ESteamNetworkingUDPMsg_ChallengeRequest;
  export type k_ESteamNetworkingUDPMsg_ChallengeReply =
    typeof ESteamNetworkingUDPMsgID.k_ESteamNetworkingUDPMsg_ChallengeReply;
  export type k_ESteamNetworkingUDPMsg_ConnectRequest =
    typeof ESteamNetworkingUDPMsgID.k_ESteamNetworkingUDPMsg_ConnectRequest;
  export type k_ESteamNetworkingUDPMsg_ConnectOK = typeof ESteamNetworkingUDPMsgID.k_ESteamNetworkingUDPMsg_ConnectOK;
  export type k_ESteamNetworkingUDPMsg_ConnectionClosed =
    typeof ESteamNetworkingUDPMsgID.k_ESteamNetworkingUDPMsg_ConnectionClosed;
  export type k_ESteamNetworkingUDPMsg_NoConnection =
    typeof ESteamNetworkingUDPMsgID.k_ESteamNetworkingUDPMsg_NoConnection;
  export type UNRECOGNIZED = typeof ESteamNetworkingUDPMsgID.UNRECOGNIZED;
}

export interface CMsgSteamSockets_UDP_ChallengeRequest {
  connection_id?: number | undefined;
  my_timestamp?: string | undefined;
  protocol_version?: number | undefined;
}

export interface CMsgSteamSockets_UDP_ChallengeReply {
  connection_id?: number | undefined;
  challenge?: string | undefined;
  your_timestamp?: string | undefined;
  protocol_version?: number | undefined;
}

export interface CMsgSteamSockets_UDP_ConnectRequest {
  client_connection_id?: number | undefined;
  challenge?: string | undefined;
  my_timestamp?: string | undefined;
  ping_est_ms?: number | undefined;
  crypt?: CMsgSteamDatagramSessionCryptInfoSigned | undefined;
  cert?: CMsgSteamDatagramCertificateSigned | undefined;
  legacy_protocol_version?: number | undefined;
  identity_string?: string | undefined;
  legacy_client_steam_id?: string | undefined;
  legacy_identity_binary?: CMsgSteamNetworkingIdentityLegacyBinary | undefined;
}

export interface CMsgSteamSockets_UDP_ConnectOK {
  client_connection_id?: number | undefined;
  server_connection_id?: number | undefined;
  your_timestamp?: string | undefined;
  delay_time_usec?: number | undefined;
  crypt?: CMsgSteamDatagramSessionCryptInfoSigned | undefined;
  cert?: CMsgSteamDatagramCertificateSigned | undefined;
  identity_string?: string | undefined;
  legacy_server_steam_id?: string | undefined;
  legacy_identity_binary?: CMsgSteamNetworkingIdentityLegacyBinary | undefined;
}

export interface CMsgSteamSockets_UDP_ConnectionClosed {
  to_connection_id?: number | undefined;
  from_connection_id?: number | undefined;
  debug?: string | undefined;
  reason_code?: number | undefined;
}

export interface CMsgSteamSockets_UDP_NoConnection {
  from_connection_id?: number | undefined;
  to_connection_id?: number | undefined;
}

export interface CMsgSteamSockets_UDP_Stats {
  stats?: CMsgSteamDatagramConnectionQuality | undefined;
  flags?: number | undefined;
}

export const CMsgSteamSockets_UDP_Stats_Flags = {
  ACK_REQUEST_E2E: 2,
  ACK_REQUEST_IMMEDIATE: 4,
  NOT_PRIMARY_TRANSPORT_E2E: 16,
  UNRECOGNIZED: -1,
} as const;

export type CMsgSteamSockets_UDP_Stats_Flags =
  typeof CMsgSteamSockets_UDP_Stats_Flags[keyof typeof CMsgSteamSockets_UDP_Stats_Flags];

export namespace CMsgSteamSockets_UDP_Stats_Flags {
  export type ACK_REQUEST_E2E = typeof CMsgSteamSockets_UDP_Stats_Flags.ACK_REQUEST_E2E;
  export type ACK_REQUEST_IMMEDIATE = typeof CMsgSteamSockets_UDP_Stats_Flags.ACK_REQUEST_IMMEDIATE;
  export type NOT_PRIMARY_TRANSPORT_E2E = typeof CMsgSteamSockets_UDP_Stats_Flags.NOT_PRIMARY_TRANSPORT_E2E;
  export type UNRECOGNIZED = typeof CMsgSteamSockets_UDP_Stats_Flags.UNRECOGNIZED;
}

function createBaseCMsgSteamSockets_UDP_ChallengeRequest(): CMsgSteamSockets_UDP_ChallengeRequest {
  return { connection_id: undefined, my_timestamp: undefined, protocol_version: undefined };
}

export const CMsgSteamSockets_UDP_ChallengeRequest: MessageFns<CMsgSteamSockets_UDP_ChallengeRequest> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamSockets_UDP_ChallengeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamSockets_UDP_ChallengeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.connection_id = reader.fixed32();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.my_timestamp = reader.fixed64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.protocol_version = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamSockets_UDP_ChallengeReply(): CMsgSteamSockets_UDP_ChallengeReply {
  return { connection_id: undefined, challenge: undefined, your_timestamp: undefined, protocol_version: undefined };
}

export const CMsgSteamSockets_UDP_ChallengeReply: MessageFns<CMsgSteamSockets_UDP_ChallengeReply> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamSockets_UDP_ChallengeReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamSockets_UDP_ChallengeReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.connection_id = reader.fixed32();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.challenge = reader.fixed64().toString();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.your_timestamp = reader.fixed64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.protocol_version = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamSockets_UDP_ConnectRequest(): CMsgSteamSockets_UDP_ConnectRequest {
  return {
    client_connection_id: undefined,
    challenge: undefined,
    my_timestamp: undefined,
    ping_est_ms: undefined,
    crypt: undefined,
    cert: undefined,
    legacy_protocol_version: undefined,
    identity_string: undefined,
    legacy_client_steam_id: undefined,
    legacy_identity_binary: undefined,
  };
}

export const CMsgSteamSockets_UDP_ConnectRequest: MessageFns<CMsgSteamSockets_UDP_ConnectRequest> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamSockets_UDP_ConnectRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamSockets_UDP_ConnectRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.client_connection_id = reader.fixed32();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.challenge = reader.fixed64().toString();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.my_timestamp = reader.fixed64().toString();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.ping_est_ms = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.crypt = CMsgSteamDatagramSessionCryptInfoSigned.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.cert = CMsgSteamDatagramCertificateSigned.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.legacy_protocol_version = reader.uint32();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.identity_string = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.legacy_client_steam_id = reader.fixed64().toString();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.legacy_identity_binary = CMsgSteamNetworkingIdentityLegacyBinary.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamSockets_UDP_ConnectOK(): CMsgSteamSockets_UDP_ConnectOK {
  return {
    client_connection_id: undefined,
    server_connection_id: undefined,
    your_timestamp: undefined,
    delay_time_usec: undefined,
    crypt: undefined,
    cert: undefined,
    identity_string: undefined,
    legacy_server_steam_id: undefined,
    legacy_identity_binary: undefined,
  };
}

export const CMsgSteamSockets_UDP_ConnectOK: MessageFns<CMsgSteamSockets_UDP_ConnectOK> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamSockets_UDP_ConnectOK {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamSockets_UDP_ConnectOK();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.client_connection_id = reader.fixed32();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.server_connection_id = reader.fixed32();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.your_timestamp = reader.fixed64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.delay_time_usec = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.crypt = CMsgSteamDatagramSessionCryptInfoSigned.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.cert = CMsgSteamDatagramCertificateSigned.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.identity_string = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.legacy_server_steam_id = reader.fixed64().toString();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.legacy_identity_binary = CMsgSteamNetworkingIdentityLegacyBinary.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamSockets_UDP_ConnectionClosed(): CMsgSteamSockets_UDP_ConnectionClosed {
  return { to_connection_id: undefined, from_connection_id: undefined, debug: undefined, reason_code: undefined };
}

export const CMsgSteamSockets_UDP_ConnectionClosed: MessageFns<CMsgSteamSockets_UDP_ConnectionClosed> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamSockets_UDP_ConnectionClosed {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamSockets_UDP_ConnectionClosed();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.to_connection_id = reader.fixed32();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.from_connection_id = reader.fixed32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.debug = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.reason_code = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamSockets_UDP_NoConnection(): CMsgSteamSockets_UDP_NoConnection {
  return { from_connection_id: undefined, to_connection_id: undefined };
}

export const CMsgSteamSockets_UDP_NoConnection: MessageFns<CMsgSteamSockets_UDP_NoConnection> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamSockets_UDP_NoConnection {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamSockets_UDP_NoConnection();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.from_connection_id = reader.fixed32();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.to_connection_id = reader.fixed32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamSockets_UDP_Stats(): CMsgSteamSockets_UDP_Stats {
  return { stats: undefined, flags: undefined };
}

export const CMsgSteamSockets_UDP_Stats: MessageFns<CMsgSteamSockets_UDP_Stats> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamSockets_UDP_Stats {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamSockets_UDP_Stats();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stats = CMsgSteamDatagramConnectionQuality.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.flags = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface MessageFns<T> {
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
