// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: steammessages_unified_base.steamworkssdk.proto

/* eslint-disable */

export const protobufPackage = "";

export const EProtoExecutionSite = {
  k_EProtoExecutionSiteUnknown: 0,
  k_EProtoExecutionSiteSteamClient: 3,
  UNRECOGNIZED: -1,
} as const;

export type EProtoExecutionSite = typeof EProtoExecutionSite[keyof typeof EProtoExecutionSite];

export namespace EProtoExecutionSite {
  export type k_EProtoExecutionSiteUnknown = typeof EProtoExecutionSite.k_EProtoExecutionSiteUnknown;
  export type k_EProtoExecutionSiteSteamClient = typeof EProtoExecutionSite.k_EProtoExecutionSiteSteamClient;
  export type UNRECOGNIZED = typeof EProtoExecutionSite.UNRECOGNIZED;
}
