// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: steamnetworkingsockets_messages_certs.proto

/* eslint-disable */
import { BinaryReader } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface CMsgSteamNetworkingIdentityLegacyBinary {
  steam_id?: string | undefined;
  generic_bytes?: Uint8Array | undefined;
  generic_string?: string | undefined;
  ipv6_and_port?: Uint8Array | undefined;
}

export interface CMsgSteamDatagramCertificate {
  key_type?: CMsgSteamDatagramCertificate_EKeyType | undefined;
  key_data?: Uint8Array | undefined;
  legacy_steam_id?: string | undefined;
  legacy_identity_binary?: CMsgSteamNetworkingIdentityLegacyBinary | undefined;
  identity_string?: string | undefined;
  gameserver_datacenter_ids: number[];
  time_created?: number | undefined;
  time_expiry?: number | undefined;
  app_ids: number[];
  ip_addresses: string[];
}

export const CMsgSteamDatagramCertificate_EKeyType = { INVALID: 0, ED25519: 1, UNRECOGNIZED: -1 } as const;

export type CMsgSteamDatagramCertificate_EKeyType =
  typeof CMsgSteamDatagramCertificate_EKeyType[keyof typeof CMsgSteamDatagramCertificate_EKeyType];

export namespace CMsgSteamDatagramCertificate_EKeyType {
  export type INVALID = typeof CMsgSteamDatagramCertificate_EKeyType.INVALID;
  export type ED25519 = typeof CMsgSteamDatagramCertificate_EKeyType.ED25519;
  export type UNRECOGNIZED = typeof CMsgSteamDatagramCertificate_EKeyType.UNRECOGNIZED;
}

export interface CMsgSteamDatagramCertificateSigned {
  cert?: Uint8Array | undefined;
  ca_key_id?: string | undefined;
  ca_signature?: Uint8Array | undefined;
  private_key_data?: Uint8Array | undefined;
}

export interface CMsgSteamDatagramCertificateRequest {
  cert?: CMsgSteamDatagramCertificate | undefined;
}

function createBaseCMsgSteamNetworkingIdentityLegacyBinary(): CMsgSteamNetworkingIdentityLegacyBinary {
  return { steam_id: undefined, generic_bytes: undefined, generic_string: undefined, ipv6_and_port: undefined };
}

export const CMsgSteamNetworkingIdentityLegacyBinary: MessageFns<CMsgSteamNetworkingIdentityLegacyBinary> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamNetworkingIdentityLegacyBinary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamNetworkingIdentityLegacyBinary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 16: {
          if (tag !== 129) {
            break;
          }

          message.steam_id = reader.fixed64().toString();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.generic_bytes = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.generic_string = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.ipv6_and_port = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamDatagramCertificate(): CMsgSteamDatagramCertificate {
  return {
    key_type: undefined,
    key_data: undefined,
    legacy_steam_id: undefined,
    legacy_identity_binary: undefined,
    identity_string: undefined,
    gameserver_datacenter_ids: [],
    time_created: undefined,
    time_expiry: undefined,
    app_ids: [],
    ip_addresses: [],
  };
}

export const CMsgSteamDatagramCertificate: MessageFns<CMsgSteamDatagramCertificate> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamDatagramCertificate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamDatagramCertificate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.key_type = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.key_data = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.legacy_steam_id = reader.fixed64().toString();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.legacy_identity_binary = CMsgSteamNetworkingIdentityLegacyBinary.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.identity_string = reader.string();
          continue;
        }
        case 5: {
          if (tag === 45) {
            message.gameserver_datacenter_ids.push(reader.fixed32());

            continue;
          }

          if (tag === 42) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.gameserver_datacenter_ids.push(reader.fixed32());
            }

            continue;
          }

          break;
        }
        case 8: {
          if (tag !== 69) {
            break;
          }

          message.time_created = reader.fixed32();
          continue;
        }
        case 9: {
          if (tag !== 77) {
            break;
          }

          message.time_expiry = reader.fixed32();
          continue;
        }
        case 10: {
          if (tag === 80) {
            message.app_ids.push(reader.uint32());

            continue;
          }

          if (tag === 82) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.app_ids.push(reader.uint32());
            }

            continue;
          }

          break;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.ip_addresses.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamDatagramCertificateSigned(): CMsgSteamDatagramCertificateSigned {
  return { cert: undefined, ca_key_id: undefined, ca_signature: undefined, private_key_data: undefined };
}

export const CMsgSteamDatagramCertificateSigned: MessageFns<CMsgSteamDatagramCertificateSigned> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamDatagramCertificateSigned {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamDatagramCertificateSigned();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.cert = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.ca_key_id = reader.fixed64().toString();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.ca_signature = reader.bytes();
          continue;
        }
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.private_key_data = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCMsgSteamDatagramCertificateRequest(): CMsgSteamDatagramCertificateRequest {
  return { cert: undefined };
}

export const CMsgSteamDatagramCertificateRequest: MessageFns<CMsgSteamDatagramCertificateRequest> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamDatagramCertificateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamDatagramCertificateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cert = CMsgSteamDatagramCertificate.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface MessageFns<T> {
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
