// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: steammessages_gamenetworkingui.proto

/* eslint-disable */
import { BinaryReader } from "@bufbuild/protobuf/wire";
import { CMsgSteamDatagramP2PRoutingSummary } from "./steamdatagram_messages_sdr.js";
import { CMsgSteamDatagramConnectionQuality } from "./steamnetworkingsockets_messages.js";

export const protobufPackage = "";

export interface CGameNetworkingUI_GlobalState {
}

export interface CGameNetworkingUI_ConnectionState {
  connection_key?: string | undefined;
  appid?: number | undefined;
  connection_id_local?: number | undefined;
  identity_local?: string | undefined;
  identity_remote?: string | undefined;
  connection_state?: number | undefined;
  start_time?: number | undefined;
  close_time?: number | undefined;
  close_reason?: number | undefined;
  close_message?: string | undefined;
  status_loc_token?: string | undefined;
  transport_kind?: number | undefined;
  sdrpopid_local?: string | undefined;
  sdrpopid_remote?: string | undefined;
  address_remote?: string | undefined;
  p2p_routing?: CMsgSteamDatagramP2PRoutingSummary | undefined;
  ping_interior?: number | undefined;
  ping_remote_front?: number | undefined;
  ping_default_internet_route?: number | undefined;
  e2e_quality_local?: CMsgSteamDatagramConnectionQuality | undefined;
  e2e_quality_remote?: CMsgSteamDatagramConnectionQuality | undefined;
  e2e_quality_remote_instantaneous_time?: string | undefined;
  e2e_quality_remote_lifetime_time?: string | undefined;
  front_quality_local?: CMsgSteamDatagramConnectionQuality | undefined;
  front_quality_remote?: CMsgSteamDatagramConnectionQuality | undefined;
  front_quality_remote_instantaneous_time?: string | undefined;
  front_quality_remote_lifetime_time?: string | undefined;
}

export interface CGameNetworkingUI_Message {
  connection_state: CGameNetworkingUI_ConnectionState[];
}

export interface CGameNetworkingUI_ConnectionSummary {
  transport_kind?: number | undefined;
  connection_state?: number | undefined;
  sdrpop_local?: string | undefined;
  sdrpop_remote?: string | undefined;
  ping_ms?: number | undefined;
  packet_loss?: number | undefined;
  ping_default_internet_route?: number | undefined;
  ip_was_shared?: boolean | undefined;
}

export interface CGameNetworkingUI_AppSummary {
  appid?: number | undefined;
  ip_was_shared_with_friend?: boolean | undefined;
  ip_was_shared_with_nonfriend?: boolean | undefined;
  active_connections?: number | undefined;
  main_cxn?: CGameNetworkingUI_ConnectionSummary | undefined;
}

function createBaseCGameNetworkingUI_GlobalState(): CGameNetworkingUI_GlobalState {
  return {};
}

export const CGameNetworkingUI_GlobalState: MessageFns<CGameNetworkingUI_GlobalState> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CGameNetworkingUI_GlobalState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCGameNetworkingUI_GlobalState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCGameNetworkingUI_ConnectionState(): CGameNetworkingUI_ConnectionState {
  return {
    connection_key: undefined,
    appid: undefined,
    connection_id_local: undefined,
    identity_local: undefined,
    identity_remote: undefined,
    connection_state: undefined,
    start_time: undefined,
    close_time: undefined,
    close_reason: undefined,
    close_message: undefined,
    status_loc_token: undefined,
    transport_kind: undefined,
    sdrpopid_local: undefined,
    sdrpopid_remote: undefined,
    address_remote: undefined,
    p2p_routing: undefined,
    ping_interior: undefined,
    ping_remote_front: undefined,
    ping_default_internet_route: undefined,
    e2e_quality_local: undefined,
    e2e_quality_remote: undefined,
    e2e_quality_remote_instantaneous_time: undefined,
    e2e_quality_remote_lifetime_time: undefined,
    front_quality_local: undefined,
    front_quality_remote: undefined,
    front_quality_remote_instantaneous_time: undefined,
    front_quality_remote_lifetime_time: undefined,
  };
}

export const CGameNetworkingUI_ConnectionState: MessageFns<CGameNetworkingUI_ConnectionState> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CGameNetworkingUI_ConnectionState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCGameNetworkingUI_ConnectionState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.connection_key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.appid = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.connection_id_local = reader.fixed32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.identity_local = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.identity_remote = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.connection_state = reader.uint32();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.start_time = reader.uint32();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.close_time = reader.uint32();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.close_reason = reader.uint32();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.close_message = reader.string();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.status_loc_token = reader.string();
          continue;
        }
        case 20: {
          if (tag !== 160) {
            break;
          }

          message.transport_kind = reader.uint32();
          continue;
        }
        case 21: {
          if (tag !== 170) {
            break;
          }

          message.sdrpopid_local = reader.string();
          continue;
        }
        case 22: {
          if (tag !== 178) {
            break;
          }

          message.sdrpopid_remote = reader.string();
          continue;
        }
        case 23: {
          if (tag !== 186) {
            break;
          }

          message.address_remote = reader.string();
          continue;
        }
        case 24: {
          if (tag !== 194) {
            break;
          }

          message.p2p_routing = CMsgSteamDatagramP2PRoutingSummary.decode(reader, reader.uint32());
          continue;
        }
        case 25: {
          if (tag !== 200) {
            break;
          }

          message.ping_interior = reader.uint32();
          continue;
        }
        case 26: {
          if (tag !== 208) {
            break;
          }

          message.ping_remote_front = reader.uint32();
          continue;
        }
        case 27: {
          if (tag !== 216) {
            break;
          }

          message.ping_default_internet_route = reader.uint32();
          continue;
        }
        case 30: {
          if (tag !== 242) {
            break;
          }

          message.e2e_quality_local = CMsgSteamDatagramConnectionQuality.decode(reader, reader.uint32());
          continue;
        }
        case 31: {
          if (tag !== 250) {
            break;
          }

          message.e2e_quality_remote = CMsgSteamDatagramConnectionQuality.decode(reader, reader.uint32());
          continue;
        }
        case 32: {
          if (tag !== 256) {
            break;
          }

          message.e2e_quality_remote_instantaneous_time = reader.uint64().toString();
          continue;
        }
        case 33: {
          if (tag !== 264) {
            break;
          }

          message.e2e_quality_remote_lifetime_time = reader.uint64().toString();
          continue;
        }
        case 40: {
          if (tag !== 322) {
            break;
          }

          message.front_quality_local = CMsgSteamDatagramConnectionQuality.decode(reader, reader.uint32());
          continue;
        }
        case 41: {
          if (tag !== 330) {
            break;
          }

          message.front_quality_remote = CMsgSteamDatagramConnectionQuality.decode(reader, reader.uint32());
          continue;
        }
        case 42: {
          if (tag !== 336) {
            break;
          }

          message.front_quality_remote_instantaneous_time = reader.uint64().toString();
          continue;
        }
        case 43: {
          if (tag !== 344) {
            break;
          }

          message.front_quality_remote_lifetime_time = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCGameNetworkingUI_Message(): CGameNetworkingUI_Message {
  return { connection_state: [] };
}

export const CGameNetworkingUI_Message: MessageFns<CGameNetworkingUI_Message> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CGameNetworkingUI_Message {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCGameNetworkingUI_Message();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.connection_state.push(CGameNetworkingUI_ConnectionState.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCGameNetworkingUI_ConnectionSummary(): CGameNetworkingUI_ConnectionSummary {
  return {
    transport_kind: undefined,
    connection_state: undefined,
    sdrpop_local: undefined,
    sdrpop_remote: undefined,
    ping_ms: undefined,
    packet_loss: undefined,
    ping_default_internet_route: undefined,
    ip_was_shared: undefined,
  };
}

export const CGameNetworkingUI_ConnectionSummary: MessageFns<CGameNetworkingUI_ConnectionSummary> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CGameNetworkingUI_ConnectionSummary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCGameNetworkingUI_ConnectionSummary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.transport_kind = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.connection_state = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sdrpop_local = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sdrpop_remote = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.ping_ms = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.packet_loss = reader.float();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.ping_default_internet_route = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.ip_was_shared = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCGameNetworkingUI_AppSummary(): CGameNetworkingUI_AppSummary {
  return {
    appid: undefined,
    ip_was_shared_with_friend: undefined,
    ip_was_shared_with_nonfriend: undefined,
    active_connections: undefined,
    main_cxn: undefined,
  };
}

export const CGameNetworkingUI_AppSummary: MessageFns<CGameNetworkingUI_AppSummary> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CGameNetworkingUI_AppSummary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCGameNetworkingUI_AppSummary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.appid = reader.uint32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.ip_was_shared_with_friend = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.ip_was_shared_with_nonfriend = reader.bool();
          continue;
        }
        case 20: {
          if (tag !== 160) {
            break;
          }

          message.active_connections = reader.uint32();
          continue;
        }
        case 30: {
          if (tag !== 242) {
            break;
          }

          message.main_cxn = CGameNetworkingUI_ConnectionSummary.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface MessageFns<T> {
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
