// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: usercmd.proto

/* eslint-disable */
import { BinaryReader } from "@bufbuild/protobuf/wire";
import { CMsgQAngle } from "./networkbasetypes.js";

export const protobufPackage = "";

export interface CInButtonStatePB {
  buttonstate1?: string | undefined;
  buttonstate2?: string | undefined;
  buttonstate3?: string | undefined;
}

export interface CSubtickMoveStep {
  button?: string | undefined;
  pressed?: boolean | undefined;
  when?: number | undefined;
  analog_forward_delta?: number | undefined;
  analog_left_delta?: number | undefined;
  pitch_delta?: number | undefined;
  yaw_delta?: number | undefined;
}

export interface CBaseUserCmdExecutionNotes {
  ignored_reason?: string | undefined;
}

export interface CBaseUserCmdPB {
  legacy_command_number?: number | undefined;
  client_tick?: number | undefined;
  prediction_offset_ticks_x256?: number | undefined;
  buttons_pb?: CInButtonStatePB | undefined;
  viewangles?: CMsgQAngle | undefined;
  forwardmove?: number | undefined;
  leftmove?: number | undefined;
  upmove?: number | undefined;
  impulse?: number | undefined;
  weaponselect?: number | undefined;
  random_seed?: number | undefined;
  mousedx?: number | undefined;
  mousedy?: number | undefined;
  pawn_entity_handle?: number | undefined;
  subtick_moves: CSubtickMoveStep[];
  move_crc?: Uint8Array | undefined;
  consumed_server_angle_changes?: number | undefined;
  cmd_flags?: number | undefined;
  execution_notes?: CBaseUserCmdExecutionNotes | undefined;
}

export interface CUserCmdBasePB {
  base?: CBaseUserCmdPB | undefined;
}

function createBaseCInButtonStatePB(): CInButtonStatePB {
  return { buttonstate1: undefined, buttonstate2: undefined, buttonstate3: undefined };
}

export const CInButtonStatePB: MessageFns<CInButtonStatePB> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CInButtonStatePB {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCInButtonStatePB();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.buttonstate1 = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.buttonstate2 = reader.uint64().toString();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.buttonstate3 = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCSubtickMoveStep(): CSubtickMoveStep {
  return {
    button: undefined,
    pressed: undefined,
    when: undefined,
    analog_forward_delta: undefined,
    analog_left_delta: undefined,
    pitch_delta: undefined,
    yaw_delta: undefined,
  };
}

export const CSubtickMoveStep: MessageFns<CSubtickMoveStep> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CSubtickMoveStep {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCSubtickMoveStep();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.button = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pressed = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.when = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.analog_forward_delta = reader.float();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.analog_left_delta = reader.float();
          continue;
        }
        case 8: {
          if (tag !== 69) {
            break;
          }

          message.pitch_delta = reader.float();
          continue;
        }
        case 9: {
          if (tag !== 77) {
            break;
          }

          message.yaw_delta = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCBaseUserCmdExecutionNotes(): CBaseUserCmdExecutionNotes {
  return { ignored_reason: undefined };
}

export const CBaseUserCmdExecutionNotes: MessageFns<CBaseUserCmdExecutionNotes> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CBaseUserCmdExecutionNotes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCBaseUserCmdExecutionNotes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ignored_reason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCBaseUserCmdPB(): CBaseUserCmdPB {
  return {
    legacy_command_number: undefined,
    client_tick: undefined,
    prediction_offset_ticks_x256: undefined,
    buttons_pb: undefined,
    viewangles: undefined,
    forwardmove: undefined,
    leftmove: undefined,
    upmove: undefined,
    impulse: undefined,
    weaponselect: undefined,
    random_seed: undefined,
    mousedx: undefined,
    mousedy: undefined,
    pawn_entity_handle: undefined,
    subtick_moves: [],
    move_crc: undefined,
    consumed_server_angle_changes: undefined,
    cmd_flags: undefined,
    execution_notes: undefined,
  };
}

export const CBaseUserCmdPB: MessageFns<CBaseUserCmdPB> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CBaseUserCmdPB {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCBaseUserCmdPB();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.legacy_command_number = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.client_tick = reader.int32();
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.prediction_offset_ticks_x256 = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.buttons_pb = CInButtonStatePB.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.viewangles = CMsgQAngle.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.forwardmove = reader.float();
          continue;
        }
        case 6: {
          if (tag !== 53) {
            break;
          }

          message.leftmove = reader.float();
          continue;
        }
        case 7: {
          if (tag !== 61) {
            break;
          }

          message.upmove = reader.float();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.impulse = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.weaponselect = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.random_seed = reader.int32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.mousedx = reader.int32();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.mousedy = reader.int32();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.pawn_entity_handle = reader.uint32();
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          message.subtick_moves.push(CSubtickMoveStep.decode(reader, reader.uint32()));
          continue;
        }
        case 19: {
          if (tag !== 154) {
            break;
          }

          message.move_crc = reader.bytes();
          continue;
        }
        case 20: {
          if (tag !== 160) {
            break;
          }

          message.consumed_server_angle_changes = reader.uint32();
          continue;
        }
        case 21: {
          if (tag !== 168) {
            break;
          }

          message.cmd_flags = reader.int32();
          continue;
        }
        case 22: {
          if (tag !== 178) {
            break;
          }

          message.execution_notes = CBaseUserCmdExecutionNotes.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCUserCmdBasePB(): CUserCmdBasePB {
  return { base: undefined };
}

export const CUserCmdBasePB: MessageFns<CUserCmdBasePB> = {
  decode(input: BinaryReader | Uint8Array, length?: number): CUserCmdBasePB {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCUserCmdBasePB();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.base = CBaseUserCmdPB.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface MessageFns<T> {
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
