// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: valveextensions.proto

/* eslint-disable */

export const protobufPackage = "";

export const EProtoDebugVisiblity = {
  k_EProtoDebugVisibility_Always: 0,
  k_EProtoDebugVisibility_Server: 70,
  k_EProtoDebugVisibility_ValveServer: 80,
  k_EProtoDebugVisibility_GC: 90,
  k_EProtoDebugVisibility_Never: 100,
  UNRECOGNIZED: -1,
} as const;

export type EProtoDebugVisiblity = typeof EProtoDebugVisiblity[keyof typeof EProtoDebugVisiblity];

export namespace EProtoDebugVisiblity {
  export type k_EProtoDebugVisibility_Always = typeof EProtoDebugVisiblity.k_EProtoDebugVisibility_Always;
  export type k_EProtoDebugVisibility_Server = typeof EProtoDebugVisiblity.k_EProtoDebugVisibility_Server;
  export type k_EProtoDebugVisibility_ValveServer = typeof EProtoDebugVisiblity.k_EProtoDebugVisibility_ValveServer;
  export type k_EProtoDebugVisibility_GC = typeof EProtoDebugVisiblity.k_EProtoDebugVisibility_GC;
  export type k_EProtoDebugVisibility_Never = typeof EProtoDebugVisiblity.k_EProtoDebugVisibility_Never;
  export type UNRECOGNIZED = typeof EProtoDebugVisiblity.UNRECOGNIZED;
}
