#![deny(clippy::all)]
#![allow(clippy::new_without_default)]

use napi::bindgen_prelude::{BigInt, BigInt64Array, Error, Float64Array, Uint8Array};
use napi_derive::napi;
use prost::Message;

/// Generated by `prost-build` from `src/proto/*.proto`. Top-level module name
/// is the default `_` because our protos have no `package` declaration.
#[allow(clippy::all, non_camel_case_types, non_snake_case, dead_code)]
mod proto {
	include!(concat!(env!("OUT_DIR"), "/_.rs"));
}

mod bitbuffer;
mod classinfo;
mod entity_parser;
mod fieldpath;
mod frame_loop;
mod quantized_float;
mod string_tables;
use bitbuffer::BitBuffer;
use classinfo::{parse_class_info, ClassInfo};
use entity_parser::{DecodeResult, EntityState};
use fieldpath::FieldPath;
use frame_loop::FrameLoop;
use napi::bindgen_prelude::Buffer;
use quantized_float::{get_quantized_float, QuantizedFloat};
use std::collections::HashMap;

/// Phase 0 smoke test: importable from JS, returns a constant string.
/// Real entity-decoder surface lands in later phases.
#[napi]
pub fn ping() -> &'static str {
	"pong"
}

/// Phase 1 parity probe — decode a captured `CSVCMsg_FlattenedSerializer`
/// blob with prost and return structural counts. The JS test compares these
/// against the ts-proto decode of the same bytes.
#[napi(object)]
pub struct FlattenedSerializerSummary {
	pub symbols: u32,
	pub fields: u32,
	pub serializers: u32,
}

#[napi]
pub fn decode_flattened_serializer_summary(bytes: &[u8]) -> Result<FlattenedSerializerSummary, Error> {
	let msg = proto::CsvcMsgFlattenedSerializer::decode(bytes)
		.map_err(|e| Error::from_reason(format!("prost decode failed: {e}")))?;
	Ok(FlattenedSerializerSummary {
		symbols: msg.symbols.len() as u32,
		fields: msg.fields.len() as u32,
		serializers: msg.serializers.len() as u32,
	})
}

/// Phase 2: napi wrapper around the Rust `BitBuffer`. Exposes the same surface
/// as `src/parser/ubitreader.ts` so the JS test suite can run side-by-side
/// against both implementations. Removed once the hot path is fully on Rust
/// (Phase 7); not part of the public package API.
#[napi(js_name = "BitBufferNative")]
pub struct BitBufferNative {
	inner: BitBuffer,
}

#[napi]
impl BitBufferNative {
	#[napi(constructor)]
	pub fn new(buffer: Uint8Array) -> Self {
		Self { inner: BitBuffer::new(buffer.to_vec()) }
	}

	#[napi]
	pub fn set_to(&mut self, buffer: Uint8Array) {
		self.inner.set_to(buffer.to_vec());
	}

	#[napi(getter, js_name = "RemainingBits")]
	pub fn remaining_bits(&self) -> u32 {
		self.inner.remaining_bits()
	}

	#[napi(getter, js_name = "RemainingBytes")]
	pub fn remaining_bytes(&self) -> u32 {
		self.inner.remaining_bytes()
	}

	#[napi(js_name = "ReadUBits")]
	pub fn read_ubits(&mut self, num_bits: u32) -> u32 {
		self.inner.read_ubits(num_bits)
	}

	#[napi(js_name = "PeekUBitsWithLog")]
	pub fn peek_ubits_with_log(&self, num_bits: u32) -> u32 {
		self.inner.peek_ubits_with_log(num_bits)
	}

	#[napi]
	pub fn consume_peeked(&mut self, num_bits: u32) {
		self.inner.consume_peeked(num_bits);
	}

	#[napi]
	pub fn read_boolean(&mut self) -> bool {
		self.inner.read_boolean()
	}

	#[napi(js_name = "ReadByte")]
	pub fn read_byte(&mut self) -> u32 {
		self.inner.read_byte()
	}

	#[napi(js_name = "readFloat32LE")]
	pub fn read_float32_le(&mut self) -> f64 {
		self.inner.read_float32_le() as f64
	}

	#[napi(js_name = "ReadUVarInt32")]
	pub fn read_uvarint32(&mut self) -> u32 {
		self.inner.read_uvarint32()
	}

	#[napi]
	pub fn read_ubit_var(&mut self) -> u32 {
		self.inner.read_ubit_var()
	}

	#[napi]
	pub fn read_ubit_var_fp(&mut self) -> u32 {
		self.inner.read_ubit_var_fp()
	}

	#[napi(js_name = "readVarInt32")]
	pub fn read_varint32(&mut self) -> i32 {
		self.inner.read_varint32()
	}

	#[napi(js_name = "readUVarInt64")]
	pub fn read_uvarint64(&mut self) -> BigInt {
		BigInt::from(self.inner.read_uvarint64())
	}

	#[napi(js_name = "decudeUint64")]
	pub fn decode_uint64(&mut self) -> BigInt {
		BigInt::from(self.inner.decode_uint64())
	}

	#[napi(js_name = "decode_noscale")]
	pub fn decode_noscale(&mut self) -> u32 {
		self.inner.decode_noscale()
	}

	#[napi(js_name = "decodeVectorNoScale")]
	pub fn decode_vector_noscale(&mut self) -> Vec<f64> {
		self.inner.decode_vector_noscale().to_vec()
	}

	#[napi]
	pub fn decode_qangle_all3(&mut self) -> Vec<f64> {
		self.inner.decode_qangle_all3().to_vec()
	}

	#[napi]
	pub fn decode_qangle_pitch_yaw(&mut self) -> Vec<f64> {
		self.inner.decode_qangle_pitch_yaw().to_vec()
	}

	#[napi]
	pub fn decode_float_coord(&mut self) -> f64 {
		self.inner.decode_float_coord() as f64
	}

	#[napi]
	pub fn decode_vector_float_coord(&mut self) -> Vec<f64> {
		self.inner.decode_vector_float_coord().to_vec()
	}

	#[napi]
	pub fn read_bit_coord(&mut self) -> f64 {
		self.inner.read_bit_coord() as f64
	}

	#[napi]
	pub fn read_bit_coord_pres(&mut self) -> f64 {
		self.inner.read_bit_coord_pres() as f64
	}

	#[napi]
	pub fn read_angle(&mut self, n: u32) -> f64 {
		self.inner.read_angle(n)
	}

	#[napi]
	pub fn decode_ammo(&mut self) -> u32 {
		self.inner.decode_ammo()
	}

	#[napi]
	pub fn decode_normal(&mut self) -> f64 {
		self.inner.decode_normal() as f64
	}

	#[napi]
	pub fn decode_normal_vec(&mut self) -> Vec<f64> {
		self.inner.decode_normal_vec().to_vec()
	}

	#[napi]
	pub fn decode_qangle_variant(&mut self) -> Vec<f64> {
		self.inner.decode_qangle_variant().to_vec()
	}

	#[napi]
	pub fn decode_qangle_variant_pres(&mut self) -> Vec<f64> {
		self.inner.decode_qangle_variant_pres().to_vec()
	}

	#[napi]
	pub fn skip_bytes_better(&mut self, bytes: u32) {
		self.inner.skip_bytes_better(bytes);
	}

	/// Reads `len` bytes from the bit stream and returns them as a fresh
	/// Uint8Array. The production decoder never crosses the FFI boundary for
	/// per-field byte reads (those happen inside Rust), so this allocation-on-
	/// every-call shape is fine — it only exists for the Phase 2 parity test.
	#[napi]
	pub fn read_bytes(&mut self, len: u32) -> Vec<u8> {
		let mut out = vec![0u8; len as usize];
		self.inner.read_bytes_into(&mut out);
		out
	}

	#[napi]
	pub fn read_bytes_to_slice(&mut self, size: u32) -> Vec<u8> {
		let mut out = vec![0u8; size as usize];
		self.inner.read_bytes_into(&mut out);
		out
	}

	#[napi]
	pub fn read_string(&mut self) -> String {
		self.inner.read_string()
	}
}

/// Phase 3: napi wrapper around the Rust `FieldPath`. Like BitBufferNative,
/// this only exists so the existing `fieldPathOps.test.ts` can drive the Rust
/// port. Goes away in Phase 7.
#[napi(js_name = "FieldPathNative")]
pub struct FieldPathNative {
	inner: FieldPath,
}

#[napi]
impl FieldPathNative {
	/// `path` defaults to `[0;7]` and `last` to `0` (matches the JS test's
	/// `makeFieldPath`, not the `parsePaths` initial state which uses -1).
	#[napi(constructor)]
	pub fn new(path: Option<Vec<i32>>, last: Option<i32>) -> Self {
		let mut fp = FieldPath { path: [0; 7], last: 0 };
		if let Some(p) = path {
			for (i, v) in p.iter().enumerate().take(7) {
				fp.path[i] = *v;
			}
		}
		fp.last = last.unwrap_or(0);
		Self { inner: fp }
	}

	#[napi(getter)]
	pub fn path(&self) -> Vec<i32> {
		self.inner.path.to_vec()
	}

	#[napi(getter)]
	pub fn last(&self) -> i32 {
		self.inner.last
	}
}

/// Apply one Huffman-decoded opcode (0..=39) to `fp`, reading any operand bits
/// from `br`. Opcode 39 is the no-op end-of-stream marker; ≥40 throws.
#[napi(js_name = "doOp")]
pub fn do_op_napi(opcode: u32, br: &mut BitBufferNative, fp: &mut FieldPathNative) -> Result<(), Error> {
	fieldpath::do_op(opcode, &mut br.inner, &mut fp.inner).map_err(Error::from_reason)
}

#[napi(js_name = "popSpecial")]
pub fn pop_special_napi(fp: &mut FieldPathNative, n: i32) {
	fieldpath::pop_special(&mut fp.inner, n);
}

/// Phase 4: napi wrapper for the QuantizedFloat setup function. Test-only —
/// the production path constructs QuantizedFloat directly from classInfo.
#[napi(object)]
pub struct QuantizedFloatJs {
	pub low: f64,
	pub high: f64,
	pub high_low_mul: f64,
	pub dec_mul: f64,
	pub offset: f64,
	pub bit_count: u32,
	pub flags: u32,
	pub no_scale: bool,
}

impl From<QuantizedFloat> for QuantizedFloatJs {
	fn from(qf: QuantizedFloat) -> Self {
		Self {
			low: qf.low as f64,
			high: qf.high as f64,
			high_low_mul: qf.high_low_mul as f64,
			dec_mul: qf.dec_mul as f64,
			offset: qf.offset as f64,
			bit_count: qf.bit_count,
			flags: qf.flags,
			no_scale: qf.no_scale,
		}
	}
}

#[napi(js_name = "getQuantalizedFloat")]
pub fn get_quantalized_float_napi(
	bitcount: u32,
	flags: Option<u32>,
	low_value: Option<f64>,
	high_value: Option<f64>,
) -> QuantizedFloatJs {
	let qf = get_quantized_float(bitcount, flags, low_value.map(|v| v as f32), high_value.map(|v| v as f32));
	qf.into()
}

// ─── Phase 5+: EntityDecoderNative umbrella ──────────────────────────────────
//
// One instance per `DemoReader`. Owns classInfo, qf table, propIdToName /
// propIdToDecoder maps (Phase 5); baselines, entity state, decode buffers
// (Phase 6); the result struct-of-arrays (Phase 6).

#[napi(object)]
pub struct ClassInfoMeta {
	/// `Record<number, string>` — prop id → fully-qualified property name.
	pub prop_id_to_name: HashMap<String, String>,
	/// Symbolic decoder ID per prop id. Mirrors the JS `propIdToDecoder` map
	/// shape: numbers or `{ type: 0, decoder: idx }` for quantized floats.
	/// The numeric value matches the `Decoders.*` constants in
	/// `src/parser/entities/constructorFields.ts`.
	pub prop_id_to_decoder: HashMap<String, i32>,
	/// Count of classes registered. JS uses this only for logging.
	pub class_count: u32,
}

/// Per-packet result struct returned to JS. Mirror of `entity_parser::DecodeResult`
/// with napi-friendly types.
///
/// 9a/note: numeric pools are typed arrays, not `Vec<T>`. `Vec<f64>` crosses
/// the FFI boundary as `Array<number>` with per-element boxing; `Float64Array`
/// transfers a single contiguous buffer (~10x faster on the JS side).
#[napi(object)]
pub struct DecodeResultJs {
	pub ops: Buffer,
	pub op_count: u32,
	pub f64_values: Float64Array,
	/// u64 bits reinterpreted as i64 (BigInt64Array transfers without boxing;
	/// JS reads them as the same numeric value as `BigInt::from(u64)` would
	/// produce when the high bit is unset, and as the negative two's-complement
	/// equivalent otherwise — callers that need the unsigned interpretation
	/// can use `BigInt.asUintN(64, x)`).
	pub bigint_values: BigInt64Array,
	pub strings: Vec<String>,
	pub blobs: Vec<Buffer>,
	pub class_names: Vec<String>,
	/// Set by `feed_chunk` when Rust paused at a tick boundary and the caller
	/// should drain by calling `feed_chunk(empty, …)` again. Always false
	/// for `finish_stream`.
	pub has_more: bool,
}

#[napi]
pub struct EntityDecoderNative {
	class_info: Option<ClassInfo>,
	state: EntityState,
	scratch: DecodeResult,
	frame_loop: FrameLoop,
}

#[napi]
impl EntityDecoderNative {
	#[napi(constructor)]
	pub fn new() -> Self {
		Self {
			class_info: None,
			state: EntityState::new(),
			scratch: DecodeResult::default(),
			frame_loop: FrameLoop::new(),
		}
	}

	/// Stage 4 entry point: feed a chunk of demo bytes; Rust accumulates,
	/// walks frames, snappy-decompresses, dispatches SVC messages, runs the
	/// entity decoder, and returns the events emitted during processing.
	///
	/// `only_game_rules` is honoured the first time DEM_ClassInfo is observed;
	/// after that initial setup, the value is locked for the parse.
	///
	/// Returns the events emitted while processing the chunk. If the result's
	/// `has_more` field is `true`, the caller must drain by calling
	/// `feed_chunk` again with an empty slice — Rust paused at a tick
	/// boundary to let JS dispatch events with entity state at the previous
	/// tick (required for correct gameevent listener semantics).
	#[napi]
	pub fn feed_chunk(
		&mut self,
		bytes: &[u8],
		only_game_rules: bool,
		skip_entities: bool,
	) -> Result<DecodeResultJs, Error> {
		self.frame_loop.only_game_rules = only_game_rules;
		self.frame_loop.skip_entities = skip_entities;
		self.scratch.reset();
		let has_more = self.frame_loop.feed_chunk(bytes, &mut self.class_info, &mut self.state, &mut self.scratch);
		let mut r = self.take_result();
		r.has_more = has_more;
		Ok(r)
	}

	/// Signal end of input. Returns any final events (e.g. trailing tickend).
	#[napi]
	pub fn finish_stream(&mut self) -> Result<DecodeResultJs, Error> {
		self.scratch.reset();
		self.frame_loop.finish_stream(&mut self.class_info, &mut self.state, &mut self.scratch);
		Ok(self.take_result())
	}

	/// Build the v1-style ClassInfoMeta from the most recent class_info init.
	/// Returns `None` if DEM_ClassInfo hasn't been observed yet.
	#[napi]
	pub fn class_info_meta(&self) -> Option<ClassInfoMeta> {
		let ci = self.class_info.as_ref()?;
		Some(ClassInfoMeta {
			prop_id_to_name: ci.prop_id_to_name.iter().map(|(k, v)| (k.to_string(), v.clone())).collect(),
			prop_id_to_decoder: ci
				.prop_id_to_decoder
				.iter()
				.map(|(k, d)| (k.to_string(), decoder_to_id(*d)))
				.collect(),
			class_count: ci.classes.len() as u32,
		})
	}

	fn take_result(&mut self) -> DecodeResultJs {
		let r = std::mem::take(&mut self.scratch);
		DecodeResultJs {
			ops: Buffer::from(r.ops),
			op_count: r.op_count,
			f64_values: napi::bindgen_prelude::Float64Array::new(r.f64_values),
			bigint_values: napi::bindgen_prelude::BigInt64Array::new(r.bigint_values),
			strings: r.strings,
			blobs: r.blobs.into_iter().map(Buffer::from).collect(),
			class_names: r.class_names,
			has_more: false,
		}
	}

	/// Build the class tree from the inner CSVCMsg_FlattenedSerializer bytes
	/// (already extracted from `CDemoSendTables.data` by JS) and CDemoClassInfo
	/// bytes. Returns the prop-id maps for JS to mirror.
	#[napi]
	pub fn init_class_info(
		&mut self,
		send_tables_inner: &[u8],
		class_info_bytes: &[u8],
		only_game_rules: bool,
	) -> Result<ClassInfoMeta, Error> {
		let ci = parse_class_info(send_tables_inner, class_info_bytes).map_err(Error::from_reason)?;
		let meta = ClassInfoMeta {
			prop_id_to_name: ci.prop_id_to_name.iter().map(|(k, v)| (k.to_string(), v.clone())).collect(),
			prop_id_to_decoder: ci
				.prop_id_to_decoder
				.iter()
				.map(|(k, d)| (k.to_string(), decoder_to_id(*d)))
				.collect(),
			class_count: ci.classes.len() as u32,
		};
		self.class_info = Some(ci);
		self.state.only_game_rules = only_game_rules;
		Ok(meta)
	}

	/// Push a baseline blob for `class_id` (called by JS whenever a
	/// string-table update changes the `instancebaseline` entry).
	#[napi]
	pub fn set_baseline(&mut self, class_id: u32, data: &[u8]) {
		self.state.baselines.insert(class_id, data.to_vec());
	}

	/// Decode one CSVCMsg_PacketEntities payload. Returns the batched ops for
	/// JS to apply to its entities array + emit events from.
	#[napi]
	pub fn parse_entity_packet(
		&mut self,
		entity_data: &[u8],
		updated_entries: u32,
		has_pvs_vis_bits: u32,
	) -> Result<DecodeResultJs, Error> {
		let class_info = self
			.class_info
			.as_ref()
			.ok_or_else(|| Error::from_reason("init_class_info must be called before parse_entity_packet"))?;

		self.scratch.reset();
		self.state.parse_entity_packet(entity_data, updated_entries, has_pvs_vis_bits, class_info, &mut self.scratch);

		Ok(self.take_result())
	}

	/// Reset entity state between parses (JS calls when a new `parseDemo` starts).
	#[napi]
	pub fn reset(&mut self) {
		self.state.reset();
	}

	// ─── v2 getter API ──────────────────────────────────────────────────────
	// Stage 1: parallel to the existing DecodeResult emission. Reads come from
	// the Rust-resident `EntityState.entities` table populated during decode.

	/// Returns `true` if an entity with this id is currently live.
	#[napi]
	pub fn has_entity(&self, entity_id: u32) -> bool {
		self.state.entities.get(entity_id as usize).and_then(|e| e.as_ref()).is_some()
	}

	#[napi]
	pub fn get_entity_class_id(&self, entity_id: u32) -> Option<u32> {
		self.state.entities.get(entity_id as usize).and_then(|e| e.as_ref()).map(|r| r.class_id)
	}

	#[napi]
	pub fn get_entity_class_name(&self, entity_id: u32) -> Option<String> {
		self.state.entities.get(entity_id as usize).and_then(|e| e.as_ref()).map(|r| r.class_name.clone())
	}

	#[napi]
	pub fn get_entity_type(&self, entity_id: u32) -> Option<u32> {
		self.state.entities.get(entity_id as usize).and_then(|e| e.as_ref()).map(|r| r.entity_type as u32)
	}

	/// List every live entity id.
	#[napi]
	pub fn get_entity_ids(&self) -> Vec<u32> {
		self.state
			.entities
			.iter()
			.enumerate()
			.filter_map(|(i, r)| r.as_ref().map(|_| i as u32))
			.collect()
	}

	/// List live entities whose class_name matches `class_name`. Used by the
	/// JS `findEntityIdsByClass` getter and `parser.playerControllers` /
	/// `parser.teams`.
	#[napi]
	pub fn find_entity_ids_by_class(&self, class_name: String) -> Vec<u32> {
		self.state
			.entities
			.iter()
			.enumerate()
			.filter_map(|(i, r)| match r {
				Some(rec) if rec.class_name == class_name => Some(i as u32),
				_ => None,
			})
			.collect()
	}

	// Typed property getters. The JS side caches prop_id by name (built once
	// from `initClassInfo`'s returned `propIdToName`), so each helper read is
	// a single HashMap probe + one FFI call.

	#[napi]
	pub fn get_property_bool(&self, entity_id: u32, prop_id: u32) -> Option<bool> {
		match self.state.entities.get(entity_id as usize)?.as_ref()?.properties.get(&prop_id)? {
			entity_parser::Value::Bool(b) => Some(*b),
			_ => None,
		}
	}

	/// Number-typed read. Boolean/i32/u32/f32 widen to f64; vec3/u64/string/blob return None.
	#[napi]
	pub fn get_property_number(&self, entity_id: u32, prop_id: u32) -> Option<f64> {
		use entity_parser::Value::*;
		match self.state.entities.get(entity_id as usize)?.as_ref()?.properties.get(&prop_id)? {
			Bool(b) => Some(if *b { 1.0 } else { 0.0 }),
			I32(n) => Some(*n as f64),
			U32(n) => Some(*n as f64),
			F32(n) => Some(*n as f64),
			_ => None,
		}
	}

	#[napi]
	pub fn get_property_string(&self, entity_id: u32, prop_id: u32) -> Option<String> {
		match self.state.entities.get(entity_id as usize)?.as_ref()?.properties.get(&prop_id)? {
			entity_parser::Value::String(s) => Some(s.clone()),
			_ => None,
		}
	}

	#[napi]
	pub fn get_property_vec3(&self, entity_id: u32, prop_id: u32) -> Option<Float64Array> {
		match self.state.entities.get(entity_id as usize)?.as_ref()?.properties.get(&prop_id)? {
			entity_parser::Value::Vec3(v) => Some(Float64Array::new(v.to_vec())),
			_ => None,
		}
	}

	#[napi]
	pub fn get_property_bigint(&self, entity_id: u32, prop_id: u32) -> Option<BigInt> {
		match self.state.entities.get(entity_id as usize)?.as_ref()?.properties.get(&prop_id)? {
			entity_parser::Value::U64(u) => Some(BigInt::from(*u)),
			_ => None,
		}
	}

	#[napi]
	pub fn get_property_blob(&self, entity_id: u32, prop_id: u32) -> Option<Buffer> {
		match self.state.entities.get(entity_id as usize)?.as_ref()?.properties.get(&prop_id)? {
			entity_parser::Value::Blob(b) => Some(Buffer::from(b.clone())),
			_ => None,
		}
	}

	/// Returns `true` if the entity has a registered value for `prop_id`. Lets
	/// JS distinguish "missing" from "default value".
	#[napi]
	pub fn has_property(&self, entity_id: u32, prop_id: u32) -> bool {
		self.state
			.entities
			.get(entity_id as usize)
			.and_then(|e| e.as_ref())
			.map(|r| r.properties.contains_key(&prop_id))
			.unwrap_or(false)
	}

	/// List every prop_id currently set on this entity. JS uses
	/// `propIdToName` to resolve names, then per-id typed getters for values.
	/// Used by `parser.getEntity(id)` to build the snapshot object.
	#[napi]
	pub fn get_entity_prop_ids(&self, entity_id: u32) -> Option<Vec<u32>> {
		let ent = self.state.entities.get(entity_id as usize)?.as_ref()?;
		Some(ent.properties.keys().copied().collect())
	}
}

/// Maps Rust `Decoder` enum to the integer IDs declared in
/// `src/parser/entities/constructorFields.ts` (D_QUANTALIZED_FLOAT=0,
/// D_VECTOR_NORMAL=1, ...). Quantized floats return -1 as a sentinel
/// (JS represents them as an object, not a number); JS-side consumers
/// of `propIdToDecoder` already cope with either.
fn decoder_to_id(d: classinfo::Decoder) -> i32 {
	use classinfo::Decoder::*;
	match d {
		QuantizedFloat(_) => 0,
		VectorNormal => 1,
		VectorNoScale => 2,
		VectorFloatCoord => 3,
		Unsigned64 => 4,
		CentityHandle => 5,
		NoScale => 6,
		Boolean => 7,
		String => 8,
		Signed => 9,
		Unsigned => 10,
		Component => 11,
		FloatCoord => 12,
		FloatSimulationTime => 13,
		Fixed64 => 14,
		QanglePitchYaw => 15,
		Qangle3 => 16,
		QangleVar => 17,
		Base => 18,
		Ammo => 19,
		QanglePres => 20,
		GameModeRules => 21,
		BinaryBlock => 22,
	}
}
