/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Phase 0 smoke test: importable from JS, returns a constant string.
 * Real entity-decoder surface lands in later phases.
 */
export declare function ping(): string
/**
 * Phase 1 parity probe — decode a captured `CSVCMsg_FlattenedSerializer`
 * blob with prost and return structural counts. The JS test compares these
 * against the ts-proto decode of the same bytes.
 */
export interface FlattenedSerializerSummary {
  symbols: number
  fields: number
  serializers: number
}
export declare function decodeFlattenedSerializerSummary(bytes: Uint8Array): FlattenedSerializerSummary
/**
 * Apply one Huffman-decoded opcode (0..=39) to `fp`, reading any operand bits
 * from `br`. Opcode 39 is the no-op end-of-stream marker; ≥40 throws.
 */
export declare function doOp(opcode: number, br: BitBufferNative, fp: FieldPathNative): void
export declare function popSpecial(fp: FieldPathNative, n: number): void
/**
 * Phase 4: napi wrapper for the QuantizedFloat setup function. Test-only —
 * the production path constructs QuantizedFloat directly from classInfo.
 */
export interface QuantizedFloatJs {
  low: number
  high: number
  highLowMul: number
  decMul: number
  offset: number
  bitCount: number
  flags: number
  noScale: boolean
}
export declare function getQuantalizedFloat(bitcount: number, flags?: number | undefined | null, lowValue?: number | undefined | null, highValue?: number | undefined | null): QuantizedFloatJs
/**
 * Per-prop_id container/scalar metadata mirrored to JS (`propIdToInfo`).
 * `containerKey`/`subKey`/`elementType`/`fixedLength` are present only for
 * container element / sub-field props; scalars carry just `name`.
 */
export interface PropInfoJs {
  name: string
  containerKey?: string
  subKey?: string
  /** Typed-array constructor name (e.g. "Uint8Array") for primitive containers. */
  elementType?: string
  fixedLength?: number
  elementTsHint?: string
}
export interface ClassInfoMeta {
  /** `Record<number, string>` — prop id → fully-qualified property name. */
  propIdToName: Record<string, string>
  /**
   * Symbolic decoder ID per prop id. Mirrors the JS `propIdToDecoder` map
   * shape: numbers or `{ type: 0, decoder: idx }` for quantized floats.
   * The numeric value matches the `Decoders.*` constants in
   * `src/parser/entities/constructorFields.ts`.
   */
  propIdToDecoder: Record<string, number>
  /** `Record<number, PropInfoJs>` — prop id → container/scalar metadata. */
  propIdToInfo: Record<string, PropInfoJs>
  /** Count of classes registered. JS uses this only for logging. */
  classCount: number
}
/**
 * Per-packet result struct returned to JS. Mirror of `entity_parser::DecodeResult`
 * with napi-friendly types.
 *
 * 9a/note: numeric pools are typed arrays, not `Vec<T>`. `Vec<f64>` crosses
 * the FFI boundary as `Array<number>` with per-element boxing; `Float64Array`
 * transfers a single contiguous buffer (~10x faster on the JS side).
 */
export interface DecodeResultJs {
  ops: Buffer
  opCount: number
  f64Values: Float64Array
  /**
   * u64 bits reinterpreted as i64 (BigInt64Array transfers without boxing;
   * JS reads them as the same numeric value as `BigInt::from(u64)` would
   * produce when the high bit is unset, and as the negative two's-complement
   * equivalent otherwise — callers that need the unsigned interpretation
   * can use `BigInt.asUintN(64, x)`).
   */
  bigintValues: BigInt64Array
  strings: Array<string>
  blobs: Array<Buffer>
  classNames: Array<string>
  /**
   * Set by `feed_chunk` when Rust paused at a tick boundary and the caller
   * should drain by calling `feed_chunk(empty, …)` again. Always false
   * for `finish_stream`.
   */
  hasMore: boolean
}
/**
 * Phase 2: napi wrapper around the Rust `BitBuffer`. Exposes the same surface
 * as `src/parser/ubitreader.ts` so the JS test suite can run side-by-side
 * against both implementations. Removed once the hot path is fully on Rust
 * (Phase 7); not part of the public package API.
 */
export declare class BitBufferNative {
  constructor(buffer: Uint8Array)
  setTo(buffer: Uint8Array): void
  get RemainingBits(): number
  get RemainingBytes(): number
  ReadUBits(numBits: number): number
  PeekUBitsWithLog(numBits: number): number
  consumePeeked(numBits: number): void
  readBoolean(): boolean
  ReadByte(): number
  readFloat32LE(): number
  ReadUVarInt32(): number
  readUbitVar(): number
  readUbitVarFp(): number
  readVarInt32(): number
  readUVarInt64(): bigint
  decudeUint64(): bigint
  decode_noscale(): number
  decodeVectorNoScale(): Array<number>
  decodeQangleAll3(): Array<number>
  decodeQanglePitchYaw(): Array<number>
  decodeFloatCoord(): number
  decodeVectorFloatCoord(): Array<number>
  readBitCoord(): number
  readBitCoordPres(): number
  readAngle(n: number): number
  decodeAmmo(): number
  decodeNormal(): number
  decodeNormalVec(): Array<number>
  decodeQangleVariant(): Array<number>
  decodeQangleVariantPres(): Array<number>
  skipBytesBetter(bytes: number): void
  /**
   * Reads `len` bytes from the bit stream and returns them as a fresh
   * Uint8Array. The production decoder never crosses the FFI boundary for
   * per-field byte reads (those happen inside Rust), so this allocation-on-
   * every-call shape is fine — it only exists for the Phase 2 parity test.
   */
  readBytes(len: number): Array<number>
  readBytesToSlice(size: number): Array<number>
  readString(): string
}
/**
 * Phase 3: napi wrapper around the Rust `FieldPath`. Like BitBufferNative,
 * this only exists so the existing `fieldPathOps.test.ts` can drive the Rust
 * port. Goes away in Phase 7.
 */
export declare class FieldPathNative {
  /**
   * `path` defaults to `[0;7]` and `last` to `0` (matches the JS test's
   * `makeFieldPath`, not the `parsePaths` initial state which uses -1).
   */
  constructor(path?: Array<number> | undefined | null, last?: number | undefined | null)
  get path(): Array<number>
  get last(): number
}
export declare class EntityDecoderNative {
  constructor()
  /**
   * Stage 4 entry point: feed a chunk of demo bytes; Rust accumulates,
   * walks frames, snappy-decompresses, dispatches SVC messages, runs the
   * entity decoder, and returns the events emitted during processing.
   *
   * `only_game_rules` is honoured the first time DEM_ClassInfo is observed;
   * after that initial setup, the value is locked for the parse.
   *
   * Returns the events emitted while processing the chunk. If the result's
   * `has_more` field is `true`, the caller must drain by calling
   * `feed_chunk` again with an empty slice — Rust paused at a tick
   * boundary to let JS dispatch events with entity state at the previous
   * tick (required for correct gameevent listener semantics).
   */
  feedChunk(bytes: Uint8Array, onlyGameRules: boolean, skipEntities: boolean): DecodeResultJs
  /** Signal end of input. Returns any final events (e.g. trailing tickend). */
  finishStream(): DecodeResultJs
  /**
   * Build the v1-style ClassInfoMeta from the most recent class_info init.
   * Returns `None` if DEM_ClassInfo hasn't been observed yet.
   */
  classInfoMeta(): ClassInfoMeta | null
  /**
   * Build the class tree from the inner CSVCMsg_FlattenedSerializer bytes
   * (already extracted from `CDemoSendTables.data` by JS) and CDemoClassInfo
   * bytes. Returns the prop-id maps for JS to mirror.
   */
  initClassInfo(sendTablesInner: Uint8Array, classInfoBytes: Uint8Array, onlyGameRules: boolean): ClassInfoMeta
  /**
   * Push a baseline blob for `class_id` (called by JS whenever a
   * string-table update changes the `instancebaseline` entry).
   */
  setBaseline(classId: number, data: Uint8Array): void
  /**
   * Decode one CSVCMsg_PacketEntities payload. Returns the batched ops for
   * JS to apply to its entities array + emit events from.
   */
  parseEntityPacket(entityData: Uint8Array, updatedEntries: number, hasPvsVisBits: number): DecodeResultJs
  /** Reset entity state between parses (JS calls when a new `parseDemo` starts). */
  reset(): void
  /**
   * Configure which optional SVC message IDs the frame loop should emit
   * (TAG_OPTIONAL_SVC) instead of skipping. JS resolves the user-facing
   * `{ UM_SayText2: true }`-style settings into the integer SVC IDs and
   * hands them over here once per parse.
   */
  setOptionalSvc(cmdIds: Array<number>): void
  /** Returns `true` if an entity with this id is currently live. */
  hasEntity(entityId: number): boolean
  getEntityClassId(entityId: number): number | null
  getEntityClassName(entityId: number): string | null
  getEntityType(entityId: number): number | null
  /** List every live entity id. */
  getEntityIds(): Array<number>
  /**
   * List live entities whose class_name matches `class_name`. Used by the
   * JS `findEntityIdsByClass` getter and `parser.playerControllers` /
   * `parser.teams`.
   */
  findEntityIdsByClass(className: string): Array<number>
  getPropertyBool(entityId: number, propId: number): boolean | null
  /** Number-typed read. Boolean/i32/u32/f32 widen to f64; vec3/u64/string/blob return None. */
  getPropertyNumber(entityId: number, propId: number): number | null
  getPropertyString(entityId: number, propId: number): string | null
  getPropertyVec3(entityId: number, propId: number): Float64Array | null
  getPropertyBigint(entityId: number, propId: number): bigint | null
  getPropertyBlob(entityId: number, propId: number): Buffer | null
  /**
   * Returns `true` if the entity has a registered value for `prop_id`. Lets
   * JS distinguish "missing" from "default value".
   */
  hasProperty(entityId: number, propId: number): boolean
  /**
   * List every prop_id currently set on this entity. JS uses
   * `propIdToName` to resolve names, then per-id typed getters for values.
   * Used by `parser.getEntity(id)` to build the snapshot object.
   */
  getEntityPropIds(entityId: number): Array<number> | null
  /**
   * Container (vector/array) field keys currently set on this entity. JS reads
   * each via `get_property_container`. Used to complete `parser.getEntity`.
   */
  getEntityContainerKeys(entityId: number): Array<string> | null
  /**
   * Read a container field by its fully-qualified `containerKey`. Builds the
   * matching JS value: a typed array (Uint8Array … BigUint64Array) for
   * primitive containers, a plain `Array` of decoded values otherwise, or an
   * `Array` of objects for vector-of-serializer fields. Returns `None` if the
   * entity / container is unset.
   */
  getPropertyContainer(entityId: number, containerKey: string): unknown | null
}
